Add sqlite_sorterpenalty as tunable
bloomberg/comdb2 pull request #2421
Opened 2020-08-19 22:01 UTC by adizaimi

Add sqlite_sorterpenalty as tunable to control with lrl cost of sorting.
Sqlite can change this default in future so some DBs benefit by having
this value determined in the lrl.

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

2020-08-20 15:19 UTC, riverszhang89 commented
We already have `sqlsortermult` to adjust sorting estimate cost (see sqlite/src/where.c). Maybe we can consolidate these two?

2020-08-20 15:22 UTC, adizaimi commented
Yes, I was hoping to remove sqlsortermult after finding a suitable sqlsorterpenalty that behaves similarly for the ONE DB that is using that feature.

2020-08-20 15:31 UTC, riverszhang89 commented
`sqlsortermult ` has existed a long time. It's possible that it's being used in production. Can I suggest that we keep `sqlsortermult` but move the adjustment in `whereSortingCost()` to `wherePathSolver()`? So it'd look like

```
rCost = (sqlite3LogEstAdd(rUnsorted, aSortCost[isOrdered]) + gbl_sqlite_sorterpenalty) * gbl_sqlite_sortermult;
```

2020-08-20 15:32 UTC, riverszhang89 commented
It's similar to what we have for sqlite_stat4 samples: we have both an addition and a multiplier.

2020-08-20 16:15 UTC, mistachkin commented on sqlite/src/where.c
>            rCost = sqlite3LogEstAdd(rUnsorted, aSortCost[isOrdered]) + 5;
For the #else and #endif here, could you please add the "**/* defined(SQLITE_BUILDING_FOR_COMDB2) */**" suffix?

2020-09-10 17:10 UTC, dorinhogea approved these changes
LGTM, make a hardcoded value configurable.  No complications.
Needs to pass tunables of course.

2020-10-01 17:49 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2020-10-01 20:05 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/373 tests failed</b> &#x26A0;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/096650d/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/096650d/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2421'>Resubmit</a></p>

2020-10-03 02:44 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2020-10-03 04:31 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/373 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>basic_nolibevent_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/21c2677/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/21c2677/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2421'>Resubmit</a></p>

2020-10-03 04:46 UTC, merged

2020-10-03 04:46 UTC, adizaimi commented
Thanks Dorin and Rivers.