logmsg optimization
bloomberg/comdb2 pull request #2478
Opened 2020-09-10 15:51 UTC by riverszhang89

Print only the first 256 characters of the query from an SQL engine in a wrong state, to minimize the time the logmsg mutex is held.

Move the logmsg level check out of the critical section. We have tons of DEBUG messages that aren't printed under the typical logmsg level configuration (INFO or higher). The change may speed it up a bit.

(DRQS 163659422)

2020-09-10 16:00 UTC, nirbhayc approved these changes
LGTM

2020-09-10 16:11 UTC, riverszhang89 commented
> LGTM

@nirbhayc Thank you for the review Nirbhay! Mike had this idea that we can be rid of the logmsg mutex. I'll work on it.

2020-09-10 17:27 UTC, roborivers approved these changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/fab92b1/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/fab92b1/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2478'>Resubmit</a></p>

2020-09-10 17:54 UTC, roborivers reviewed
Lint check:

```diff


@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2020-09-10 19:36 UTC, roborivers approved these changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p>The first 10 failing tests are: <br>ioerror_remsql [core dumped]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/bfbfa9d/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/bfbfa9d/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2478'>Resubmit</a></p>

2020-09-10 19:55 UTC, nirbhayc commented on util/logmsg.c
> +    head = realloc(head, off + size + 1);
Given the log messages won't be too long, I think it's better to start with a static buffer of some decent size and fallback to malloc only for ones that won't fit.

2020-09-11 13:49 UTC, roborivers reviewed
Lint check:

```diff


@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2020-09-11 15:14 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/dbe8026/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/dbe8026/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/dbe8026/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2478'>Resubmit</a></p>

2020-09-11 15:42 UTC, nirbhayc approved these changes
Looks great!

2020-09-11 15:55 UTC, riverszhang89 commented
@nirbhayc Thank you for the review!

2020-09-11 15:55 UTC, merged