schema_lk inversion
bloomberg/comdb2 pull request #2529
Opened 2020-10-08 18:48 UTC by markhannum

I've added instrumentation in hopes of being able to replicate the comdb2del bug brought to our attention by the DBA group.  This isn't ready to merge- I'm submitting the PR to see what RR tests fail.

2020-10-08 20:27 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/374 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart<br>maxtable</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4a01db4/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4a01db4/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2529'>Resubmit</a></p>

2020-10-13 20:25 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/375 tests failed</b> &#x26A0;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/fcdea4d/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/fcdea4d/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2529'>Resubmit</a></p>

2020-10-13 23:36 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/375 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>fingerprints<br>logfill</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/fcdea4d/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/fcdea4d/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2529'>Resubmit</a></p>

2020-10-14 04:33 UTC, adizaimi commented on bdb/locks.c
> +    assert(nlocks == 0);
just reminding you that the asserts will not kick in unless we build in Debug mode.

2020-10-14 04:45 UTC, adizaimi approved these changes
It looks good to me.

2020-10-14 13:03 UTC, merged