Fix some macOS warnings and arm atomic
bloomberg/comdb2 pull request #2532
Opened 2020-10-09 19:07 UTC by adizaimi

Fix some macOS warnings
Arm would not link without -latomic

2020-10-09 19:09 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/prefault_helper.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/sqlglue.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/handle_buf.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2020-10-09 20:26 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/c40179a/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/374 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/c40179a/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/c40179a/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2532'>Resubmit</a></p>

2020-10-12 02:47 UTC, akshatsikarwar commented on db/sqlinterfaces.c
> +    clnt->debug_sqlclntstate = (int)pthread_self();
Change `debug_sqlclntstate` to `pthread_t` instead?

2020-10-12 02:48 UTC, akshatsikarwar commented on lua/sp.c
> +                gbl_break_lua = (int)pthread_self();
Same - declare `gbl_break_lua` as `pthread_t`

2020-10-12 20:45 UTC, mohitkhullar commented on lua/sp.c
> +        gbl_break_all_lua = 1;
The lua part looks good.

2020-10-15 02:24 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/prefault_helper.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/sqlglue.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/handle_buf.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2020-10-15 04:07 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/d9c4e7a/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/375 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_swapfields_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/d9c4e7a/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/d9c4e7a/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2532'>Resubmit</a></p>

2020-10-15 14:00 UTC, merged