Autoanalyze fails when authentication is enabled
bloomberg/comdb2 pull request #2533
Opened 2020-10-10 06:16 UTC by nirbhayc

This is because autoanalyze threads execute analyze operations as anonymous user. Added a mechanism to bypass  authentication for such cases.

Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

2020-10-10 07:55 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/36f2b6d/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/36f2b6d/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>3/375 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>fingerprints<br>sc_truncate_lockorder_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/36f2b6d/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/36f2b6d/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2533'>Resubmit</a></p>

2020-10-21 20:28 UTC, riverszhang89 approved these changes
Very surgical changes - good to merge.

The test failures are probably not related to your changes. But for peace of mind let's resubmit the branch and see whether it'll pass this time.

2020-10-21 22:36 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/d025c95/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/d025c95/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>1/377 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_swapfields_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/d025c95/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/d025c95/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2533'>Resubmit</a></p>

2020-10-22 01:51 UTC, merged

2020-10-22 02:02 UTC, nirbhayc commented
Cherry-picked to 7.0

2020-10-22 02:02 UTC, nirbhayc commented
Thanks for the review @riverszhang89!