Tweak bdb_create_dba_user()
bloomberg/comdb2 pull request #2539
Opened 2020-10-13 20:01 UTC by riverszhang89

Pass an empty string instead of a NULL to supress the following error,
when creating a brand new DBA user:

```
strncpy0(152462): ERROR: NULL src
```

2020-10-14 01:29 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e7aaed1/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/375 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>logfill</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e7aaed1/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e7aaed1/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2539'>Resubmit</a></p>

2020-10-20 14:58 UTC, nirbhayc approved these changes
Ok to merge. Thanks!

2020-10-21 16:04 UTC, riverszhang89 commented
Thank you for the review, Nirbhay!

2020-10-21 16:06 UTC, merged

2020-10-27 17:15 UTC, nirbhayc commented
Cherry-picked to 7.0