fdb: Case-insensitive machine class name comparison
bloomberg/comdb2 pull request #2550
Opened 2020-10-21 03:19 UTC by nirbhayc

This fixes the case where the following query failed as the tier prefix (DEV_), qualifying the database name, specified in the query was compared against the list of valid tiers hashed in lowercase.

`select * from DEV_testdb.t`

N.B. Older Comdb2 version (R6) only supported uppercase tier prefixes.

Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

2020-10-21 05:12 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/29abff0/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/29abff0/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>1/377 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/29abff0/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/29abff0/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2550'>Resubmit</a></p>

2020-10-21 14:41 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/29abff0/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/377 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>serialstep [setup failure]<br>socksql_master_swings<br>fingerprints<br>sc_constraints_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/29abff0/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/29abff0/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2550'>Resubmit</a></p>

2020-10-27 15:30 UTC, mponomar approved these changes

2020-10-27 16:03 UTC, merged

2020-10-27 16:18 UTC, nirbhayc commented
Cherry-picked to 7.0.