fix case when single rows take out dohsql quota
bloomberg/comdb2 pull request #2552
Opened 2020-10-21 18:16 UTC by dorinhogea

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

Large rows can take over quota for a doh queue and deadlocks in current implementation; this is because we cache the rows to skip a potential malloc when a new row is retrieved (and we keep counting them against the quota).  Fix is to detect the idle time and free the cached, which free the quota in return.

2020-10-21 19:54 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/dd4e920/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/377 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>systbl_proc_leak<br>fingerprints</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/dd4e920/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/dd4e920/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2552'>Resubmit</a></p>

2020-10-21 23:29 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/dd4e920/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/377 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>serialstep [setup failure]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/dd4e920/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/dd4e920/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2552'>Resubmit</a></p>

2020-10-23 17:02 UTC, mponomar approved these changes

2020-10-23 17:06 UTC, dorinhogea commented
Thank you

2020-10-23 17:06 UTC, merged