Hostname support
bloomberg/comdb2 pull request #2554
Opened 2020-10-21 21:58 UTC by akshatsikarwar

This makes mapping `fd` -> `hostname`, independent of whether `fd` is obtained from `sbuf`, `socket` or `libevent`. It wan't appropriate to have that facility burried in `sbuf` library.

I will check if this is suitable for use `os compat` as well.

2020-10-21 21:59 UTC, roborivers reviewed
Lint check:

```diff


@@ util/hostname_support.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2020-10-22 00:56 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9bc1f77/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/377 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ssl_san<br>ssl_set_cmd<br>ssl_dbname</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9bc1f77/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9bc1f77/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2554'>Resubmit</a></p>

2020-10-22 03:09 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/1be2760/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/1be2760/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>1/378 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_constraints_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/1be2760/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/1be2760/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2554'>Resubmit</a></p>

2020-10-22 11:27 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/aee7229/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/aee7229/smoketest.log'>Error &#x26A0; </a>.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/aee7229/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>336/378 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>odh_blobs [core dumped]<br>unionpar_maxqueue [core dumped]<br>dohsql_leaks [core dumped]<br>timepart_retention1 [core dumped]<br>truncatesc_offline_generated [core dumped]<br>simple_timepart_reptimeout_generated [core dumped]<br>simple_timepart [core dumped]<br>systable_locking [core dumped]<br>systable_locking_extralock_generated [core dumped]<br>sc_timepart_logicalsc_generated [core dumped]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/aee7229/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/aee7229/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2554'>Resubmit</a></p>

2020-10-22 13:16 UTC, akshatsikarwar commented
OK This needs more work to fix the leak. I'm thinking of introducing an out param for use in ssl.

2020-10-22 14:41 UTC, riverszhang89 commented
Yes. In sbuf client mode, the hostname memory is leaked in ssl_verify_ca. Thank you for catching it! Maybe we could try the following?

```
#if !SBUF2_SERVER
free(host);
#endif
```

2020-10-22 18:51 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e5930eb/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e5930eb/smoketest.log'>Error &#x26A0; </a>.<br>Failed to compile.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e5930eb/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e5930eb/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2554'>Resubmit</a></p>

2020-10-22 20:02 UTC, akshatsikarwar commented
> #if !SBUF2_SERVER

We could try that. However, I'm opposed to using that anywhere outside of `sbuf2` library. I've added new api which accepts an out-param and using that in ssl support code.

2020-10-22 20:03 UTC, akshatsikarwar commented
Although, it appears that macro is widely used in ssl code already!

2020-10-22 20:40 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ba7742d/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/379 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sql_func_mem_leak<br>concurrent_sql<br>sc_constraints_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ba7742d/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ba7742d/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2554'>Resubmit</a></p>

2020-10-22 22:33 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ba7742d/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/379 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>leakcheck<br>concurrent_sql</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ba7742d/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ba7742d/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2554'>Resubmit</a></p>

2020-10-23 02:10 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e5811d2/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/379 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings [core dumped]<br>concurrent_sql<br>logfill</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e5811d2/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e5811d2/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2554'>Resubmit</a></p>

2020-10-23 03:25 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/46e9715/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/379 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>concurrent_sql</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/46e9715/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/46e9715/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2554'>Resubmit</a></p>

2020-10-23 16:51 UTC, merged