Fix analyze crash on database exit
bloomberg/comdb2 pull request #2559
Opened 2020-10-26 19:44 UTC by riverszhang89

If an analyze's commit or rollback fails to dispatch (which happens quite often during clean-exit), the database will trigger the in-use-rqid assertion when cleaning up the analyze's OSQL structures.

The fix is unregister the analyze thread from the OSQL checkboard if commit/rollback fails.

2020-10-26 21:44 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/52d68f9/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/380 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ruleset_no_fp_generated [core dumped]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/52d68f9/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/52d68f9/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2559'>Resubmit</a></p>

2020-10-27 16:58 UTC, roborivers approved these changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/06afb79/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/06afb79/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2559'>Resubmit</a></p>

2020-11-04 19:29 UTC, mistachkin approved these changes
Looks good to me.

2020-11-04 19:47 UTC, riverszhang89 commented
@mistachkin Thank you for the review!

2020-11-04 19:48 UTC, merged