Fixes to Semle complains
bloomberg/comdb2 pull request #2562
Opened 2020-10-27 18:54 UTC by adizaimi

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

2020-10-27 19:24 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/947070c/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/947070c/smoketest.log'>Error &#x26A0; </a>.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>379/379 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>cldeadlock [setup failure]<br>queuedb_rollover [setup failure]<br>sirace [setup failure]<br>truncatesc [setup failure]<br>socksql_master_swings [setup failure]<br>maxtable [setup failure]<br>incremental_backup_load [setup failure]<br>systable_locking [setup failure]<br>odh_blobs [setup failure]<br>incrementalcopy [setup failure]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/947070c/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/947070c/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2562'>Resubmit</a></p>

2020-10-27 21:42 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/c9fcc9f/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/c9fcc9f/smoketest.log'>Error &#x26A0; </a>.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>379/379 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover [setup failure]<br>sirace [setup failure]<br>cldeadlock [setup failure]<br>truncatesc [setup failure]<br>socksql_master_swings [setup failure]<br>maxtable [setup failure]<br>incremental_backup_load [setup failure]<br>systable_locking [setup failure]<br>odh_blobs [setup failure]<br>incrementalcopy [setup failure]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/c9fcc9f/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/c9fcc9f/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2562'>Resubmit</a></p>

2020-10-28 06:54 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/47c4644/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/379 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>tunables<br>queuedb_rollover</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/47c4644/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/47c4644/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2562'>Resubmit</a></p>

2020-10-28 13:36 UTC, riverszhang89 commented on db/osqlcheckboard.c
> +static inline int insert_into_checkerboard(osql_checkboard_t *cb,
What's the warning here?

2020-10-28 19:57 UTC, adizaimi commented on db/osqlcheckboard.c
> +static inline int insert_into_checkerboard(osql_checkboard_t *cb,
local variable hides global variable.

2020-10-28 20:00 UTC, riverszhang89 commented on db/osqlcheckboard.c
> +static inline int insert_into_checkerboard(osql_checkboard_t *cb,
Got it! Thank you!

2020-11-02 14:46 UTC, riverszhang89 approved these changes
Good to merge.

2020-11-02 23:20 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/a616510/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/380 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ruleset_no_fp_generated [core dumped]<br>tunables<br>logfill<br>sc_constraints_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/a616510/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/a616510/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2562'>Resubmit</a></p>

2020-11-05 22:04 UTC, merged

2020-11-05 22:05 UTC, adizaimi commented
Thank you Rivers.