Copy blobs only once
bloomberg/comdb2 pull request #2565
Opened 2020-11-03 17:40 UTC by riverszhang89

When retrieving a blob, we copy it from berkdb (if uncompressed) or bdb (if compressed) to sqlite, so that the memory is owned by sqlite. However, we can get rid of the extra copy by passing sqlite's allocator to berkdb and bdb and allocate memory directly from it. This way it'll be faster and require less memory.

(DRQS 163035031)

2020-11-03 20:48 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5949998/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/380 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ruleset [core dumped]<br>sql_func_mem_leak</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5949998/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5949998/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2565'>Resubmit</a></p>

2020-11-03 23:06 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5949998/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/380 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_constraints_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5949998/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5949998/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2565'>Resubmit</a></p>

2020-11-04 19:33 UTC, mistachkin approved these changes
Looks good.

2020-11-04 20:00 UTC, riverszhang89 commented
Thank you for the review, Joe!

2020-11-04 20:00 UTC, merged