Consistent thread pool handling of free lists by work threads.
bloomberg/comdb2 pull request #2566
Opened 2020-11-03 20:10 UTC by mistachkin

Work threads within a thread pool are setup to (possibly) remove themselves from their associated thread pool (and its associated free thread list) after completion of each work item if the current number of threads exceeds its predefined limit.  This can occur if one or more threads are forced into existence via the "admin" flag or similar thread limit overrides.

The changes in this pull request make handling of free thread lists consistent with thread limit override semantics and avoid an abort() being triggered under some circumstances.

Signed-off-by: mistachkin <joe@mistachkin.com>

2020-11-03 20:20 UTC, adizaimi approved these changes
This looks good to me.

2020-11-03 20:21 UTC, mponomar approved these changes

2020-11-03 22:03 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/380 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sql_func_mem_leak<br>manual_partition</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/6db0675/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/6db0675/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2566'>Resubmit</a></p>

2020-11-04 14:20 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/380 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sql_func_mem_leak<br>cdb2_close</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/6db0675/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/6db0675/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2566'>Resubmit</a></p>

2020-11-04 15:47 UTC, merged