Add tunable which prevents mixed ddl and dml write schedules
bloomberg/comdb2 pull request #2568
Opened 2020-11-04 18:58 UTC by markhannum

We have to prevent "mixed" ddl and dml schedules for now.  The fundamental issue is the handling of the schema-lock on the master: currently we acquire the schema-lk when handling OSQL_DONE before finalizing any outstanding schema-changes.  If we've executed DML as part of the same transaction, we'll be holding locks on those tables and pages while blocking on schema-lock (lock-inversion).

There might be other approaches that would allow us to bring this back.  The simplest is to have the master acquire the schemalk in osql_process_schemachange after all of the outstanding schema-changes have completed.  We'd avoid lock-inversion by maintaining the schema writelock while executing the transaction's dml.  This would only be feasible if we limit the size of mixed dml / ddl transactions, and if we prevent it outright for writes which would cause cascades (which could carry an unknown number of additional writes).

This is being actively worked on (and discussed).  Not yet ready for review.

2020-11-04 18:59 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2020-11-04 19:46 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/71e027a/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/71e027a/smoketest.log'>Error &#x26A0; </a>.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>380/380 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>odh_blobs [core dumped]<br>sirace [core dumped]<br>incremental_backup [core dumped]<br>maxtable [core dumped]<br>incremental_backup_usenames [core dumped]<br>incremental_backup_load [core dumped]<br>sicountbug [core dumped]<br>serial_randtest2 [core dumped]<br>scindex_logicalsc_generated [core dumped]<br>scindex [core dumped]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/71e027a/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/71e027a/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2568'>Resubmit</a></p>

2020-11-04 22:49 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2020-11-05 00:35 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/381 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sql_func_mem_leak<br>verify_error<br>sc_transactional<br>sc_transactional_logicalsc_generated<br>sc_truncate_lockorder_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ad3ff18/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ad3ff18/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2568'>Resubmit</a></p>

2020-11-05 13:50 UTC, markhannum commented
This only lacks a test case which would demonstrates why mixed mode would deadlock prior to these changes.  I will create this today.

2020-11-05 13:54 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2020-11-05 15:33 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/19a85fd/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/381 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sql_func_mem_leak</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/19a85fd/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/19a85fd/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2568'>Resubmit</a></p>

2020-11-05 17:39 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2020-11-05 19:13 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/382 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_constraints_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e99cd99/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e99cd99/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2568'>Resubmit</a></p>

2020-11-06 16:49 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2020-11-06 18:23 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5750867/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5750867/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5750867/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2568'>Resubmit</a></p>

2020-11-09 13:09 UTC, nirbhayc approved these changes
Looks good!

2020-11-13 22:05 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2020-11-13 22:23 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/a1d26395/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/a1d26395/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2568'>Resubmit</a></p>

2020-11-17 16:25 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2020-11-17 18:15 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/384 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sql_func_mem_leak</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/0bb00ceb/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/0bb00ceb/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2568'>Resubmit</a></p>

2020-11-17 22:06 UTC, merged