Backup logfiles into a dir instead of deleting them
bloomberg/comdb2 pull request #2583
Opened 2020-11-16 20:06 UTC by adizaimi

Move the logfiles instead of deleting them if lrl option is set:

   location backup_logfiles_dir /bigstore/backup/%dbname

This will allow for ability to restore to any point in time given that
logs will always be available. This can work well with a reasonable
maintenance schedule to backup to tape and cleanup log files
older than a preset value (ex a month).

If directory ends with %dbname, we will substitute the actual dbname
to use as directory where the logfiles will be backed up.

Note that if the backup_logfiles_dir is an nfs mounted directory
which is accessible from all the nodes in a cluster, correctness
of the backedup logfiles is ensured because only the master is able
to move logfiles to the backup directory (amongst other restrictions,
we only delete/move a logfile if there is no reference to a transaction
in blkseq).

Added unit test which exercises this feature.

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

2020-11-16 22:08 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/77186a4c/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/77186a4c/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>1/384 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>verify_db_parallel_generated [core dumped]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/77186a4c/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/77186a4c/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2583'>Resubmit</a></p>

2020-11-17 02:02 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5beb90fd/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5beb90fd/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>2/384 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>verify_db_parallel_generated [core dumped]<br>sql_func_mem_leak</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5beb90fd/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5beb90fd/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2583'>Resubmit</a></p>

2020-11-17 20:29 UTC, markhannum approved these changes
Awesome .. very straightforward .. good to merge!

2020-11-17 22:10 UTC, merged

2020-11-17 22:10 UTC, adizaimi commented
Thank you Mark.