Use protobuf allocator for newsql unpacking
bloomberg/comdb2 pull request #2591
Opened 2020-11-20 05:01 UTC by riverszhang89

It may also help reduce heap fragmentation, as protobuf allocation will be done in its own allocator.

2020-11-20 06:59 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/386 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>backup_logfiles<br>sc_swapfields_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/d38d248c/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/d38d248c/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2591'>Resubmit</a></p>

2020-11-24 14:37 UTC, roborivers approved these changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/d38d248c/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/d38d248c/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2591'>Resubmit</a></p>

2020-11-24 17:55 UTC, adizaimi commented
The main goal here is to have this appear under the protobuf category?

2020-11-24 18:22 UTC, riverszhang89 commented
Yes Adi!

2020-11-24 19:16 UTC, adizaimi approved these changes
LGTM

2020-11-27 15:41 UTC, riverszhang89 commented
Thank you for the review, @adizaimi !

2020-11-27 15:41 UTC, merged