Stop the ongoing verify if db is exiting
bloomberg/comdb2 pull request #2595
Opened 2020-11-30 22:11 UTC by adizaimi

When db is sent exit and if there are verify threads working, currently the db will alarm every 10s and wait till timeout (5 min):
```
Waiting for threads to stop
12 registered threads running:-
   0) tid 83914:req
   1) tid 83915:req
....
id 5 11/30/2020 16:59:50 localhost pid 17474 task cdb2sql EXEC PROCEDURE sys.cmd.verify("updlog","parallel","verbose")
Alarm clock
```

Where client currently shows a timeout error:
```
[EXEC PROCEDURE sys.cmd.verify("updlog","parallel","verbose")] failed with rc -1 cdb2_next_record_int: Timeout while reading response from server
```
 

This patch will make the verify threads exit if db is exiting, and will send that info back to the client:
* server will display`DB exiting, stopping verify` in the logs
* client will print same message as server if running verify in verbose mode, otherwise will simply show verify error:
```
(out='DB exiting, stopping verify')
[EXEC PROCEDURE sys.cmd.verify("updlog","parallel","verbose")] failed with rc -3 [sys.comdb_verify(tbl, mode, ver...]:2: Verify failed.
```

2020-11-30 23:52 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/386 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>verify_db_parallel_generated [core dumped]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/059cfe7e/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/059cfe7e/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2595'>Resubmit</a></p>

2020-12-01 07:07 UTC, adizaimi commented
The failure with verify_db_parallel_generated [core dumped] is an unrelated issue and is addressed by https://github.com/bloomberg/comdb2/pull/2597.

2020-12-01 17:08 UTC, markhannum approved these changes
Very simple .. obviously correct .. good to merge!

2020-12-01 17:16 UTC, adizaimi commented
Thank you Mark!

2020-12-01 17:30 UTC, merged