Synchronous osql cancellation
bloomberg/comdb2 pull request #2606
Opened 2020-12-08 17:26 UTC by riverszhang89

An osql cancellation is done asynchronously in the sense that a replicant doesn't wait for it to complete on the master node. If there's a large number of rollbacks or client disconnects, and the master can't cancel them faster than they arrive, these requests will pile up on the master.

This patch makes osql cancellation synchronous, so that the master can be protected in this case.

(DRQS 164512050)

2020-12-08 19:05 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/24545db6/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/24545db6/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>9/388 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>selectv_recom_range<br>selectv_rcode_serialretry_generated<br>selectv_rcode_serialize_reads_like_writes_generated<br>selectv_rcode_force_commit_generated<br>selectv_rcode<br>selectv_rcode_disable_svonly_nop_generated<br>selectv_range<br>occ_selectv</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/24545db6/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/24545db6/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2606'>Resubmit</a></p>

2020-12-09 00:28 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/935cc42e/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/935cc42e/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/935cc42e/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2606'>Resubmit</a></p>

2020-12-10 00:42 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4b428240/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4b428240/smoketest.log'>Error &#x26A0; </a>.<br>Failed to compile.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4b428240/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4b428240/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2606'>Resubmit</a></p>

2020-12-10 02:29 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/98b1ab4b/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/389 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>basic_rowlocks_generated [core dumped]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/98b1ab4b/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/98b1ab4b/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2606'>Resubmit</a></p>

2020-12-11 14:26 UTC, adizaimi approved these changes
LGTM.

2020-12-11 17:21 UTC, riverszhang89 commented
@adizaimi Thank you for the review!

2020-12-11 17:22 UTC, merged