Use hash to find fileids rather than walking a list
bloomberg/comdb2 pull request #2630
Opened 2021-01-05 22:47 UTC by markhannum

We've found this list to be a performance killer during recover for databases which have a large number of btrees.  I've added a simple plhash filled reference to the adj_fileid index.  This is a work-in-progress.

2021-01-06 00:44 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/394 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>timepart_auth</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/45ce54d4/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/45ce54d4/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2630'>Resubmit</a></p>

2021-01-07 15:29 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>239/394 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>truncatesc<br>truncatesc_offline_generated<br>incremental_backup_usenames<br>incremental_backup<br>incremental_backup_load<br>dohsql_leaks<br>temp_table_truncate_leak<br>temp_table_cursor_leak<br>sql_datetime_interval_arithmetic_leak<br>sc_ddl_backout_rowlocks_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/da22edc6/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/da22edc6/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2630'>Resubmit</a></p>

2021-01-07 15:30 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>241/394 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>truncatesc<br>truncatesc_offline_generated<br>incremental_backup_usenames<br>incremental_backup<br>incremental_backup_load<br>dohsql_leaks<br>temp_table_truncate_leak<br>temp_table_cursor_leak<br>sql_datetime_interval_arithmetic_leak<br>sc_ddl_backout_rowlocks_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/da22edc6/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/da22edc6/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2630'>Resubmit</a></p>

2021-01-07 19:07 UTC, roborivers submitted a review, later dismissed
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/704141f9/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/704141f9/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2630'>Resubmit</a></p>

2021-01-11 20:12 UTC, adizaimi commented on berkdb/db/db.c
>  	u_int32_t maxid;
this is now no longer used

2021-01-11 23:24 UTC, adizaimi approved these changes
This looks good. One thing we should probably do is to cleanup on exit, in a later PR.

2021-01-12 15:55 UTC, adizaimi approved these changes

2021-01-12 16:11 UTC, merged