Add id to fname hash to dbreg
bloomberg/comdb2 pull request #2633
Opened 2021-01-06 18:39 UTC by markhannum

This is to speed up dbreg_to_fname, which prior to this PR would walk the list of fname structures searching for a specific id.  This is a WIP.  This, along with https://github.com/bloomberg/comdb2/pull/2630 and https://github.com/bloomberg/comdb2/pull/2631 addresses the recovery slowness issue that we see when a database has a large number of btrees.

2021-01-06 20:30 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/394 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>truncatesc [core dumped]<br>sc_truncate [core dumped]<br>truncatesc_offline_generated [core dumped]<br>logfill</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9b6b9a8c/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9b6b9a8c/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2633'>Resubmit</a></p>

2021-01-07 21:00 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/394 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>truncatesc_offline_generated [core dumped]<br>truncatesc [core dumped]<br>socksql_master_swings<br>sc_truncate</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/1e650648/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/1e650648/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2633'>Resubmit</a></p>

2021-01-08 07:38 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/b933c7ae/smoketest.log'>Error &#x26A0; </a>.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>393/394 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sirace [setup core dumped]<br>truncatesc [setup core dumped]<br>truncatesc_offline_generated [setup core dumped]<br>cldeadlock [setup core dumped]<br>sc_async_constraints_logicalsc_generated [setup core dumped]<br>sicomplex [setup core dumped]<br>sirandtest [setup core dumped]<br>sicountbug2 [setup core dumped]<br>sicountbug [setup core dumped]<br>serial_randtest2 [setup core dumped]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/b933c7ae/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/b933c7ae/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2633'>Resubmit</a></p>

2021-01-11 20:02 UTC, mponomar approved these changes
Looks good Mark, thanks!  One more list scan going away.

2021-01-12 16:47 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/7d125459/smoketest.log'>Error &#x26A0; </a>.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/395 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated [core dumped]<br>load_cache [core dumped]<br>load_cache_autocache_generated [core dumped]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/7d125459/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/7d125459/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2633'>Resubmit</a></p>

2021-01-12 19:47 UTC, roborivers approved these changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ad4bab25/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ad4bab25/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2633'>Resubmit</a></p>

2021-01-12 20:01 UTC, nirbhayc approved these changes
Looks good!

2021-01-12 20:02 UTC, markhannum commented
Thanks Nirbhay!

2021-01-12 20:02 UTC, merged

2021-01-12 20:15 UTC, roborivers approved these changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ad4bab25/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ad4bab25/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2633'>Resubmit</a></p>