Fix prepare retry case inside transaction
bloomberg/comdb2 pull request #2639
Opened 2021-01-09 03:48 UTC by mohitkhullar

Don't set client error in param retry case

2021-01-09 04:20 UTC, mohitkhullar commented
Test case will be added in robomark

2021-01-09 05:40 UTC, roborivers approved these changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/01b3f224/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/01b3f224/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2639'>Resubmit</a></p>

2021-01-11 13:03 UTC, nirbhayc approved these changes
Looks good.

2021-01-11 19:36 UTC, mponomar approved these changes
Looks good!

2021-01-12 03:49 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/395 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>backup_logfiles</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/01b3f224/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/01b3f224/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2639'>Resubmit</a></p>

2021-01-12 14:31 UTC, mohitkhullar commented
Passed the robomark test

2021-01-12 14:31 UTC, merged