Skip check for ulonglong on startup (upmerge from 7.0)
bloomberg/comdb2 pull request #2650
Opened 2021-01-15 18:26 UTC by nirbhayc

PR-2594 fixed the logic of broken forbid_ulonglong tunable that was added to
disallow use of ulonglong types in a table schema. This new logic, however,
now prevents existing databases from starting that have been using ulonglong.

The change, introduced by this PR, skips this check until the database is fully
up, allowing affected databases to start ignoring forbid_ulonglong tunable in
the lrl. The tunable becomes effective and is enforced once the database has
started. Besides, maintenance operations (like rebuild, truncate) should succeed
on old u_longlong tables

An error is always logged, unconditionally, to allow enabling ALRMs

Refer: https://github.com/bloomberg/comdb2/pull/2594

Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

To help us review your pull request, please consider providing an overview of the following:
* What is the type of the change (bug fix, feature, documentation and etc.) ?
* What are the current behavior and expected behavior, if this is a bugfix ?
* What are the steps required to reproduce the bug, if this is a bugfix ?
* What is the current behavior and new behavior, if this is a feature change or enhancement ?
* [Optional] Why is the new behavior better than the current behavior, if this is a feature change ?

2021-01-15 22:56 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/395 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>sc_async_constraints_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/351862be/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/351862be/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2650'>Resubmit</a></p>

2021-01-22 18:03 UTC, roborivers approved these changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e06bdf2d/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e06bdf2d/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2650'>Resubmit</a></p>

2021-01-22 18:19 UTC, roborivers approved these changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e06bdf2d/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e06bdf2d/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2650'>Resubmit</a></p>

2021-01-22 18:58 UTC, mponomar approved these changes

2021-01-22 18:59 UTC, merged