Convert to real function bdb_has_tablename_locked
bloomberg/comdb2 pull request #2656
Opened 2021-01-19 22:00 UTC by adizaimi

Instead of having bdb_assert_tablename_locked assert on the return value
(which also means if debug is not enabled, the whole work that function does
is wasted), convert it to a real function which we can use independently,
and assert on the value returned from the existing callers.

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

2021-01-19 23:31 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/f8af6256/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/f8af6256/smoketest.log'>Error &#x26A0; </a>.<br>Failed to compile.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/f8af6256/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/f8af6256/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2656'>Resubmit</a></p>

2021-01-20 21:07 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9f782f5c/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9f782f5c/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>2/396 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>cldeadlock [core dumped]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9f782f5c/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9f782f5c/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2656'>Resubmit</a></p>

2021-01-21 20:57 UTC, markhannum approved these changes
Good to merge

2021-01-22 02:37 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9f782f5c/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9f782f5c/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>2/397 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>backup_logfiles<br>op_makerecord</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9f782f5c/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9f782f5c/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2656'>Resubmit</a></p>

2021-01-22 03:34 UTC, merged

2021-01-22 03:34 UTC, adizaimi commented
Thank you Mark!