Speedup truncate: cache version_num in process_unused_files
bloomberg/comdb2 pull request #2660
Opened 2021-01-20 22:10 UTC by adizaimi

When a db has many tables tables, truncate will take a long time because
delfiles will go through the entire directory to find files matching pattern
to be put in list for deletion. The inneficiency is because we fetch
version_num for every file in the directory: this checkin improves that
by caching those values in a local array.
Also dont check if tbl is under schemachange when we have tbllock.

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

2021-01-20 23:31 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e211e771/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e211e771/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: Success &#10003;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated [core dumped]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e211e771/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e211e771/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2660'>Resubmit</a></p>

2021-01-25 18:43 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/39c4fd44/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/39c4fd44/smoketest.log'>Error &#x26A0; </a>.<br>Failed to compile.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/39c4fd44/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/39c4fd44/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2660'>Resubmit</a></p>

2021-01-25 21:32 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/c1cac112/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/c1cac112/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>2/397 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>backup_logfiles<br>op_makerecord</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/c1cac112/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/c1cac112/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2660'>Resubmit</a></p>

2021-01-26 02:31 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/72cddac0/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/72cddac0/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/72cddac0/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2660'>Resubmit</a></p>

2021-01-27 21:08 UTC, mponomar approved these changes
Looks correct.

2021-01-28 03:05 UTC, merged

2021-01-28 03:05 UTC, adizaimi commented
Thank you Mike!