Cache sql statements triggered internally
bloomberg/comdb2 pull request #2662
Opened 2021-01-21 01:59 UTC by nirbhayc

Part-2 of there work done in #2310 
Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

2021-01-21 02:04 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2021-01-21 03:42 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/6c26f40f/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/6c26f40f/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/6c26f40f/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2662'>Resubmit</a></p>

2021-01-22 03:48 UTC, adizaimi commented on db/sqlinterfaces.c
> +            clnt->prep_rc = rc =
May I suggest you merge the two else-s into one?
```
found = 0;
If (gbl_enable) {
  ..
  if(stmt_find) {
     ...
     found = 1;
   }
}
if (!found) {
   prepare();
}
  ```

2021-01-22 21:39 UTC, riverszhang89 submitted a review, later dismissed

2021-01-22 22:05 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2021-01-22 23:30 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/87a273e4/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p>The first 10 failing tests are: <br>concurrent_sql</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/87a273e4/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/87a273e4/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2662'>Resubmit</a></p>

2021-01-22 23:49 UTC, riverszhang89 approved these changes

2021-01-23 01:29 UTC, merged

2021-01-23 01:29 UTC, nirbhayc commented
Thanks for the review @riverszhang89 !