Exclude first internal entry if should not be displayed
bloomberg/comdb2 pull request #2677
Opened 2021-01-24 02:28 UTC by adizaimi

Currenctly `select * from comdb2_tunables` includes
`(name='legacy_schema', description='Only allow legacy compatible csc2 schema', type='BOOLEAN', value='OFF', read_only='N')`
because it happens to be first item returned by hash_first().
This checkin fixes that by keep doing hash_next() until we find a non internal
tunables on open().

Also, adding a new column to print all flags in DEBUG mode so entry would look
like this:
`(name='legacy_schema', description='Only allow legacy compatible csc2 schema', type='BOOLEAN', value='OFF', flags='EXPERIMENTAL INTERNAL READEARLY ', read_only='N')`

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

To help us review your pull request, please consider providing an overview of the following:
* What is the type of the change (bug fix, feature, documentation and etc.) ?
* What are the current behavior and expected behavior, if this is a bugfix ?
* What are the steps required to reproduce the bug, if this is a bugfix ?
* What is the current behavior and new behavior, if this is a feature change or enhancement ?
* [Optional] Why is the new behavior better than the current behavior, if this is a feature change ?

2021-01-24 03:49 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/397 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/905342fb/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/905342fb/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2677'>Resubmit</a></p>

2021-01-24 08:10 UTC, roborivers reviewed
<p>Sysbench Transactions Per Second (commit: 905342fb):</p>

<pre lang=diff>
@@ sysbench/select_random_ranges @@
-6.22%
</pre>

2021-01-25 15:21 UTC, nirbhayc approved these changes

2021-01-25 15:24 UTC, adizaimi commented on sqlite/ext/comdb2/tunables.c
> +#endif
Oh, I don't know, I added it as debug info to catch issue, but if you thing is useful, sure.

2021-01-25 15:28 UTC, nirbhayc commented on sqlite/ext/comdb2/tunables.c
> +#endif
I think it's a good idea. Also, let's keep this column hidden.

2021-01-25 15:28 UTC, nirbhayc commented on sqlite/ext/comdb2/tunables.c
> +#endif
Okay to merge.

2021-01-25 17:56 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/397 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_swapfields_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/04797e54/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/04797e54/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2677'>Resubmit</a></p>

2021-01-26 18:30 UTC, nirbhayc approved these changes

2021-01-26 19:08 UTC, merged

2021-01-26 19:08 UTC, adizaimi commented
Thank you Nirbhay!