Print in reqlog table deadlock count
bloomberg/comdb2 pull request #2678
Opened 2021-01-24 07:34 UTC by adizaimi

Print in reqlog number of times which writing to a table
resulted in a deadlock, ex:

```
01/24 02:33:10:   DIFF REQUEST STATS FOR TABLE 't1'
01/24 02:33:10:       OSQL_USEDB             4
01/24 02:33:10:       OSQL_QBLOB             13
01/24 02:33:10:       OSQL_UPDREC            5
01/24 02:33:10:       OSQL_UPDCOLS           5
01/24 02:33:10:       OSQL_DONE_SNAP         6
01/24 02:33:10:       OSQL_SCHEMACHANGE      1
01/24 02:33:10:       OSQL_INSERT            8
01/24 02:33:10:       OSQL_STARTGEN          6
01/24 02:33:10:       nsql                   11
01/24 02:33:10:       inserted rows          7
01/24 02:33:10:       updated rows           4
01/24 02:33:10:       deadlock count         2
```

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

To help us review your pull request, please consider providing an overview of the following:
* What is the type of the change (bug fix, feature, documentation and etc.) ?
* What are the current behavior and expected behavior, if this is a bugfix ?
* What are the steps required to reproduce the bug, if this is a bugfix ?
* What is the current behavior and new behavior, if this is a feature change or enhancement ?
* [Optional] Why is the new behavior better than the current behavior, if this is a feature change ?

2021-01-24 09:01 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e1c13870/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/397 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e1c13870/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e1c13870/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2678'>Resubmit</a></p>

2021-01-24 15:12 UTC, roborivers reviewed
<p>Sysbench Transactions Per Second (commit: e1c13870):</p>

<pre lang=diff>
@@ sysbench/select_random_points @@
-8.08%
@@ sysbench/select_random_ranges @@
-7.18%
</pre>

2021-01-25 13:21 UTC, nirbhayc approved these changes
Looks good.

2021-01-25 15:23 UTC, mponomar approved these changes
Looks good!

2021-01-25 15:37 UTC, merged

2021-01-25 15:37 UTC, adizaimi commented
Thank you Nirbhay and Mike!