Auth: cache user passwords
bloomberg/comdb2 pull request #2686
Opened 2021-01-27 15:34 UTC by nirbhayc

Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

2021-01-27 15:39 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2021-01-27 17:23 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/fe00fe5c/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/fe00fe5c/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/fe00fe5c/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2686'>Resubmit</a></p>

2021-03-03 20:29 UTC, riverszhang89 requested changes

2021-03-03 20:29 UTC, riverszhang89 commented on bdb/llmeta.c
> +lrucache *password_cache; // saved password hashes
static

2021-03-03 20:29 UTC, riverszhang89 commented on bdb/llmeta.c
> +    return memcmp(key1, key2, PASSWD_HASH_SZ);
CRYPTO_memcmp

2021-03-05 15:39 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2021-03-05 15:51 UTC, riverszhang89 commented
Looks great. Would you want to squash the commits so that I can approve?

2021-03-05 16:01 UTC, mponomar reviewed
I don't see an lrucache_release?  It'd be needed for things to get removed from the list.

2021-03-05 17:03 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/3e1ef50e/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/400 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>sc_timepart_logicalsc_generated<br>simple_timepart_reptimeout_generated<br>simple_timepart<br>sc_timepart</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/3e1ef50e/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/3e1ef50e/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2686'>Resubmit</a></p>

2021-03-05 20:19 UTC, nirbhayc commented
> Looks great. Would you want to squash the commits so that I can approve?

Done

2021-03-05 20:20 UTC, nirbhayc commented
> I don't see an lrucache_release? It'd be needed for things to get removed from the list.

I didn't know that. Added in the latest commit. Thank you for pointing.

2021-03-05 20:24 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2021-03-05 22:05 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e32d1509/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/401 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>simple_timepart_reptimeout_generated<br>sc_timepart_logicalsc_generated<br>simple_timepart</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e32d1509/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e32d1509/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2686'>Resubmit</a></p>

2021-05-03 20:15 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2021-05-03 21:30 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e32d1509/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e32d1509/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>2/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>op_makerecord<br>tunables</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e32d1509/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e32d1509/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2686'>Resubmit</a></p>

2021-05-04 13:30 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2021-05-04 14:47 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/938148f1/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>pmux</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/938148f1/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/938148f1/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2686'>Resubmit</a></p>

2021-05-04 15:30 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2021-05-04 17:09 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/938148f1/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>op_makerecord</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/938148f1/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/938148f1/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2686'>Resubmit</a></p>

2021-06-02 17:22 UTC, riverszhang89 approved these changes

2021-06-02 17:27 UTC, merged

2021-06-02 17:27 UTC, nirbhayc commented
@riverszhang89 Thanks!