ulonglong: Allow time partitions to rollout new shards
bloomberg/comdb2 pull request #2692
Opened 2021-02-01 16:04 UTC by nirbhayc

Following the general rule to allow all operations on existing tables with ulonglong fields even when forbid_ulonglong is set in the lrl, this PR fixes another bug where rollout of new shards failed for the time partitions that had ulonglong typed fields.

Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

2021-02-01 17:30 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/eea52695/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/398 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/eea52695/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/eea52695/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2692'>Resubmit</a></p>

2021-02-04 03:24 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2021-02-04 04:44 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/02a27d36/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/399 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>limitsortingtbl</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/02a27d36/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/02a27d36/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2692'>Resubmit</a></p>

2021-02-24 17:26 UTC, mponomar approved these changes

2021-02-24 17:31 UTC, merged