Better error messages for foreign key constraint violations
bloomberg/comdb2 pull request #2704
Opened 2021-02-08 18:00 UTC by riverszhang89

Reword foreign key constraint error messages to include foreign key details and cause of failure. 

For instance, the following error message

```
verify key constraint cannot resolve constraint table 't' index '0' key 'I' -> table 'u' index '0' 
```

would become

```
Transaction violates foreign key constraint u(i) -> t(i, j, k): key value is still referenced from child table
```

2021-02-08 19:27 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5ec164bd/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>2/398 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>backup_logfiles<br>sc_parallel_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5ec164bd/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5ec164bd/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2704'>Resubmit</a></p>

2021-02-16 18:32 UTC, riverszhang89 commented on db/constraints.c
> +                        const struct schema *fk, *pk;
Made a change per your suggestion. Thanks!

2021-02-16 18:50 UTC, nirbhayc approved these changes

2021-02-16 20:36 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/399 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>comdb2sys_pagesize_generated [setup failure]<br>sc_timepart<br>auth<br>stripe_order_inserts</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/6c2ca59b/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/6c2ca59b/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2704'>Resubmit</a></p>

2021-02-16 22:44 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/399 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart<br>stripe_order_inserts</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/6c2ca59b/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/6c2ca59b/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2704'>Resubmit</a></p>

2021-02-16 22:47 UTC, merged

2021-02-16 22:47 UTC, riverszhang89 commented
@nirbhayc @adizaimi Thank you for the review!