make sure we pick the next shard in sc if already created
bloomberg/comdb2 pull request #2707
Opened 2021-02-10 16:18 UTC by dorinhogea

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

There is a time window during partition in which we already have a new shard ready not rolled in.  Any schema change happening during this time will miss it.  This patch make sure the ready-to-rollin shard is also schema changed.

2021-02-10 17:41 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/b837e2fe/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/399 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>backup_logfiles</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/b837e2fe/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/b837e2fe/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2707'>Resubmit</a></p>

2021-02-10 18:46 UTC, adizaimi commented on tests/sc_race_timepart.test/runit
> +echo cdb2sql ${CDB2_OPTIONS} $dbname default "CREATE TIME PARTITION ON t as ${VIEW1} PERIOD 'daily' RETENTION 2 START '${starttime}'"
extra echo

2021-02-10 18:48 UTC, adizaimi approved these changes
looks good.

2021-02-11 14:00 UTC, merged

2021-02-11 14:00 UTC, dorinhogea commented
Thank you