UPSERT: Check for 'uniqnulls' flag in the index schema (upmerge from 7.0)
bloomberg/comdb2 pull request #2721
Opened 2021-02-18 21:46 UTC by nirbhayc

comdb2_is_idx_uniqnulls() wrongly checked it in the base table schema. This function is called by sqlite engine to check whether it should report a conflict for multiple NULLs for the current index.

Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

2021-02-18 23:23 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/399 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart<br>backup_logfiles<br>stripe_order_inserts</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/f3b829b4/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/f3b829b4/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2721'>Resubmit</a></p>

2021-02-19 20:50 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/399 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>comdb2sys_pagesize_generated [setup failure]<br>stripe_order_inserts</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/f3b829b4/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/f3b829b4/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2721'>Resubmit</a></p>

2021-02-22 15:00 UTC, mponomar approved these changes

2021-02-22 15:08 UTC, merged

2021-02-22 15:08 UTC, nirbhayc commented
Thank you Mike!