comdb2_files: A system table to allow making a copy of data directory (WIP)
bloomberg/comdb2 pull request #2726
Opened 2021-02-23 19:08 UTC by nirbhayc

An async replicant can use this system table to inherit the initial state.

Changes have been made so that comdb2 will automatically try to copy the contents of data directory of the source database if it finds 'replicate_from' in its lrl.

Credit: @mponomar

Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

2021-02-23 19:10 UTC, roborivers reviewed
Lint check:

```diff


@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ db/phys_rep.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2021-02-23 19:34 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/df6c3b07/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/df6c3b07/smoketest.log'>Error &#x26A0; </a>.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/df6c3b07/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/df6c3b07/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/df6c3b07/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2726'>Resubmit</a></p>

2021-02-23 21:39 UTC, roborivers reviewed
Lint check:

```diff


@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ db/phys_rep.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2021-02-23 22:03 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/3bd0746d/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/3bd0746d/smoketest.log'>Error &#x26A0; </a>.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/3bd0746d/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/3bd0746d/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2726'>Resubmit</a></p>

2021-02-24 13:29 UTC, roborivers reviewed
Lint check:

```diff


@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ db/phys_rep.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2021-02-24 14:01 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/7066ad5a/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/7066ad5a/smoketest.log'>Error &#x26A0; </a>.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/7066ad5a/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/7066ad5a/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2726'>Resubmit</a></p>

2021-02-24 17:32 UTC, mponomar commented
Quick thoughts - we rely on a couple of behaviors in comdb2ar (which are the reasons we don't use the system tar)

1. We need to pause log deletion while the copy is taking place because we may need lot entries to recover the copied files.
1. comdb2ar computes checksums to prevent torn page issues and retries on an checksum failures

The existing code will need to do something similar.  For (1) we can pause deletion for the duration of any queries that run against comdb2_files.  For (2) can can replicate comdb2ar's logic, (or move it into a library shared between comdb2 and comdb2ar).  A more correct option is to go through the db cache, but that'll be detrimental for performance.

2022-12-15 19:08 UTC, mponomar commented on db/comdb2.c
> +        int pre_process_physrep_options(const char *lrlname);
Put this prototype in a shared header somewhere?

2022-12-15 19:30 UTC, mponomar commented on sqlite/ext/comdb2/files.c
> +  if( idxNum & 1 ){
Constants for these would be easier to remember.

2023-04-28 18:14 UTC, closed without merging