Fix disable_tagged_api tunable
bloomberg/comdb2 pull request #2727
Opened 2021-02-24 20:45 UTC by nirbhayc

Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

2021-02-24 20:49 UTC, roborivers reviewed
Lint check:

```diff


@@ db/sltdbt.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2021-02-24 22:12 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/fdc2f1da/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/400 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>backup_logfiles</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/fdc2f1da/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/fdc2f1da/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2727'>Resubmit</a></p>

2021-02-25 02:28 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e2523504/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/400 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>backup_logfiles<br>sc_truncate</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e2523504/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e2523504/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2727'>Resubmit</a></p>

2021-05-03 19:50 UTC, riverszhang89 approved these changes

2021-05-03 19:51 UTC, merged