Only get tablelock once for repeated USEDB of same tbl
bloomberg/comdb2 pull request #2742
Opened 2021-03-09 19:43 UTC by adizaimi

Currently if there are several USEDB messages, we get tablelock
for every one of them. This change will not get tablelock for
subsequent USEDBs if we already got it once before.

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

2021-03-09 20:49 UTC, riverszhang89 commented
We already skip repeated USEDB's in [osq_send_usedb](https://github.com/bloomberg/comdb2/blob/master/db/osqlsqlthr.c#L1321-L1324). It seems unnecessary to perform the check on master node again.

2021-03-09 21:45 UTC, adizaimi commented
No, the usedbs in this case are indeed repeated in the following case:
begin
insert into t1
insert into t2
insert into t1
commit

2021-03-09 21:51 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e7c66edd/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/401 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill [core dumped]<br>simple_timepart_reptimeout_generated<br>simple_timepart</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e7c66edd/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e7c66edd/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2742'>Resubmit</a></p>

2021-03-11 14:33 UTC, akshatsikarwar commented
What is `reordering`?

Can you confirm `usedb` is cleared at the start of a new transaction?

2021-03-11 18:46 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/8a043bbc/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/401 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>simple_timepart_reptimeout_generated<br>simple_timepart<br>datetime</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/8a043bbc/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/8a043bbc/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2742'>Resubmit</a></p>

2021-03-12 18:52 UTC, akshatsikarwar commented
> We reorder osql operations

Is this enabled by default?

2021-03-12 23:29 UTC, adizaimi commented
Yes, it is enabled by default: `gbl_reorder_socksql_no_deadlock` (I should rename it :).

2021-03-15 13:10 UTC, akshatsikarwar approved these changes

2021-03-15 14:28 UTC, merged

2021-03-15 14:28 UTC, adizaimi commented
Thank you!