Return bdberror on failure to create temptable
bloomberg/comdb2 pull request #2749
Opened 2021-03-15 16:26 UTC by adizaimi

Return bdberror on failure to create temptable
also print error if failed to borrow from tmptable pool.

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

2021-03-15 17:20 UTC, riverszhang89 commented on bdb/temptable.c
> +            logmsg(LOGMSG_ERROR, "comdb2_objpool_borrow returns rc %d\n", rc);
Can be either `comdb2_objpool_forcedborrow` or `comdb2_objpool_borrow`. You may also want to include a `strerror()` here.

2021-03-15 17:50 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/401 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>simple_timepart_reptimeout_generated<br>sc_timepart_logicalsc_generated<br>simple_timepart<br>datetime</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/275119ea/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/275119ea/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2749'>Resubmit</a></p>

2021-03-15 22:01 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/401 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>simple_timepart_reptimeout_generated<br>sc_timepart_logicalsc_generated<br>sc_timepart<br>simple_timepart<br>datetime</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/255bb223/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/255bb223/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2749'>Resubmit</a></p>

2021-03-17 20:32 UTC, mistachkin approved these changes
Looks good.

2021-03-18 20:47 UTC, merged

2021-03-18 20:47 UTC, adizaimi commented
Thank you Joe!