Fix Number to Datetime conversion
bloomberg/comdb2 pull request #2753
Opened 2021-03-16 21:04 UTC by riverszhang89

Handle the decimal number of a negative number correctly, when counting from the Unix epoch.

2021-03-16 22:37 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/401 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>simple_timepart_reptimeout_generated<br>sc_timepart<br>simple_timepart<br>datetimeusec<br>datetime</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9c2f5d57/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9c2f5d57/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2753'>Resubmit</a></p>

2021-03-17 15:04 UTC, adizaimi commented on db/types.c
> +        dt->dttz_frac = (d - (long long)d) * 1E3;
since we already casted for the assignment in 13401, maybe change to:
  dt->dttz_frac = (d - dt->dttz_sec) * 1E3;

2021-03-18 19:43 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/401 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>simple_timepart_reptimeout_generated<br>simple_timepart<br>datetime<br>logfill</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/c27cab6d/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/c27cab6d/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2753'>Resubmit</a></p>

2021-03-24 17:48 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/c27cab6d/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>4/403 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>constraints_noreorder_generated<br>simple_timepart_reptimeout_generated<br>sc_timepart<br>simple_timepart</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/c27cab6d/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/c27cab6d/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2753'>Resubmit</a></p>

2021-04-16 17:10 UTC, adizaimi approved these changes
LGTM

2021-04-17 00:46 UTC, riverszhang89 commented
@adizaimi Thank you for the review!

2021-04-17 00:46 UTC, merged