remove low level timepart check that is not used
bloomberg/comdb2 pull request #2784
Opened 2021-04-08 18:19 UTC by dorinhogea

Code removed is in backout_schemas, and introduces a reverse ordering between the low level tag lock and the higher level views lock. Checked all callers of that function, and all pass down a tablename, not a partition name.   Safe to clean.

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

2021-04-08 19:45 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/403 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>comdb2sys_pagesize_generated [setup failure]<br>sc_timepart_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e2543cb3/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e2543cb3/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2784'>Resubmit</a></p>

2021-04-09 15:41 UTC, adizaimi approved these changes
Looks good.

2021-04-09 16:20 UTC, dorinhogea commented
Thanks Adi

2021-04-09 16:20 UTC, merged

2021-04-09 16:48 UTC, roborivers approved these changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e2543cb3/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e2543cb3/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2784'>Resubmit</a></p>