Fix copycomdb2 script to work even when lz4 is not installed
bloomberg/comdb2 pull request #2792
Opened 2021-04-14 16:26 UTC by adizaimi

While it is expected that servers will always have lz4 installed,
there may be cases where lz4 is unavailable in a source or destination machine,
and in that case copycomdb2 can simply use `cat` as the tool to read
data (in both source and destination)--this patch does just that.

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

2021-04-14 18:09 UTC, roborivers submitted a review, later dismissed
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/869f9cb3/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/869f9cb3/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2792'>Resubmit</a></p>

2021-04-14 19:04 UTC, riverszhang89 commented on db/copycomdb2
> +PREFIX=/opt/bb
Is this debug leftover?

2021-04-14 19:04 UTC, riverszhang89 commented on db/copycomdb2
> +set -x
This, too.

2021-04-15 18:25 UTC, adizaimi commented on db/copycomdb2
> +PREFIX=/opt/bb
Yes, thank you Rivers.

2021-04-15 18:27 UTC, adizaimi commented on db/copycomdb2
> +set -x
Thanks. Fixed : )

2021-04-15 18:44 UTC, riverszhang89 approved these changes

2021-04-15 20:09 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/403 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9862a783/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9862a783/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2792'>Resubmit</a></p>

2021-04-15 23:49 UTC, merged

2021-04-15 23:49 UTC, adizaimi commented
Thank you Rivers!