Dynamically allocating constraints
bloomberg/comdb2 pull request #2794
Opened 2021-04-15 18:19 UTC by mogarg

To help us review your pull request, please consider providing an overview of the following:
* What is the type of the change (bug fix, feature, documentation and etc.) ?
* What are the current behavior and expected behavior, if this is a bugfix ?
* What are the steps required to reproduce the bug, if this is a bugfix ?
* What is the current behavior and new behavior, if this is a feature change or enhancement ?
* [Optional] Why is the new behavior better than the current behavior, if this is a feature change ?

2021-04-15 19:48 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/8c3a9395/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/403 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>fkey_timepart [setup core dumped]<br>constraints_noreorder_generated [core dumped]<br>sc_constraints [core dumped]<br>sc_constraints_logicalsc_generated [core dumped]<br>constraints [core dumped]<br>ddl_no_csc2 [core dumped]<br>sc_timepart</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/8c3a9395/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/8c3a9395/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2794'>Resubmit</a></p>

2021-04-20 19:35 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/cc1889d4/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/403 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>fkey_timepart [setup core dumped]<br>constraints_noreorder_generated [core dumped]<br>constraints [core dumped]<br>sc_timepart_logicalsc_generated<br>logfill</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/cc1889d4/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/cc1889d4/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2794'>Resubmit</a></p>

2021-04-20 19:56 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/2fa9e5cf/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/403 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>sc_timepart<br>fkey_timepart</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/2fa9e5cf/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/2fa9e5cf/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2794'>Resubmit</a></p>

2021-04-20 21:30 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/044d8dbc/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/403 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>op_makerecord<br>fkey_timepart</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/044d8dbc/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/044d8dbc/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2794'>Resubmit</a></p>

2021-04-21 00:08 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ed8abfe0/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/403 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>constraints_noreorder_generated<br>sc_constraints<br>sc_constraints_logicalsc_generated<br>sc_blob_update_logicalsc_generated<br>sc_blob_update<br>constraints<br>fkey_timepart<br>ddl_no_csc2<br>logfill</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ed8abfe0/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ed8abfe0/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2794'>Resubmit</a></p>

2021-04-21 20:40 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5cc334e8/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/403 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart<br>op_makerecord<br>auth_queueodh_generated<br>fkey_timepart</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5cc334e8/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5cc334e8/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2794'>Resubmit</a></p>

2021-04-21 23:43 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9f78b722/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/402 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>comdb2sys_queueodh_generated<br>comdb2sys_pagesize_generated<br>comdb2sys</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9f78b722/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9f78b722/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2794'>Resubmit</a></p>

2021-04-22 01:22 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/402 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>op_makerecord</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/0497accd/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/0497accd/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2794'>Resubmit</a></p>

2021-04-22 20:02 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/402 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/3e42f439/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/3e42f439/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2794'>Resubmit</a></p>

2021-04-26 20:36 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/402 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/bafaef1c/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/bafaef1c/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2794'>Resubmit</a></p>

2021-04-27 15:15 UTC, mogarg commented on db/comdb2.c
> +                    tbl->constraints[ii].table[jj] = strndup(tblnm, MAXTABLELEN);
strdup is fine.

2021-04-27 15:21 UTC, mogarg commented on db/comdb2.c
> +    db->rev_constraints[idx] = NULL;
free this deleted constraint.

2021-04-27 15:23 UTC, mogarg commented on db/comdb2.c
> +    if (db->n_rev_constraints > 0 && db->n_rev_constraints <= db->cap_rev_constraints / 4) {
resizing is not super-important.

2021-04-27 15:28 UTC, mogarg commented on db/tag.c
> +    if (db->rev_constraints) {
check and see if we also want to free sub-fields.

2021-04-27 15:33 UTC, mogarg commented on schemachange/sc_fastinit_table.c
> +        cleanup_newdb(newdb);
test with truncate a table that has foreign key constraints.

2021-04-27 18:01 UTC, mogarg commented on db/comdb2.c
> +    if (db->n_rev_constraints > 0 && db->n_rev_constraints <= db->cap_rev_constraints / 4) {
Since, this is tested and working, I don't want to remove this retest. So, leaving this here for now.

2021-04-27 19:47 UTC, mogarg commented on db/tag.c
> +    if (db->rev_constraints) {
The `constraint_t *` pointers in `rev_constraints` contains pointers owned by the referring tables so no need to free here.

2021-04-27 21:31 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/404 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart<br>pmux_sqlite_memory_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/b96a8611/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/b96a8611/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2794'>Resubmit</a></p>

2021-04-27 22:55 UTC, roborivers approved these changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/b96a8611/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/b96a8611/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2794'>Resubmit</a></p>

2021-04-29 13:56 UTC, mponomar approved these changes
Went over this with Mohit yesterday, looks good!

2021-04-29 16:15 UTC, merged