Use thread manager to account for all running threads
bloomberg/comdb2 pull request #2801
Opened 2021-04-18 01:38 UTC by adizaimi

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

2021-04-18 03:13 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9eedc57a/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/403 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>serialstep [setup failure]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9eedc57a/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9eedc57a/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2801'>Resubmit</a></p>

2021-04-19 15:52 UTC, akshatsikarwar commented on net/akq.c
> -    while (1) {
This is wrong - nothing will ever resume akq after `start_threads` is called. We never want to stop processing replication net traffic - that is where subsequent start-thread will be received!
akq shutdown is performed by `stop_event_net`.

2021-04-19 20:03 UTC, akshatsikarwar approved these changes

2021-04-19 21:52 UTC, merged

2021-04-19 21:52 UTC, adizaimi commented
Thank you Akshat!