Perform 'legacy_schema' checks only on master node
bloomberg/comdb2 pull request #2813
Opened 2021-04-27 14:42 UTC by nirbhayc

This will prevent the replicant nodes from panicking in the unlikely event when they have legacy_schema turned ON and are processing newer csc2 constructs in the schema sent from master node that has this tunable turned OFF.

Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

2021-04-27 16:28 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/a7c2e545/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/a7c2e545/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/a7c2e545/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2813'>Resubmit</a></p>

2021-04-29 13:31 UTC, riverszhang89 commented on db/glue.c
> +    return (!thedb || thedb->master == gbl_myhostname) ? 1 : 0;
I don't think `thedb` can be null here. `return (thedb->master == gbl_myhostname);` should be sufficient.

2021-04-29 13:55 UTC, mponomar approved these changes

2021-04-29 14:55 UTC, riverszhang89 approved these changes

2021-04-29 16:46 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/754592cb/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/754592cb/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/754592cb/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2813'>Resubmit</a></p>

2021-04-29 19:05 UTC, merged