Allow unsigned int tunables to be assigned full range of values
bloomberg/comdb2 pull request #2814
Opened 2021-04-27 14:45 UTC by adizaimi

Currently setting an unsigned int tunable to values larger than LONG_MAX
results in failure. This change allows us to properly assign values
up to ULONG_MAX. We use strtoul() for all tunables that are NOT SIGNED,
and strtol() for those wich are SIGNED.

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

2021-04-27 16:38 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/f0796c93/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/f0796c93/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/f0796c93/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2814'>Resubmit</a></p>

2021-04-27 20:37 UTC, nirbhayc approved these changes
A suggestion inline, looks good otherwise.

2021-04-27 20:37 UTC, nirbhayc commented on db/db_tunables.c
> +    *num = strtoul(value, &endptr, 10);
We need to add a check for the parsed value just to be safe.
```
unsigned long n = strtoul(...);
// Note: the underlying storage is `int`
if (n > LONG_MAX) {          // on error strtoul() returns ULONG_MAX
    // error
} else {
    *num = (int)n;
}
```

2021-05-03 15:27 UTC, merged

2021-05-03 15:27 UTC, adizaimi commented
Thank you Nirbhay!