Eventlog: print number of writes and cascaded writes per transaction
bloomberg/comdb2 pull request #2817
Opened 2021-04-27 21:36 UTC by adizaimi

Print number of writes and cascaded writes for every transaction in eventlog
file so an entry will now have `nwrites` and `casc_nwrites` additional fields:

```
{
  "time": 1619552710156440,
  "type": "txn",
  "cnonce": "3766303130312d356163642d3535623334336166383230302d30306530636262646666393730663563",
  "id": "48f28bc5-1fbb-4605-9573-883026aee4bf",
  "host": "",
  "nwrites": 101,
  "casc_nwrites": 100,
  "perf": {
    "tottime": 5465,
    "processingtime": 5427,
    "qtime": 38
  }
}
```

Also, keep a counter of cascaded deletes and updates for a table and display
the delta in statreqs every minute:

```
04/27 15:46:01:   DIFF REQUEST STATS FOR TABLE 't2'
04/27 15:46:01:       OSQL_DELREC            200
04/27 15:46:01:       OSQL_UPDREC            200
04/27 15:46:01:       OSQL_UPDCOLS           200
04/27 15:46:01:       OSQL_DONE_SNAP         704
04/27 15:46:01:       OSQL_SCHEMACHANGE      1
04/27 15:46:01:       OSQL_INSERT            900
04/27 15:46:01:       OSQL_STARTGEN          704
04/27 15:46:01:       nsql                   910
04/27 15:46:01:       inserted rows          899
04/27 15:46:01:       updated rows           1196
04/27 15:46:01:       deleted rows           915
04/27 15:46:01:       cascaded upd/del rows 1713
```

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

To help us review your pull request, please consider providing an overview of the following:
* What is the type of the change (bug fix, feature, documentation and etc.) ?
* What are the current behavior and expected behavior, if this is a bugfix ?
* What are the steps required to reproduce the bug, if this is a bugfix ?
* What is the current behavior and new behavior, if this is a feature change or enhancement ?
* [Optional] Why is the new behavior better than the current behavior, if this is a feature change ?

2021-04-27 23:33 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9ab7c317/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>bplog_leaks_sockbplog_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9ab7c317/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9ab7c317/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2817'>Resubmit</a></p>

2021-04-28 14:50 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9ab7c317/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>sc_timepart</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9ab7c317/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9ab7c317/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2817'>Resubmit</a></p>

2021-04-28 16:48 UTC, riverszhang89 approved these changes

2021-04-29 18:21 UTC, merged

2021-04-29 18:21 UTC, adizaimi commented
Thank you Rivers!