Port max_query_fingerprints to tunables sub-system (cherry-picked from 7.0)
bloomberg/comdb2 pull request #2825
Opened 2021-05-03 20:54 UTC by nirbhayc

In the current implementation there is no cleaner way to check its current value.

$ comdb2sc.tsk testdb send max_query_fingerprints
Expected max query fingerprints, current 1000

Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

2021-05-03 20:55 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2021-05-03 22:23 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/284aec7b/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>pmux_sqlite_memory_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/284aec7b/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/284aec7b/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2825'>Resubmit</a></p>

2021-05-04 00:11 UTC, riverszhang89 approved these changes

2021-05-06 17:30 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/8df3de1b/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/8df3de1b/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/8df3de1b/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2825'>Resubmit</a></p>

2021-05-06 17:52 UTC, mponomar approved these changes

2021-05-06 18:20 UTC, merged