Reduce protobuf memory footprint
bloomberg/comdb2 pull request #2831
Opened 2021-05-05 19:37 UTC by riverszhang89

Currently row data is returned in a nested protobuf message, as below.

```
message CDB2_SQLRESPONSE {
    message Column {
        ...
    }
}
```

The patch, instead, returns row data directly under CDB2_SQLRESPONSE.

A nested message is more readable, but comes with an overhead: `protobuf_c_message_pack_to_buffer()` must first pack a nested message into main memory to get its serialized size. This means that for each column value that is being serialized, we end up using memory 2x of its size. We can avoid the overhead by collapsing the nested `CDB2_SQLRESPONSE.column` message into its parent message.

(DRQS 165828409)

2021-05-05 19:40 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

2021-05-05 21:19 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/62116dab/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart<br>op_makerecord</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/62116dab/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/62116dab/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2831'>Resubmit</a></p>

2021-05-06 13:05 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

2021-05-06 14:46 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/210db2fa/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/210db2fa/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2831'>Resubmit</a></p>

2021-05-06 17:07 UTC, mponomar submitted a review, later dismissed
Looks great.  Thanks Rivers.

2021-05-06 19:16 UTC, akshatsikarwar approved these changes

2021-05-06 20:12 UTC, riverszhang89 commented
Thank you for the review! @mponomar @akshatsikarwar

2021-05-06 20:12 UTC, merged