Add ability to abort transaction past a TTL limit
bloomberg/comdb2 pull request #2846
Opened 2021-05-13 02:19 UTC by adizaimi

Add ability to fail a transaction depending on time duration by
setting tunable max_time_per_txn_ms which controls the maximum point in time
we can perform an ins/upd/del on the master as part of a given txn.

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

2021-05-13 02:20 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2021-05-13 03:51 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4f4490fd/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4f4490fd/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4f4490fd/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2846'>Resubmit</a></p>

2021-07-15 14:45 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2021-07-15 15:30 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/407 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>timepart_changeretention</p>

2021-07-15 15:44 UTC, adizaimi commented
timepart_changeretention failure seems to happen in other branches, and must be unrelated to this PR.

2021-08-03 19:49 UTC, mponomar approved these changes
Looks good!

2021-08-03 20:27 UTC, merged

2021-08-03 20:27 UTC, adizaimi commented
Thank you Mike!