Tests: Exclude queuedb_rollover_extended_noroll1_generated from running
bloomberg/comdb2 pull request #2853
Opened 2021-05-18 18:58 UTC by adizaimi

Exclude from normal running of tests of
queuedb_rollover_extended_noroll1_generated.test which takes a very long time

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

2021-05-18 19:58 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>deadlock_load_noreorder_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/57be973a/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/57be973a/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2853'>Resubmit</a></p>

2021-05-19 02:16 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/a8936b50/smoketest.log'>Error &#x26A0; </a>.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/404 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>comdb2sys_pagesize_generated [setup failure]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/a8936b50/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/a8936b50/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2853'>Resubmit</a></p>

2021-05-20 19:54 UTC, riverszhang89 approved these changes

2021-05-20 20:08 UTC, merged

2021-05-20 20:08 UTC, adizaimi commented
Thank you Rivers!

2021-05-20 20:20 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/a8936b50/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/a8936b50/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/a8936b50/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2853'>Resubmit</a></p>