phys_rep.test: enable test after fixing issues
bloomberg/comdb2 pull request #2859
Opened 2021-05-22 21:54 UTC by adizaimi

* fix test to start physical replicant correctly
* wait for the leader's lsn before fetching the results
* use `send bdb cluster` to get last lsn
* apply_log() to update last lsn like in leader codepath
* downgrade not in background for now

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

2021-05-22 22:43 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/05b3f7fe/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>comdb2sys_pagesize_generated [setup failure]<br>sc_repeated_updates_logicalsc_generated<br>sc_repeated_updates</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/05b3f7fe/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/05b3f7fe/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2859'>Resubmit</a></p>

2021-05-24 04:01 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/19450dde/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/19450dde/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/19450dde/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2859'>Resubmit</a></p>

2021-06-02 19:32 UTC, mponomar approved these changes

2021-06-02 20:22 UTC, merged

2021-06-02 20:23 UTC, adizaimi commented
Thank you Mike!!