Fix selectv rcode
bloomberg/comdb2 pull request #2864
Opened 2021-05-29 22:27 UTC by riverszhang89

In socksql mode, if selectv-range-check is enabled, but osql-reordering is disabled, selectv transactions may receive errors out of order.

Consider the following example:

```SQL

TXN 1                                          | TXN 2
                                               |
SET VERIFYRETRY OFF                            |
BEGIN                                          |
SELECTV * FROM t WHERE id = 1 -- SELECTV       |
UPDATE t SET id = 2 WHERE id = 1 -- UPDREC     |
                                               | UPDATE t SET id = 3 WHERE id = 1
COMMIT                                         |
```

Without reordering, master processes the opcodes in the order in which they were received. A selectv range is sent to master at commit time. Therefore, TXN 1 will get a verify error (since UPDREC is received and processed before SELECTV), instead of a selectv-constraint error.

An easy way to address the issue is to disable selectv-range-check in socksql mode if osql-reordering isn't enabled.

2021-05-29 23:24 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/f78daa89/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/f78daa89/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/f78daa89/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/f78daa89/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2864'>Resubmit</a></p>

2021-06-29 18:00 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://roborivers.dev.bloomberg.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://roborivers.dev.bloomberg.com/tests/f78daa89/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://roborivers.dev.bloomberg.com/tests/f78daa89/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: Success &#10003;.</p><p><a href='http://roborivers.dev.bloomberg.com/tests/f78daa89/detail.txt'>Detail</a> | <a href='http://roborivers.dev.bloomberg.com/tests/f78daa89/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2864'>Resubmit</a></p>

2021-06-29 23:13 UTC, roborivers approved these changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e6523a18/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e6523a18/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2864'>Resubmit</a></p>

2021-06-30 00:46 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/407 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>auth_dba<br>sc_timepart</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e6523a18/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e6523a18/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2864'>Resubmit</a></p>

2021-06-30 14:55 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/407 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logdelete [setup failure]</p>

2022-11-08 21:40 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>1/407 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>upsert</p>

2022-11-09 14:19 UTC, riverszhang89 commented
Discussed this with Mark. It appears that the range-checking code always suffers this way, that a client may receive a verify-error instead of a constraints-error, and thus may wind up retrying a transaction that it should not retry. My fix isn't optimal, as it basically just disables the range-checking code. Mark has a better idea for this: on the replicant, if a update or a delete occurs within a select-range, we can light a flag on the osql-update or osql_delete record, which tells master to change rcode to constraints-error rather than verify-error.

2022-11-09 14:19 UTC, closed without merging