Make listen() backlog configurable
bloomberg/comdb2 pull request #2866
Opened 2021-06-01 19:29 UTC by mponomar

Starting enough connections against a single node can result in failure if we have more pending connections then the server's listen() backlog.  Make the backlog tunable.

2021-06-01 19:30 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2021-06-01 20:24 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/7fe2b443/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/7fe2b443/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>1/404 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>tunables</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/7fe2b443/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/7fe2b443/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2866'>Resubmit</a></p>

2021-06-01 21:46 UTC, nirbhayc submitted a review, later dismissed
A minor suggestion below.

2021-06-02 13:23 UTC, riverszhang89 approved these changes

2021-06-02 13:25 UTC, merged