bbcmake trunk
bloomberg/comdb2 pull request #2871
Opened 2021-06-07 18:24 UTC by akshatsikarwar

/silent

2021-06-07 19:17 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4e7978ce/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4e7978ce/smoketest.log'>Error &#x26A0; </a>.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4e7978ce/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>391/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>odh_blobs<br>sc_constraints_logicalsc_generated<br>scindex<br>scindex_logicalsc_generated<br>sc_constraints<br>sicomplex<br>sicountbug2<br>sirandtest<br>updater_latency<br>dohsql_leaks</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4e7978ce/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4e7978ce/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2871'>Resubmit</a></p>

2021-06-07 20:27 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/47996af1/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/47996af1/smoketest.log'>Error &#x26A0; </a>.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/47996af1/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>391/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_constraints_logicalsc_generated<br>sc_constraints<br>sicomplex<br>odh_blobs<br>scindex_logicalsc_generated<br>scindex<br>sicountbug2<br>updater_latency<br>dohsql_leaks<br>sirandtest</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/47996af1/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/47996af1/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2871'>Resubmit</a></p>

2021-06-07 22:29 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/3ccf32ef/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/3ccf32ef/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/3ccf32ef/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/3ccf32ef/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2871'>Resubmit</a></p>

2021-06-08 13:40 UTC, nirbhayc approved these changes

2021-06-08 13:49 UTC, merged