Fix SSL initialization error for OpenSSL versions below 1.1.0
bloomberg/comdb2 pull request #2872
Opened 2021-06-08 21:37 UTC by riverszhang89

OpenSSL versions older than 1.1.0 require an explicit initialization. The server's and client's ssl_init routines are consolidated into a single one, as part of bbcmake changes. As a result, the cdb2_ssl_init() call in util/rtcpu.c prevents ssl_bend_init() from explicitly initializing OpenSSL.

The patch fixes it by removing the cdb2_ssl_init() call in util/rtcpu.c.

2021-06-08 22:29 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>serialstep [setup failure]<br>timepart_auth</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/6f657e9c/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/6f657e9c/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2872'>Resubmit</a></p>

2021-06-09 03:49 UTC, akshatsikarwar commented
Shouldn't `ssl_bend_init` run first when server starts?

2021-06-09 14:05 UTC, riverszhang89 commented
Yeah you're right. I'll make ssl_bend_init run first.

2021-06-09 15:28 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sp_twofiles_generated<br>sc_swapfields_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9f7aa18d/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9f7aa18d/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2872'>Resubmit</a></p>

2021-06-09 17:31 UTC, akshatsikarwar approved these changes

2021-06-09 17:44 UTC, merged