Add test and fix bufferoverflow cases in cdb2api
bloomberg/comdb2 pull request #2918
Opened 2021-07-26 18:17 UTC by adizaimi

There are several instances of strcpy in cdb2api which will overflow buffer.
Added fix and tests which show the bug.

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

2021-07-26 18:20 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

2021-07-26 18:24 UTC, riverszhang89 approved these changes

2021-07-26 19:06 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>1/408 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>timepart_changeretention</p>

2021-07-28 18:45 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

2021-07-28 19:31 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>1/409 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>timepart_changeretention</p>

2021-07-29 17:17 UTC, merged

2021-07-29 17:17 UTC, adizaimi commented
Thank you Rivers!