Allow typecasting if forbid ulonglong is disabled
bloomberg/comdb2 pull request #2926
Opened 2021-08-04 15:17 UTC by mohitkhullar

handle a deprecated type

Signed-off-by: Mohit Khullar <mkhullar1@bloomberg.net>

2021-08-04 16:20 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/410 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>timepart_changeretention</p>

2021-08-04 16:25 UTC, aakash10292 submitted a review, later dismissed

2021-08-04 16:48 UTC, nirbhayc reviewed
It'll be good to have a test to cover this change. (https://github.com/bloomberg/comdb2/blob/master/tests/ulonglong.test/t00.sql)

2021-08-04 20:24 UTC, mohitkhullar commented
/runtests

2021-08-04 23:11 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/410 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>timepart_changeretention</p>

2021-08-04 23:19 UTC, nirbhayc submitted a review, later dismissed

2021-08-04 23:41 UTC, nirbhayc submitted a review, later dismissed

2021-08-05 00:40 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/410 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>tmptbl_deadlock_starve_generated [setup failure]<br>timepart_changeretention</p>

2021-08-05 03:01 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>1/410 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>timepart_changeretention</p>

2021-08-05 11:22 UTC, nirbhayc approved these changes

2021-08-05 13:29 UTC, mohitkhullar commented
Thanks

2021-08-05 13:29 UTC, merged