fix race between chunk transactions and schema changes (i.e. keep locks for follow-up chunks)
bloomberg/comdb2 pull request #2938
Opened 2021-08-30 21:41 UTC by dorinhogea

Currently we drop all the locks when a transaction is committed.  Therefore the second transaction chunk has no locks on used tables, and a race with a schema change on those tables has unfortunate consequences. 
For delicate reasons it is not possible to keep locks across chunks.  Solution is to reacquire locks when a new chunk is created.
NOTE: in order to make sure the table has not changed while the transaction lost the table locks, we need to cache their versions in sqlite (currently, only remote table versions are cached, but this patch adds the version for local tables as well).

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

2021-08-30 21:45 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2021-08-30 22:41 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/410 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>tunables</p>

2021-08-31 14:50 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2021-08-31 14:57 UTC, nirbhayc commented on db/sqlglue.c
> +                rc = SQLITE_ERROR;
rc = newlocks_rc?

2021-08-31 15:02 UTC, mponomar commented on db/sqlglue.c
> +            sleep(gbl_throttle_txn_chunks_sec);
Make this milliseconds?

2021-08-31 15:26 UTC, mponomar approved these changes

2021-08-31 15:36 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p>

2021-08-31 16:47 UTC, merged