Libevent fastsql
bloomberg/comdb2 pull request #2967
Opened 2021-09-29 13:48 UTC by akshatsikarwar

/plugin-branch libevent-fastsql

2021-09-29 13:48 UTC, akshatsikarwar commented
/silent

2021-09-29 14:35 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: Success &#10003;.</p>

2021-11-01 17:29 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/409 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>recover_ddlk_sp</p>

2021-11-08 14:38 UTC, riverszhang89 approved these changes

2021-11-08 15:22 UTC, merged