interm work
bloomberg/comdb2 pull request #3023
Opened 2021-11-03 20:34 UTC by dorinhogea

Partitioned table part 2:
Following the new concept that partitioning is a property of a table, we add the ability to partition an existing table by altering  its properties.
Currently supported partitioning is time based; syntax is:

"ALTER TABLE tablename PARTITIONED BY TIME PERIOD 'daily' RETENTION 2 START '2021-11-03T America/New_York'"

Because partitioning is a property no different than other schema constraints, we can mix operations like:

ALTER TABLE t add column b, partitioned by ...

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

2021-11-03 20:35 UTC, roborivers reviewed
Lint check:

```diff


@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
```

2021-11-03 21:45 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>sc_truncate_lockorder_generated</p>

2021-11-11 17:30 UTC, roborivers reviewed
Lint check:

```diff


@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
```

2021-11-11 18:32 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p>

2021-11-12 16:56 UTC, mponomar approved these changes
Went over earlier with Dorin, looks good.

2021-11-12 19:01 UTC, dorinhogea commented
Thank you Mike!

2021-11-12 19:01 UTC, merged