Make query fingerprint available to cdb2api events
bloomberg/comdb2 pull request #3026
Opened 2021-11-07 17:44 UTC by riverszhang89

This change makes it possible for an API event to retrieve a query fingerprint from the server.

2021-11-07 17:45 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

2021-11-07 18:37 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: Success &#10003;.</p>

2021-11-12 19:55 UTC, mponomar approved these changes

2021-11-15 20:44 UTC, mponomar approved these changes

2021-11-18 02:56 UTC, merged