Add all tables in query to event logging json, even if not used
bloomberg/comdb2 pull request #3031
Opened 2021-11-10 18:58 UTC by chands10

Currently only tables that are actually needed to execute a query are written to the events log, but this change makes it so that all tables referenced in a query are written to the events log.

2021-11-10 20:07 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/410 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>eventlog</p>

2021-11-10 21:38 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p>

2021-11-11 17:18 UTC, aakash10292 approved these changes
Looks good to me!

2021-11-11 18:43 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p>The first 10 failing tests are: <br>socksql_master_swings</p>

2021-11-11 19:21 UTC, aakash10292 approved these changes

2021-11-11 19:23 UTC, merged