sp: Non-fatal string conversion during emit
bloomberg/comdb2 pull request #3053
Opened 2021-12-01 23:08 UTC by akshatsikarwar

I'm guessing I missed adding this variant for strings, thinking
(incorrectly) that conversion to string cannot fail. This initial work
was done here: 3a57baab34c151c1674e3e75119ae0997fedb4f5

Signed-off-by: Akshat Sikarwar <asikarwar1@bloomberg.net>

2021-12-01 23:08 UTC, akshatsikarwar commented
/silent

2021-12-02 00:28 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/421 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_constraints<br>sc_resume_logicalsc_generated<br>sp_twofiles_generated<br>sp<br>sp_queueodh_generated<br>sp_snapshot_generated</p>

2021-12-02 15:33 UTC, riverszhang89 approved these changes

2021-12-02 15:46 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/421 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_constraints</p>

2021-12-02 16:01 UTC, merged