simplify the llog_scdone code
bloomberg/comdb2 pull request #3061
Opened 2021-12-14 05:45 UTC by dorinhogea

Currently we log scdone in various cases and the code path is overly complicated.  We (l)log scdone for things with names that are tables, and things with names that are not tables; also for things that we do not care to pass names (like user views).
A code that is simply (de)serializing 2 DBT structures could be simpler. 

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

2021-12-14 05:56 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Failed to compile.</p>

2021-12-14 16:06 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: Success &#10003;.</p><p>The first 10 failing tests are: <br>phys_rep</p>

2021-12-14 17:35 UTC, dorinhogea commented
/plugin-branch cleanup_llog_scdone_path

2021-12-14 18:27 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: Success &#10003;.</p>

2021-12-14 19:48 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/421 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated [core dumped]<br>reorder_inserts_noreorder_generated</p>

2021-12-15 16:14 UTC, mponomar approved these changes
Looks good Dorin.  One really minor suggestion: just pass the name in without the length and do strlen in the logging code - less stuff to pass around.

2021-12-15 16:20 UTC, dorinhogea commented
thank you Mike!
NOTE: tablename is not a c-string, that is why we pass the length as well

2021-12-15 16:21 UTC, merged