clean free and is_timepartition code paths
bloomberg/comdb2 pull request #3078
Opened 2022-01-10 18:07 UTC by dorinhogea

For partition free code path, remove unused return code.
For partition check, simplify locking by remembering the initial check in sqlite parser. 

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

2022-01-10 18:10 UTC, roborivers reviewed
Lint check:

```diff


@@ db/views.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2022-01-10 19:30 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>5/422 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate [core dumped]<br>phys_rep<br>upsert<br>reorder_inserts_noreorder_generated<br>selectv_rcode</p>

2022-01-11 16:16 UTC, roborivers reviewed
Lint check:

```diff


@@ db/views.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2022-01-11 17:07 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/422 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>reorder_inserts_noreorder_generated<br>sc_datacopy_logicalsc_generated</p>

2022-01-11 20:13 UTC, aakash10292 approved these changes
Looks Good. 
Very minor suggestion (nit-picking, really) for readability => in chkAndCopyTable definition, since 'is_partition' no longer is used as a flag to indicate if table is  time partition or not, maybe we can rename it to reflect what it actually represents now a.k.a the shard name.

2022-01-11 22:44 UTC, dorinhogea commented
Thanks for comment and rubber-stamp Aakash! I will rename it in the following PR, which I will push shortly! I have been splinting some parts of the bigger drop partition PR, mainly cleanup and fixes that I discovered while testing it.

2022-01-11 22:44 UTC, merged