fix versioning across shards
bloomberg/comdb2 pull request #3082
Opened 2022-01-12 00:31 UTC by dorinhogea

Bug discovered while testing drop partition feature.  Make sure the rollout does not artificially increase the table version number.  Only a partition alter would increase the shards version.

(Also rename argument is_partition per previous PR comment).

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

2022-01-12 01:25 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>1/422 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>reorder_inserts_noreorder_generated</p>

2022-01-12 15:35 UTC, dorinhogea commented
NOTE: whenever we drop and afterwards we add back a table using the same name, the schema version is increased (this allows a distributed schema detect cases when new table has same name but different schema).   Nevertheless, this happens normally during legacy rollout; in this case version should be preserved since schema does not change.  This PR fixes the problem.

2022-01-27 20:33 UTC, mponomar approved these changes

2022-01-27 21:26 UTC, chands10 approved these changes

2022-01-27 21:28 UTC, dorinhogea commented
Thank you Salil!

2022-01-27 21:28 UTC, merged