net: Schemachange rebuild performance
bloomberg/comdb2 pull request #3089
Opened 2022-01-14 16:18 UTC by akshatsikarwar

* rep_process_message, rep_verify_match can easily take > heartbeat
  timeout. Nothing is actually broken, but the writer will drop
  connection and lose everything buffered in the read, write queues.
  Change heartbeat_send to not drop connection. If things are not making
  it to the sibling, then corresponding reader will disconnect.

* Increase sc_logbytes_per_second (we can easily do 3 logs / sec) and
  I've observed up to 5 / sec on a 8 node cluster.

* Tweak rd/wr buffers.

* Tweak some logmsg trace

2022-01-14 16:18 UTC, akshatsikarwar commented
/silent

2022-01-14 17:09 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2022-01-18 17:49 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/421 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>reorder_inserts_noreorder_generated<br>selectv_rcode_disable_svonly_nop_generated<br>transchunk_manyins</p>

2022-01-19 16:23 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/421 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep<br>reorder_inserts_noreorder_generated<br>sc_datacopy_logicalsc_generated</p>

2022-01-20 20:45 UTC, mponomar approved these changes

2022-01-20 21:03 UTC, merged