Sending smartbeats for long running transactions
bloomberg/comdb2 pull request #3091
Opened 2022-01-18 21:46 UTC by riverszhang89

This is an addendum to #3081. The change allows hungserv to identify hung clients more accurately.

2022-01-18 23:17 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/421 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>comdb2sys_pagesize_generated [setup failure]<br>socksql_master_swings [core dumped]<br>sc_truncate [core dumped]<br>selectv_rcode_serialretry_generated<br>reorder_inserts_noreorder_generated</p>

2022-01-18 23:35 UTC, nirbhayc submitted a review, later dismissed
Could you please double-check if the crashes from the tests are unrelated? Good to go otherwise.

2022-01-18 23:35 UTC, nirbhayc commented on tests/tools/smartbeats.c
> +
Awesome test Rivers!

2022-01-19 16:28 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/421 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_constraints [core dumped]<br>selectv_rcode_serialize_reads_like_writes_generated [core dumped]<br>socksql_master_swings<br>sc_constraints<br>reorder_inserts_noreorder_generated<br>selectv_rcode_disable_svonly_nop_generated<br>selectv_rcode</p>

2022-03-09 16:24 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>reorder_inserts_noreorder_generated<br>lock_maxid</p>

2022-03-14 18:48 UTC, nirbhayc approved these changes

2022-03-14 18:50 UTC, riverszhang89 commented
@nirbhayc Thank you for the review!

2022-03-14 18:50 UTC, merged