"sql dump" will also dump parameter values
bloomberg/comdb2 pull request #3097
Opened 2022-01-19 21:03 UTC by mponomar

Signed-off-by: Mike Ponomarenko <mponomarenko@bloomberg.net>

To help us review your pull request, please consider providing an overview of the following:
* What is the type of the change (bug fix, feature, documentation and etc.) ?
* What are the current behavior and expected behavior, if this is a bugfix ?
* What are the steps required to reproduce the bug, if this is a bugfix ?
* What is the current behavior and new behavior, if this is a feature change or enhancement ?
* [Optional] Why is the new behavior better than the current behavior, if this is a feature change ?

2022-01-19 21:57 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/421 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated [core dumped]<br>phys_rep<br>reorder_inserts_noreorder_generated</p>

2022-01-19 23:59 UTC, riverszhang89 approved these changes

2022-01-20 14:35 UTC, akshatsikarwar commented on db/sqlglue.c
> +            int nparams = thd->clnt->plugin.param_count(thd->clnt);
https://github.com/bloomberg/comdb2/blob/447e94fccd003f6c791abdb7fc50a6a4944c1138/db/sql.h#L530

2022-01-20 14:37 UTC, akshatsikarwar commented on db/reqlog.c
> +    if (param_value(clnt, &p, n) != 0) {
Ah! so much nicer that `if (clnt->is_has_want_newsql) {} else {}`  (-:

2022-01-28 18:22 UTC, merged