trivial fix and cleanup in mixed sql tags case
bloomberg/comdb2 pull request #3099
Opened 2022-01-20 19:54 UTC by dorinhogea

Parent_trans and trans are flipped by mistake; only happens when sql and tags are mixed (case that used to happened in the wild with very old clients mainly).

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

2022-01-20 19:55 UTC, dorinhogea commented on db/toblock.c
> +                        javasp_trans_handle, iq, &trans, \
in case it is not clear, trans is first, parent_trans is second. That is the bug.

2022-01-20 21:04 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/421 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite<br>reorder_inserts_noreorder_generated<br>recover_ddlk_sp<br>selectv_rcode</p>

2022-01-25 15:51 UTC, mponomar approved these changes

2022-01-25 15:56 UTC, dorinhogea commented
Thanks Mike!

2022-01-25 15:56 UTC, merged