enable micro_commit only if rowlocks enabled
bloomberg/comdb2 pull request #3100
Opened 2022-01-20 20:52 UTC by dorinhogea

micro_commit enables per btree physical transactions;  it was not probably not meant to be enabled for logical transactions if rowlocks are not enabled.  Logical transactions are used for ddl, and code works because gbl_locks_check_waiters is set (which allows the physical transaction to become a child of the logical transaction).  Disabling gbl_locks_check_waiters is a timebomb (it will prevent making the physical txn a child of the logical txn, so the locks will be released early, which is probably not what we want in non-rowlocks schema change).
Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

2022-01-20 21:50 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/421 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated [core dumped]<br>phys_rep<br>reorder_inserts_noreorder_generated<br>sc_truncate_lockorder_generated</p>

2022-01-21 20:00 UTC, markhannum commented
This is obviously correct .. micro commit is meaningless outside of rowlocks.

2022-01-21 21:11 UTC, markhannum approved these changes
Good to merge!

2022-01-24 16:04 UTC, mponomar approved these changes

2022-01-24 16:04 UTC, dorinhogea commented
Thank you Mark! Also, thanks Rivers, Mike!

2022-01-24 16:04 UTC, merged