Fewer temptables for new snapshot
bloomberg/comdb2 pull request #3106
Opened 2022-01-27 06:15 UTC by riverszhang89

Mike's idea: do not keep temptables around for log files if we're holding them only for other replicants to recover.

(DRQS 168188318)

2022-01-27 06:20 UTC, roborivers reviewed
Lint check:

```diff


@@ bdb/bdb_osqltrn.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2022-01-27 07:23 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2022-01-27 16:58 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2022-01-27 18:25 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2022-01-28 20:03 UTC, mponomar approved these changes

2022-01-31 04:30 UTC, merged