cdb2api: Get hostname from a cached FD
bloomberg/comdb2 pull request #3128
Opened 2022-02-11 19:39 UTC by riverszhang89

A connetion obtained from the in-process cache or sockpool does not have host information.
The patch fixes it.

The patch also includes changes needed for distributed tracing, which is a separate pull request against bb-plugins.

(DRQS 168421725)

2022-02-11 19:39 UTC, riverszhang89 commented
/plugin-branch dtrace

2022-02-11 19:40 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

2022-04-04 19:16 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

2022-04-04 19:17 UTC, mponomar approved these changes

2022-04-04 20:42 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/425 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>morestripe [core dumped]<br>socksql_master_swings<br>sc_truncate<br>recover_ddlk_sp</p>

2022-04-06 15:06 UTC, merged