Ufid 7
bloomberg/comdb2 pull request #3138
Opened 2022-02-20 13:10 UTC by markhannum

Replace dbreg identifiers with ufid numbers in the log stream.  This fixes a bug where an addrem is applied to an incorrect b-tree- the 'sc_downgrade' test reproduces this.  sc_downgrade also reproduces a different bug in our 'purge-unused-files' logic.  I'll address this under a different PR.

I'm submitting a PR now with ufid_logging enabled to verify that things work correctly under robo-rivers.

2022-02-20 13:11 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
@@ sqlite/src/vdbeInt.h @@
+ If the order of members in struct Mem is changed, columnNullValue (defined in sqlite/vdbeapi.c) needs to be reordered accordingly.
@@ sqlite/src/vdbeaux.c @@
+ If a new fixed-length serial type is introduced, sqlite3IsFixedLengthSerialType (defined in sqlite/vdbeInt.h) needs to be changed accordingly.
@@ db/appsock_handler.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/handle_buf.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/fdb_bend.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/prefault_helper.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/sqlglue.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ schemachange/sc_global.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/walkback.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/rep/rep_record.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/btree/bt_rec.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/dbreg/dbreg_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ csc2/macc_so.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlinterfaces.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlcheckboard.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/dohsql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/eventlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/appsock_handler.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/trigger.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/fdb_boots.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_metrics.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_fingerprint.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlglue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ net/net.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ schemachange/sc_global.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2022-02-20 15:11 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>22/352 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>odh_blobs [core dumped]<br>dohsql_leaks [core dumped]<br>insert_lots_large_tran_generated [core dumped]<br>cldeadlock [core dumped]<br>unionpar_maxqueue [core dumped]<br>analyze [core dumped]<br>analyze_partial_index_off_generated [core dumped]<br>update_datetime [core dumped]<br>yast_stat4scan_generated [core dumped]<br>yast [core dumped]</p>

2022-03-02 21:06 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
@@ sqlite/src/vdbeInt.h @@
+ If the order of members in struct Mem is changed, columnNullValue (defined in sqlite/vdbeapi.c) needs to be reordered accordingly.
@@ sqlite/src/vdbeaux.c @@
+ If a new fixed-length serial type is introduced, sqlite3IsFixedLengthSerialType (defined in sqlite/vdbeInt.h) needs to be changed accordingly.
@@ db/appsock_handler.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/handle_buf.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/fdb_bend.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/prefault_helper.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/sqlglue.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ schemachange/sc_global.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/walkback.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/rep/rep_record.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/btree/bt_rec.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/dbreg/dbreg_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ csc2/macc_so.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlinterfaces.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlcheckboard.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/dohsql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/eventlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/appsock_handler.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/trigger.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/fdb_boots.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_metrics.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_fingerprint.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlglue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ net/net.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ schemachange/sc_global.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2022-03-02 21:32 UTC, markhannum commented
Running sc_downgrade in a loop on my own machines crashes once every 20 runs or so with this stack:

https://gist.github.com/markhannum/67535179711dd6b4eb2202288c80e72f

This isn't related to these changes- I will investigate under a different PR

2022-03-02 22:16 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/353 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_downgrade<br>updater_latency<br>ssl_comdb2ar</p>

2022-03-02 22:36 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
@@ sqlite/src/vdbeInt.h @@
+ If the order of members in struct Mem is changed, columnNullValue (defined in sqlite/vdbeapi.c) needs to be reordered accordingly.
@@ sqlite/src/vdbeaux.c @@
+ If a new fixed-length serial type is introduced, sqlite3IsFixedLengthSerialType (defined in sqlite/vdbeInt.h) needs to be changed accordingly.
@@ db/appsock_handler.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/handle_buf.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/fdb_bend.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/prefault_helper.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/sqlglue.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ schemachange/sc_global.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/walkback.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/rep/rep_record.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/btree/bt_rec.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/dbreg/dbreg_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ csc2/macc_so.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlinterfaces.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlcheckboard.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/dohsql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/eventlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/appsock_handler.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/trigger.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/fdb_boots.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_metrics.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_fingerprint.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlglue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ net/net.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ schemachange/sc_global.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2022-03-03 00:09 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>6/353 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_downgrade<br>selectv_rcode_force_commit_generated<br>sp<br>ssl_comdb2ar<br>sp_snapshot_generated<br>logfill</p>

2022-03-03 19:24 UTC, markhannum commented
All of the failing tests also fail under 7.0 branch - I will look at them under different PRs.

2022-03-04 12:06 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
@@ sqlite/src/vdbeInt.h @@
+ If the order of members in struct Mem is changed, columnNullValue (defined in sqlite/vdbeapi.c) needs to be reordered accordingly.
@@ sqlite/src/vdbeaux.c @@
+ If a new fixed-length serial type is introduced, sqlite3IsFixedLengthSerialType (defined in sqlite/vdbeInt.h) needs to be changed accordingly.
@@ db/appsock_handler.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/handle_buf.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/fdb_bend.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/prefault_helper.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/sqlglue.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ schemachange/sc_global.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/walkback.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/rep/rep_record.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/btree/bt_rec.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/dbreg/dbreg_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ csc2/macc_so.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlinterfaces.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlcheckboard.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/dohsql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/eventlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/appsock_handler.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/trigger.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/fdb_boots.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_metrics.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_fingerprint.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlglue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ net/net.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ schemachange/sc_global.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2022-03-04 12:52 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/353 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>updater_latency<br>ssl_comdb2ar</p>

2022-03-07 15:02 UTC, markhannum commented
There are strange deadlocks in the sp test when ufid_logging is enabled.  I can't merge this until I understand what's happening.

2022-03-09 14:21 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
@@ sqlite/src/vdbeInt.h @@
+ If the order of members in struct Mem is changed, columnNullValue (defined in sqlite/vdbeapi.c) needs to be reordered accordingly.
@@ sqlite/src/vdbeaux.c @@
+ If a new fixed-length serial type is introduced, sqlite3IsFixedLengthSerialType (defined in sqlite/vdbeInt.h) needs to be changed accordingly.
@@ db/appsock_handler.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/handle_buf.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/fdb_bend.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/prefault_helper.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/sqlglue.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ schemachange/sc_global.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/walkback.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/rep/rep_record.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/btree/bt_rec.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/dbreg/dbreg_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ csc2/macc_so.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlinterfaces.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlcheckboard.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/dohsql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/eventlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/appsock_handler.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/trigger.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/fdb_boots.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_metrics.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_fingerprint.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlglue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ net/net.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ schemachange/sc_global.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2022-03-09 15:19 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>18/354 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_constraints [core dumped]<br>sc_constraints_logicalsc_generated [core dumped]<br>sc_inserts_logicalsc_generated [core dumped]<br>sc_inserts_deletes [core dumped]<br>sc_inserts_deletes_partial_index_off_generated [core dumped]<br>sc_inserts [core dumped]<br>sc_repeated_updates [core dumped]<br>sc_addfield_logicalsc_generated [core dumped]<br>sc_rebuilds_logicalsc_generated [core dumped]<br>sc_rebuilds [core dumped]</p>

2022-03-09 16:01 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
@@ sqlite/src/vdbeInt.h @@
+ If the order of members in struct Mem is changed, columnNullValue (defined in sqlite/vdbeapi.c) needs to be reordered accordingly.
@@ sqlite/src/vdbeaux.c @@
+ If a new fixed-length serial type is introduced, sqlite3IsFixedLengthSerialType (defined in sqlite/vdbeInt.h) needs to be changed accordingly.
@@ db/appsock_handler.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/handle_buf.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/fdb_bend.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/prefault_helper.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/sqlglue.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ schemachange/sc_global.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/walkback.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/rep/rep_record.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/btree/bt_rec.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/dbreg/dbreg_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ csc2/macc_so.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlinterfaces.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlcheckboard.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/dohsql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/eventlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/appsock_handler.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/trigger.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/fdb_boots.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_metrics.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_fingerprint.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlglue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ net/net.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ schemachange/sc_global.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2022-03-09 16:47 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>5/354 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>updater_latency<br>sc_timepart_logicalsc_generated<br>selectv_rcode<br>ssl_comdb2ar<br>recover_ddlk_sp</p>

2022-03-09 19:41 UTC, markhannum commented
The failures aren't related to the changes:
updater_latency : cycle-starved vm's (suspicious time-gap in the logs for all 3 machines at failure)
sc_timepart_logicalsc_generated : new master completed the sc, (but later because CONVERTSLEEP 10)
selectv_rcode : SSL Error / dropped connection- I am trying to reproduce this, but it's not ufid_log related
ssl_comdb2ar : server.key exists but has incorrect permissions- probably a umask issue
recover_ddlk_sp: incorrect number of table-locks exists after calling recover-deadlock from an sp- I am trying to reproduce this, but this isn't related to this code

2022-03-09 20:06 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
@@ sqlite/src/vdbeInt.h @@
+ If the order of members in struct Mem is changed, columnNullValue (defined in sqlite/vdbeapi.c) needs to be reordered accordingly.
@@ sqlite/src/vdbeaux.c @@
+ If a new fixed-length serial type is introduced, sqlite3IsFixedLengthSerialType (defined in sqlite/vdbeInt.h) needs to be changed accordingly.
@@ db/appsock_handler.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/handle_buf.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/fdb_bend.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/prefault_helper.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/sqlglue.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ schemachange/sc_global.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/walkback.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/rep/rep_record.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/btree/bt_rec.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/dbreg/dbreg_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ csc2/macc_so.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlinterfaces.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlcheckboard.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/dohsql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/eventlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/appsock_handler.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/trigger.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/fdb_boots.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_metrics.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_fingerprint.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlglue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ net/net.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ schemachange/sc_global.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2022-03-09 20:52 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/354 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>updater_latency<br>ssl_comdb2ar</p>

2022-03-10 23:16 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
@@ sqlite/src/vdbeInt.h @@
+ If the order of members in struct Mem is changed, columnNullValue (defined in sqlite/vdbeapi.c) needs to be reordered accordingly.
@@ sqlite/src/vdbeaux.c @@
+ If a new fixed-length serial type is introduced, sqlite3IsFixedLengthSerialType (defined in sqlite/vdbeInt.h) needs to be changed accordingly.
@@ db/appsock_handler.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/handle_buf.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/fdb_bend.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/prefault_helper.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/sqlglue.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ schemachange/sc_global.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/walkback.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/rep/rep_record.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/btree/bt_rec.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/dbreg/dbreg_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ csc2/macc_so.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlinterfaces.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlcheckboard.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/dohsql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/eventlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/appsock_handler.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/trigger.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/fdb_boots.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_metrics.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_fingerprint.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlglue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ net/net.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ schemachange/sc_global.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2022-03-11 00:29 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>7/354 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>updater_latency<br>selectv_rcode_disable_svonly_nop_generated<br>sp<br>ssl_comdb2ar<br>recover_ddlk_sp<br>sp_snapshot_generated<br>logfill</p>

2022-03-11 13:01 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
@@ sqlite/src/vdbeInt.h @@
+ If the order of members in struct Mem is changed, columnNullValue (defined in sqlite/vdbeapi.c) needs to be reordered accordingly.
@@ sqlite/src/vdbeaux.c @@
+ If a new fixed-length serial type is introduced, sqlite3IsFixedLengthSerialType (defined in sqlite/vdbeInt.h) needs to be changed accordingly.
@@ db/appsock_handler.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/handle_buf.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/fdb_bend.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/prefault_helper.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/sqlglue.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ schemachange/sc_global.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/walkback.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/rep/rep_record.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/btree/bt_rec.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/dbreg/dbreg_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ csc2/macc_so.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlinterfaces.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlcheckboard.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/dohsql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/eventlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/appsock_handler.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/trigger.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/fdb_boots.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_metrics.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_fingerprint.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlglue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ net/net.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ schemachange/sc_global.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2022-03-11 14:36 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
@@ sqlite/src/vdbeInt.h @@
+ If the order of members in struct Mem is changed, columnNullValue (defined in sqlite/vdbeapi.c) needs to be reordered accordingly.
@@ sqlite/src/vdbeaux.c @@
+ If a new fixed-length serial type is introduced, sqlite3IsFixedLengthSerialType (defined in sqlite/vdbeInt.h) needs to be changed accordingly.
@@ db/appsock_handler.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/handle_buf.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/fdb_bend.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/prefault_helper.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/sqlglue.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ schemachange/sc_global.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/walkback.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/rep/rep_record.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/btree/bt_rec.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/dbreg/dbreg_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ csc2/macc_so.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlinterfaces.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlcheckboard.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/dohsql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/eventlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/appsock_handler.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/trigger.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/fdb_boots.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_metrics.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_fingerprint.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlglue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ net/net.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ schemachange/sc_global.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2022-03-11 15:24 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>4/354 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>selectv_rcode<br>ssl_comdb2ar<br>recover_ddlk_sp<br>sp_snapshot_generated</p>

2022-03-14 14:21 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
@@ sqlite/src/vdbeInt.h @@
+ If the order of members in struct Mem is changed, columnNullValue (defined in sqlite/vdbeapi.c) needs to be reordered accordingly.
@@ sqlite/src/vdbeaux.c @@
+ If a new fixed-length serial type is introduced, sqlite3IsFixedLengthSerialType (defined in sqlite/vdbeInt.h) needs to be changed accordingly.
@@ db/appsock_handler.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/handle_buf.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/fdb_bend.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/prefault_helper.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/sqlglue.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ schemachange/sc_global.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/walkback.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/rep/rep_record.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/btree/bt_rec.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/dbreg/dbreg_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ csc2/macc_so.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlinterfaces.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlcheckboard.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/dohsql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/eventlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/appsock_handler.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/trigger.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/fdb_boots.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_metrics.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_fingerprint.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlglue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ net/net.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ schemachange/sc_global.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2022-03-14 15:13 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>6/354 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>schemalk_logicalsc_generated [core dumped]<br>updater_latency<br>selectv_rcode<br>ssl_comdb2ar<br>recover_ddlk_sp<br>sp_snapshot_generated</p>

2022-03-17 16:45 UTC, closed without merging