do not leak array of pointers when transferring table info
bloomberg/comdb2 pull request #3144
Opened 2022-02-23 19:53 UTC by dorinhogea

https://github.com/bloomberg/comdb2/pull/3142 for master

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

2022-02-23 20:10 UTC, roborivers reviewed
Lint check:

```diff


@@ sqlite/src/vdbeaux.c @@
+ If a new fixed-length serial type is introduced, sqlite3IsFixedLengthSerialType (defined in sqlite/vdbeInt.h) needs to be changed accordingly.
```

2022-02-23 20:47 UTC, mponomar approved these changes

2022-02-23 23:32 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated [core dumped]<br>morestripe [core dumped]<br>upsert<br>reorder_inserts_noreorder_generated<br>sc_truncate_lockorder_generated<br>lock_maxid</p>

2022-02-24 00:16 UTC, merged

2022-02-24 00:16 UTC, dorinhogea commented
Thank you Mike!