Add foreign db force to comdb3db tunable
bloomberg/comdb2 pull request #3145
Opened 2022-02-23 21:43 UTC by mogarg

2022-02-23 21:45 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2022-02-24 00:46 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated [core dumped]<br>socksql_master_swings<br>upsert<br>reorder_inserts_noreorder_generated<br>lock_maxid</p>

2022-02-24 15:56 UTC, mponomar approved these changes

2022-02-24 16:04 UTC, mponomar approved these changes

2022-02-24 16:05 UTC, merged