do not use a permanent field for a temp action, use an argument
bloomberg/comdb2 pull request #3147
Opened 2022-02-24 17:21 UTC by dorinhogea

We do not need a permanent struct member to temporary do an action, just pass an argument.  (Small update towards macc code encapsulation).

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

2022-02-24 18:15 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>truncatesc [core dumped]<br>upsert<br>reorder_inserts_noreorder_generated<br>lock_maxid</p>

2022-03-03 15:04 UTC, mponomar submitted a review, later dismissed

2022-03-03 16:19 UTC, mponomar approved these changes

2022-03-03 16:21 UTC, dorinhogea commented
thank you Mike, again!

2022-03-03 16:21 UTC, merged