do not assume there is a sc running when failing cmacc parsing
bloomberg/comdb2 pull request #3167
Opened 2022-03-10 16:11 UTC by dorinhogea

Per title, cmacc parsing of a csc2 file assumes there is a schema change running if an error happens (i.e. db->iq && db->iq->sc are populated).
The code runs also when there is no schema change.  Changing some db settings (like ulonglong permission) can generate an error while parsing a previously accepted csc2 and crash the server.
The fix removes the assumption there is a sc running if csc2 fails to parse; the parser caller, who knows if there is an sc or not, will handle the error message.

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

2022-03-10 16:43 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2022-03-11 16:09 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2022-03-11 19:29 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>selectv_rcode<br>reorder_inserts_noreorder_generated</p>

2022-03-11 20:10 UTC, mponomar approved these changes

2022-03-11 20:25 UTC, dorinhogea commented
thank you Mike!

2022-03-11 20:34 UTC, merged