Port forbid_remote_admin to evbuffer codepath
bloomberg/comdb2 pull request #3168
Opened 2022-03-10 22:11 UTC by markhannum

The forbid_remote_admin tunable had no effect for databases using evbuffer net code.  This preserves the tunable's behavior.

2022-03-10 23:04 UTC, akshatsikarwar commented on plugins/newsql/newsql_evbuffer.c
> +int allow_admin(int local)
make it `static`?

2022-03-10 23:05 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite<br>reorder_inserts_noreorder_generated</p>

2022-03-11 00:59 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>timepart_trunc<br>reorder_inserts_noreorder_generated<br>basic_nolibevent_generated</p>

2022-03-11 15:20 UTC, akshatsikarwar approved these changes

2022-03-11 15:45 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>4/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>morestripe [core dumped]<br>sc_truncate<br>phys_rep<br>reorder_inserts_noreorder_generated</p>

2022-03-11 19:32 UTC, merged