encapsulate rest of cmacc csc2 code
bloomberg/comdb2 pull request #3195
Opened 2022-03-21 22:01 UTC by dorinhogea

Last phase of cmacc encapsulation.  
All code that uses cmacc/yacc library is in macc_glue.c, which is accessed by either create_new_dbtable() or populate_db_with_alt_schema() api.

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

2022-03-21 23:09 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>402/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sirace [setup failure]<br>socksql_master_swings [setup failure]<br>sicomplex [setup failure]<br>serial_randtest2 [setup failure]<br>sirandtest [setup failure]<br>sicountbug [setup failure]<br>sicountbug2 [setup failure]<br>ixentry_order [setup failure]<br>timepart_retention1 [setup failure]<br>simple_timepart_reptimeout_generated [setup failure]</p>

2022-03-22 06:24 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>yast<br>ulonglong<br>recover_ddlk_sp</p>

2022-03-22 18:20 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>yast<br>basic_nolibevent_generated</p>

2022-03-23 12:21 UTC, mponomar approved these changes

2022-03-23 17:57 UTC, dorinhogea commented
Thank you Mike!

2022-03-23 17:57 UTC, merged