Fixing a minor memory leak in fileid hash
bloomberg/comdb2 pull request #3206
Opened 2022-03-25 21:02 UTC by riverszhang89

A DB's fileid hash entry needs to be freed in __db_refresh(), in case the DB's DBENV is never refreshed.

2022-03-25 23:26 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>socksql_master_swings<br>yast</p>

2022-03-28 15:11 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>comdb2sys_pagesize_generated [setup failure]<br>socksql_master_swings<br>yast<br>reorder_inserts_noreorder_generated</p>

2022-04-05 09:08 UTC, markhannum approved these changes
TY for fixing my bug Rivers!  Good to merge

2022-04-05 12:54 UTC, riverszhang89 commented
@markhannum Thank you Mark!

2022-04-05 12:54 UTC, merged