Allow local rep for tables with expression index
bloomberg/comdb2 pull request #3209
Opened 2022-03-29 15:26 UTC by mohitkhullar

Signed-off-by: mohitkhullar <mkhullar1@bloomberg.net>

2022-03-29 16:51 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings</p>

2022-04-04 19:39 UTC, mohitkhullar commented
Only create expression indexes at the start, leave rest for later

2022-04-05 07:14 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>110/425 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>scindex [core dumped]<br>sc_constraints_logicalsc_generated [core dumped]<br>sc_constraints [core dumped]<br>yast [core dumped]<br>sp_snapshot_generated [core dumped]<br>sc_parallel_logicalsc_generated [core dumped]<br>upsert [core dumped]<br>sc_truncate<br>phys_rep<br>socksql_master_swings</p>

2022-04-05 19:43 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>240/425 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>scindex [core dumped]<br>scindex_logicalsc_generated [core dumped]<br>sc_constraints [core dumped]<br>sc_constraints_logicalsc_generated [core dumped]<br>sc_truncate [core dumped]<br>yast [core dumped]<br>sp_snapshot_generated [core dumped]<br>sc_parallel [core dumped]<br>socksql_master_swings<br>scindex</p>

2022-04-06 17:30 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/429 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>socksql_master_swings<br>sp_snapshot_generated</p>

2022-04-08 14:31 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2026-06-04 13:21 UTC, closed without merging