do not continue search on corrupted btree pages
bloomberg/comdb2 pull request #3212
Opened 2022-03-30 17:12 UTC by dorinhogea

Adding https://github.com/bloomberg/comdb2/pull/3211 to master as well.  See previous for explanations.

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

2022-03-30 19:40 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>374/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>cldeadlock [core dumped]<br>truncatesc_offline_generated [core dumped]<br>truncatesc [core dumped]<br>sc_inserts_deletes_logicalsc_generated [core dumped]<br>sc_inserts_deletes [core dumped]<br>sc_inserts_deletes_partial_index_off_generated [core dumped]<br>sc_drop [core dumped]<br>random_osql_replay [core dumped]<br>updcolsbug [core dumped]<br>yast [core dumped]</p>

2022-03-31 16:36 UTC, mponomar approved these changes

2022-05-02 12:08 UTC, mponomar approved these changes

2022-05-02 12:09 UTC, dorinhogea commented
Thank you Mike!

2022-05-02 12:09 UTC, merged

2022-05-02 12:21 UTC, mponomar commented
/runtests