New SC fix for conflicts which can occur in the logical redo thread
bloomberg/comdb2 pull request #3219
Opened 2022-04-04 14:54 UTC by markhannum

Signed-off-by: Mark Hannum <mhannum72@gmail.com>

We discovered cases where the newsc logical redo thread can experience constraint violations against records which never co-existed in the original table.  I've added a test, sc_redo_logicalsc_generated, which reproduces this case.  See tests/sc_redo.test/README for a detailed description of the case that this PR addresses.

This is still a WIP- I'm putting this in a little early to see how it fares under RR.

2022-04-04 14:55 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
@@ sqlite/src/vdbeInt.h @@
+ If the order of members in struct Mem is changed, columnNullValue (defined in sqlite/vdbeapi.c) needs to be reordered accordingly.
@@ sqlite/src/vdbeaux.c @@
+ If a new fixed-length serial type is introduced, sqlite3IsFixedLengthSerialType (defined in sqlite/vdbeInt.h) needs to be changed accordingly.
@@ db/appsock_handler.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/handle_buf.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/fdb_bend.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/prefault_helper.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/sqlglue.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ schemachange/sc_global.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ schemachange/sc_records.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/walkback.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/rep/rep_record.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/btree/bt_rec.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ csc2/macc_so.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlinterfaces.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlcheckboard.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/dohsql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/eventlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/appsock_handler.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/trigger.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/fdb_boots.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_metrics.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_fingerprint.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlglue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ net/net.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ schemachange/sc_global.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ util/walkback.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
@@ util/walkback.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2022-04-04 16:14 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/355 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_blob_update_logicalsc_generated [core dumped]</p>

2022-04-08 22:01 UTC, markhannum commented
This is ready for review

2022-04-11 13:16 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
@@ sqlite/src/vdbeInt.h @@
+ If the order of members in struct Mem is changed, columnNullValue (defined in sqlite/vdbeapi.c) needs to be reordered accordingly.
@@ sqlite/src/vdbeaux.c @@
+ If a new fixed-length serial type is introduced, sqlite3IsFixedLengthSerialType (defined in sqlite/vdbeInt.h) needs to be changed accordingly.
@@ db/appsock_handler.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/handle_buf.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/fdb_bend.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/prefault_helper.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/sqlglue.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ schemachange/sc_global.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ schemachange/sc_records.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/walkback.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/rep/rep_record.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/btree/bt_rec.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/dbreg/dbreg_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ csc2/macc_so.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlinterfaces.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlcheckboard.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/dohsql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/eventlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/appsock_handler.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/trigger.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/fdb_boots.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_metrics.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_fingerprint.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/machclass.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlglue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ net/net.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ schemachange/sc_global.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ util/walkback.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
@@ util/walkback.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2022-04-11 14:22 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/357 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>systbl_proc_leak<br>recover_ddlk_sp<br>logfill</p>

2022-04-12 15:41 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
@@ sqlite/src/vdbeInt.h @@
+ If the order of members in struct Mem is changed, columnNullValue (defined in sqlite/vdbeapi.c) needs to be reordered accordingly.
@@ sqlite/src/vdbeaux.c @@
+ If a new fixed-length serial type is introduced, sqlite3IsFixedLengthSerialType (defined in sqlite/vdbeInt.h) needs to be changed accordingly.
@@ db/appsock_handler.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/handle_buf.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/fdb_bend.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/prefault_helper.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/sqlglue.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ schemachange/sc_global.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ schemachange/sc_records.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/walkback.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/rep/rep_record.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/btree/bt_rec.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/dbreg/dbreg_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ csc2/macc_so.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlinterfaces.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlcheckboard.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/dohsql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/eventlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/appsock_handler.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/trigger.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/fdb_boots.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_metrics.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_fingerprint.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/machclass.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlglue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ net/net.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ schemachange/sc_global.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ util/walkback.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
@@ util/walkback.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2022-06-28 18:36 UTC, riverszhang89 commented on schemachange/sc_records.c
> +static void getcore()
This is unused.

2022-06-30 22:10 UTC, markhannum commented on bdb/tran.c
> +void bdb_set_tran_verify_updateid(tran_type *tran)
Fixes a bug: if redo-update fails on a verify-error, the code always calls del_new_record on the old genid.  If you don't verify the updateid from ll_dta_del the code will delete the non-matching genid (which just failed with a verify error).

2022-06-30 22:11 UTC, markhannum commented on schemachange/sc_records.c
> +                    logmsg(LOGMSG_USER, "%s %u nretries>500?\n", __func__, __LINE__);
yes - removed - thank you

2022-06-30 22:11 UTC, markhannum commented on bdb/llmeta.c
> +int bdb_newsc_get_redo_lsn(tran_type *t, const char *tablename, uint64_t genid,
Not used - I've deleted it.

2022-06-30 22:12 UTC, markhannum commented on bdb/llmeta.c
> +static int kv_del_all_partial(tran_type *tran, void *k, size_t klen, int *bdberr)
not used - I've deleted it

2022-06-30 22:12 UTC, markhannum commented on schemachange/sc_records.c
> +static void getcore()
was for debugging - I've deleted it

2022-07-01 12:32 UTC, riverszhang89 approved these changes
Good to merge! Thank you!

2022-07-01 20:27 UTC, merged