Disable rcache by default
bloomberg/comdb2 pull request #3235
Opened 2022-04-21 17:20 UTC by nirbhayc

Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

2022-04-21 17:35 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2022-04-21 20:07 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/430 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>recover_ddlk_sp</p>

2022-04-22 10:37 UTC, aakash10292 approved these changes
good to merge

2022-04-28 16:09 UTC, mponomar commented on db/db_tunables.h
> +REGISTER_TUNABLE("rcache", "Keep a lookaside cache of root pages for B-trees. (Default: on)",
Default: off?

2022-05-04 19:41 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2022-05-04 20:49 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/429 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>lostwrite</p>

2022-05-06 13:47 UTC, akshatsikarwar commented
Disabled by a prior PR

2022-05-06 13:47 UTC, closed without merging