comdb2_transaction_logs: Incorrect log stream in blocking mode
bloomberg/comdb2 pull request #3240
Opened 2022-04-29 15:03 UTC by nirbhayc

While reading from this virtual table in blocking-mode some logs
could erroneously get skipped due to an incorrect logic.

Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

2022-04-29 16:16 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2022-05-06 01:21 UTC, mponomar approved these changes

2022-05-06 01:40 UTC, markhannum approved these changes
Great catch .. good to merge!

2022-05-06 13:34 UTC, nirbhayc commented
/runtests

2022-05-09 16:01 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>6/430 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>updater_latency<br>sp_twofiles_generated<br>sp_snapshot_generated<br>sp_queueodh_generated<br>sp</p>

2022-05-09 16:33 UTC, merged