Replay errors for hint queries
bloomberg/comdb2 pull request #3263
Opened 2022-05-17 18:15 UTC by mohitkhullar

Signed-off-by: mohitkhullar <mkhullar1@bloomberg.net>

unlike R6, in R7 we add statement in history in run_stmt https://github.com/bloomberg/comdb2/blob/master/db/sqlinterfaces.c#L3872
however we error back before that in prepare_stmt error
https://github.com/bloomberg/comdb2/blob/master/db/sqlinterfaces.c#L3863

2022-05-17 18:20 UTC, mohitkhullar commented
this is when we add the query in run_stmt https://github.com/bloomberg/comdb2/blob/master/db/sqlinterfaces.c#L3631

2022-05-17 18:26 UTC, riverszhang89 commented
🤯

2022-05-17 19:18 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/430 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sql_datetime_interval_arithmetic_leak [core dumped]<br>socksql_master_swings<br>sc_truncate<br>sp_twofiles_generated<br>sp_snapshot_generated<br>sp_queueodh_generated<br>sp</p>

2022-05-17 20:42 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>9/430 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>comdb2sys_pagesize_generated [setup failure]<br>sc_truncate<br>socksql_master_swings<br>phys_rep<br>sp_twofiles_generated<br>sp_snapshot_generated<br>sp_queueodh_generated<br>sp<br>selectv_rcode_disable_svonly_nop_generated</p>

2022-05-18 16:06 UTC, markhannum approved these changes
Good to merge .. awesome find!

2022-05-19 16:01 UTC, mohitkhullar commented
Thanks

2022-05-19 16:01 UTC, merged