SSL metrics
bloomberg/comdb2 pull request #3277
Opened 2022-05-25 19:59 UTC by riverszhang89

The patch keeps track of numbers of SSL full and partial handshakes in the comdb2_metrics table.
It also keeps track of per-connection SSL attributes such as the Common Name in the comdb2_connections table.

Signed-off-by: Rivers Zhang <hzhang320@bloomberg.net>

2022-05-25 23:34 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/434 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>recover_ddlk_sp</p>

2022-05-26 13:21 UTC, nirbhayc commented on tests/simple_ssl.test/runit
> +if [ $all_ssl = 0 ]; then
Should be $has_handshake_cnt.

2022-05-26 13:32 UTC, nirbhayc approved these changes
Found a typo in the test, looks good otherwise.

2022-05-27 15:05 UTC, nirbhayc approved these changes
Good to merge.

2022-05-27 15:06 UTC, riverszhang89 commented
@nirbhayc Thanks for the review, Nirbhay!

2022-05-27 15:06 UTC, merged