Removing partitioning for a "table"
bloomberg/comdb2 pull request #3294
Opened 2022-06-08 13:24 UTC by dorinhogea

Introducing syntax:

ALTER TABLE t PARTITIONED BY NONE

This replaces partition "t" with a table "t" that contains all the data of the original shards.

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

2022-06-08 14:26 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/434 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_downgrade [core dumped]<br>socksql_master_swings<br>verify_writes<br>sc_downgrade</p>

2022-07-13 17:44 UTC, mponomar submitted a review, later dismissed

2022-07-14 18:31 UTC, markhannum approved these changes
Good to merge!

2022-07-14 19:59 UTC, merged

2022-07-14 19:59 UTC, dorinhogea commented
Thank you Mark!