Use temptable for sqlite's rowset
bloomberg/comdb2 pull request #3316
Opened 2022-07-05 18:32 UTC by riverszhang89

SQLite's rowset is implemented using binary search trees. These binary trees are kept in memory. When a large amount of rowid's are recorded, this implementation ends up using quite a lot memory.

This patch provides an alternative implementation using temptable, which spills content to disk when the amount of entries is over a threshold to reduce memory footprint. It also runs faster than stock SQLite, thanks to its more compact and efficient data structure.

2022-07-05 18:36 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2022-07-05 19:54 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/439 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>sc_truncate<br>ignore_bad_table<br>load_cache_autocache_generated<br>tunables</p>

2022-07-05 19:56 UTC, mponomar approved these changes

2022-07-06 19:03 UTC, riverszhang89 commented
@mponomar Thanks for the review!

2022-07-06 19:03 UTC, merged