ALTER TABLE t MERGE t2
bloomberg/comdb2 pull request #3323
Opened 2022-07-12 20:30 UTC by dorinhogea

New syntax:

ALTER TABLE t ..., MERGE t2

It complements CREATE TABLE ... MERGE.. syntax.   

Example:
CREATE TABLE t (a int, bint);
CREATE TABLE t2(a int);
ALTER TABLE t drop column b, MERGE t2

The last statement will alter the table t, and merge t2 into it, atomically.

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

2022-07-12 21:40 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/439 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated<br>sc_truncate<br>ignore_bad_table</p>

2022-07-18 19:11 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/439 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_downgrade [core dumped]<br>socksql_master_swings<br>ignore_bad_table<br>lostwrite<br>load_cache_dumpmax_generated<br>sc_downgrade</p>

2022-07-21 17:53 UTC, mponomar approved these changes

2022-07-21 20:22 UTC, dorinhogea commented
Thank you Mike!

2022-07-21 20:22 UTC, merged