sp: Run trigger code in protected mode
bloomberg/comdb2 pull request #3328
Opened 2022-07-13 17:39 UTC by akshatsikarwar

There has been increased use of `luaL_error` (in `get_qdb`, for example) and this causes Lua  to `abort` when not running in protected mode.

Make all trigger code run in protected mode. Also reduces trigger specific code. They run pretty much like a consumer.

Signed-off-by: Akshat Sikarwar <asikarwar1@bloomberg.net>

2022-07-14 14:34 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>7/439 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_downgrade [core dumped]<br>sc_resume<br>socksql_master_swings<br>sc_truncate<br>siasof<br>ignore_bad_table<br>load_cache_autocache_generated<br>sc_downgrade</p>

2022-07-14 21:33 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>8/439 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_downgrade [core dumped]<br>sc_resume<br>socksql_master_swings<br>sc_truncate<br>siasof<br>sql_datetime_interval_arithmetic_leak<br>ignore_bad_table<br>load_cache_dumpmax_generated<br>sc_downgrade</p>

2022-07-15 15:05 UTC, mohitkhullar submitted a review, later dismissed
looks good

2022-07-15 19:10 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/439 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>sc_truncate_lockorder_generated<br>sc_truncate<br>siasof<br>sql_datetime_interval_arithmetic_leak<br>ignore_bad_table</p>

2022-07-18 13:15 UTC, mponomar approved these changes

2022-07-18 13:19 UTC, merged