Get avg cost from all results instead of last result's cost
bloomberg/comdb2 pull request #3334
Opened 2022-07-18 16:35 UTC by mohitkhullar

2022-07-19 16:26 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/439 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_downgrade [core dumped]<br>socksql_master_swings<br>sc_truncate<br>sql_datetime_interval_arithmetic_leak<br>ignore_bad_table<br>recover_ddlk_sp<br>datacopy<br>sc_downgrade</p>

2022-11-03 18:53 UTC, mponomar approved these changes

2022-11-03 18:55 UTC, mponomar submitted a review, later dismissed

2022-11-03 19:13 UTC, mohitkhullar commented
/runtests

2023-01-09 17:38 UTC, mohitkhullar commented
used different PR for these changes

2023-01-09 17:38 UTC, closed without merging