osql: Clean repository before rep_start
bloomberg/comdb2 pull request #3349
Opened 2022-07-25 17:36 UTC by akshatsikarwar

Fixes race condition between cleaning repository after upgrade, and
replicant restarting OSQL session. Without this fix, the replicant would
restart session first, then master node would clean repository, thus
losing the session. This would have caused the following failures:

On the master node:
```
EST 2022/02/09 18:07:50 bidxspdb:discarding packet for 1 29f8aa01-cd74-46a4-827b-4275afa5991a, session not found
EST 2022/02/09 18:07:55 bidxspdb:Missing SORESE sql session 0 29f8aa01-cd74-46a4-827b-4275afa5991a on c2pfbf-rr-001 from 0
```

On the replicant:
```
EST 2022/02/09 18:08:50 bidxspdb:Master c2pfbf-rr-001 failed to acknowledge session 1 29f8aa01-cd74-46a4-827b-4275afa5991a
```

On the client:
```
rc: 402 errstr: Client api should run query against a different node
```

Signed-off-by: Akshat Sikarwar <asikarwar1@bloomberg.net>

2022-07-25 17:36 UTC, akshatsikarwar commented
/silent

2022-07-25 18:12 UTC, mponomar approved these changes

2022-07-25 18:24 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2022-07-26 14:51 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/439 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>socksql_master_swings<br>siasof<br>sql_datetime_interval_arithmetic_leak<br>ignore_bad_table<br>updater_latency</p>

2022-07-26 14:53 UTC, merged