Increase maximum hostname length 63 -> 127 bytes
bloomberg/comdb2 pull request #3355
Opened 2022-07-28 17:08 UTC by gusmonod

This is required for setting a long hostname in `/opt/bb/etc/cdb2/config/comdb2db.cfg`.

To help us review your pull request, please consider providing an overview of the following:
* Type of the change: bug fix
* Current behavior: hostname is truncated to 64 bytes
* Expected behavior: accept longer hostnames e.g. `fv-az133-281.yhipumr4050edinzmvad0xeera.cx.internal.cloudapp.net`
* Steps to reproduce the bug:
    1. set a hostname of 64 bytes or more in `/opt/bb/etc/cdb2/config/comdb2db.cfg`
    2. run `/opt/bb/bin/cdb2sql $DB_NAME dev "select comdb2_host()"`
    3. observe the hostname be truncated to 63 bytes
* Why this behavior is better than the current behavior: longer hostnames are fairly common, especially when using virtualization, and in our case we don't get to choose the hostname (using Github Actions, running on Microsoft Azure).

2022-07-28 17:59 UTC, nirbhayc commented
/runtests

2022-07-28 18:00 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

2022-07-28 18:11 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Failed to compile.</p>

2022-07-29 14:56 UTC, gusmonod commented
/runtests

2022-07-29 15:05 UTC, gusmonod commented
I guess I am not enabled to do that command above. Is there anything I can do to help making the coding style/smoke test/compile check pass?

I'm aware that it isn't very helpful, but this code is building and running on my Ubuntu VM just fine.

2022-07-29 15:08 UTC, mponomar commented
Thanks for the PR Gus, we'll take a look at it.

2022-07-29 15:09 UTC, nirbhayc commented
/runtests

2022-07-29 15:20 UTC, nirbhayc commented
@gusmonod : You'd also need to update https://github.com/bloomberg/comdb2/blob/master/tests/tools/cdb2api_unit.c

```
/bb/comdb2a/roborivers/branches/master/tests/tools/cdb2api_unit.c: In function 'test_read_comdb2db_cfg':
/bb/comdb2a/roborivers/branches/master/tests/tools/cdb2api_unit.c:209:23: error: passing argument 5 of 'read_comdb2db_cfg' from incompatible pointer type [-Werror]
                       &dbnum, &stack_at_open);
                       ^
In file included from /bb/comdb2a/roborivers/branches/master/tests/tools/cdb2api_unit.c:25:0:
/bb/comdb2a/roborivers/branches/master/cdb2api/cdb2api.c:1251:13: note: expected 'char (*)[128]' but argument is of type 'char (*)[64]'
 static void read_comdb2db_cfg(cdb2_hndl_tp *hndl, SBUF2 *s,
             ^
/bb/comdb2a/roborivers/branches/master/tests/tools/cdb2api_unit.c:209:23: error: passing argument 9 of 'read_comdb2db_cfg' from incompatible pointer type [-Werror]
                       &dbnum, &stack_at_open);
```

When done, do a `make test-tools` to confirm test files build fine as well.

2022-07-29 15:31 UTC, riverszhang89 commented
[Thanks for the pull ](https://github.com/bloomberg/comdb2/blob/master/tests/cdb2api_unit.test/unit_get_comdb2db_hosts.c#L33-L47)

These will need to adjusted accordingly.

2022-07-29 18:10 UTC, gusmonod commented
> @gusmonod : You'd also need to update https://github.com/bloomberg/comdb2/blob/master/tests/tools/cdb2api_unit.c
> 
> ```
> /bb/comdb2a/roborivers/branches/master/tests/tools/cdb2api_unit.c: In function 'test_read_comdb2db_cfg':
> /bb/comdb2a/roborivers/branches/master/tests/tools/cdb2api_unit.c:209:23: error: passing argument 5 of 'read_comdb2db_cfg' from incompatible pointer type [-Werror]
>                        &dbnum, &stack_at_open);
>                        ^
> In file included from /bb/comdb2a/roborivers/branches/master/tests/tools/cdb2api_unit.c:25:0:
> /bb/comdb2a/roborivers/branches/master/cdb2api/cdb2api.c:1251:13: note: expected 'char (*)[128]' but argument is of type 'char (*)[64]'
>  static void read_comdb2db_cfg(cdb2_hndl_tp *hndl, SBUF2 *s,
>              ^
> /bb/comdb2a/roborivers/branches/master/tests/tools/cdb2api_unit.c:209:23: error: passing argument 9 of 'read_comdb2db_cfg' from incompatible pointer type [-Werror]
>                        &dbnum, &stack_at_open);
> ```
> 
> When done, do a `make test-tools` to confirm test files build fine as well.

Thanks for the explanation, I have updated the tests forward declarations, but unfortunately I was not able to run `make test-tools` because it fails with a protobuf error:

```
[  0%] Generating sqlquery.pb-c.h, sqlquery.pb-c.c
sqlquery.proto:53:7: Expected "required", "optional", or "repeated".
sqlquery.proto:53:21: Missing field number.
make[3]: *** [protobuf/CMakeFiles/proto.dir/build.make:85: protobuf/sqlquery.pb-c.h] Error 1
make[2]: *** [CMakeFiles/Makefile2:1195: protobuf/CMakeFiles/proto.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2878: tests/tools/CMakeFiles/test-tools.dir/rule] Error 2
make: *** [Makefile:1213: test-tools] Error 2
```

2022-07-29 18:27 UTC, nirbhayc commented
@gusmonod You might be using some old protobuf compiler. This is what I have on my machine:
```
$ protoc-c  --version
protobuf-c 1.2.1
libprotoc 3.0.
```

2022-07-29 20:41 UTC, gusmonod commented
I am indeed using an older version, but I'm not sure on how to update. It seems I am already on the latest DPKG version of `libprotobuf-c-dev`

2022-07-29 20:50 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

2022-07-29 21:01 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Failed to compile.</p>

2022-07-29 21:01 UTC, riverszhang89 commented
Can you try apt-get update && apt-get upgrade? Anyhow I'm rerunning your pull request now to see if it compiles.

2022-07-29 21:07 UTC, riverszhang89 commented
https://github.com/bloomberg/comdb2/blob/master/tests/tools/cdb2api_unit.c#L187-L188

These 2 lines need adjusting too. Maybe just replace all 64's with the COMDB2HOSTNAME_LEN macro in that file?

2022-07-29 21:17 UTC, gusmonod commented
> Can you try apt-get update && apt-get upgrade? Anyhow I'm rerunning your pull request now to see if it compiles.

I tried that and I still have the same versions.

> These 2 lines need adjusting too. Maybe just replace all 64's with the COMDB2HOSTNAME_LEN macro in that file?

There are only 2 occurrences of 64 in that file, but 52804 in the whole repository. So I've changed that file, and will let you tell me if there are other places where it should be done.

2022-07-30 01:34 UTC, nirbhayc commented
/runtests

2022-07-30 16:10 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

2022-07-30 16:11 UTC, riverszhang89 commented
resubmitted for testing

2022-07-30 16:21 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Failed to compile.</p>

2022-07-31 03:51 UTC, riverszhang89 commented on tests/tools/cdb2api_unit.c
> +#define CDB2HOSTNAME_LEN 64
Did you mean 128 here?

2022-08-02 15:05 UTC, gusmonod commented on tests/tools/cdb2api_unit.c
> +#define CDB2HOSTNAME_LEN 64
yes :-/

2022-08-02 15:21 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

2022-08-02 16:24 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>10/440 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_downgrade [core dumped]<br>sc_resume<br>socksql_master_swings<br>sc_truncate<br>siasof<br>sql_datetime_interval_arithmetic_leak<br>ignore_bad_table<br>weighted_standing_queue<br>op_makerecord<br>load_cache</p>

2022-08-03 13:33 UTC, gusmonod commented
Can I have help on how to fix the tests?

2022-08-03 16:08 UTC, nirbhayc commented
/runtests

2022-08-04 20:11 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

2022-08-04 21:34 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>7/440 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>siasof<br>sql_datetime_interval_arithmetic_leak<br>ignore_bad_table<br>weighted_standing_queue<br>load_cache_autocache_generated<br>load_cache_dumpmax_generated</p>

2022-08-05 14:07 UTC, akshatsikarwar approved these changes

2022-08-05 14:07 UTC, merged