Weighted average queue metrics
bloomberg/comdb2 pull request #3357
Opened 2022-07-28 20:07 UTC by riverszhang89

Queue metrics, previously, were just moving averages. They did not respond well to a pulsed workload and often resulted in a false positive. This patch introduces weighted average queue metrics that are less sensitive to spikes.

(DRQS 169797794)

2022-07-28 20:10 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2022-07-28 21:16 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>5/440 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>sql_datetime_interval_arithmetic_leak<br>ignore_bad_table<br>selectv_deadlock<br>sc_downgrade</p>

2022-07-29 13:51 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2022-07-29 15:36 UTC, mponomar approved these changes

2022-07-29 16:48 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/440 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>sc_truncate_lockorder_generated<br>siasof<br>sql_datetime_interval_arithmetic_leak<br>ignore_bad_table<br>load_cache_dumpmax_generated<br>reorder_inserts_noreorder_generated</p>

2022-07-29 17:09 UTC, merged