Force direct on any environment where the flag is set.
bloomberg/comdb2 pull request #3360
Opened 2022-08-01 20:05 UTC by mponomar

Some codepaths always open a file with no O_DIRECT. On AIX a file can't be opened with both O_DIRECT and no O_DIRECT.

Signed-off-by: Mike Ponomarenko <mponomarenko@bloomberg.net>

2022-08-01 20:11 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2022-08-01 20:12 UTC, akshatsikarwar submitted a review, later dismissed

2022-08-01 20:21 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Failed to compile.</p>

2022-08-02 13:01 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2022-08-02 13:04 UTC, riverszhang89 approved these changes
Good to merge!

2022-08-02 13:05 UTC, merged