Disable the auto-consume logic in cdb2_close
bloomberg/comdb2 pull request #3362
Opened 2022-08-03 03:16 UTC by riverszhang89

cdb2_close() attempts to drain unfetched rows in order to make the connection reusable for the next sockpool user. This logic however may undesirably consume events from a consumer. Disable it by default.

Fixes #3361.

2022-08-03 03:20 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

2022-08-03 04:25 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/440 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_downgrade [core dumped]<br>socksql_master_swings<br>sc_truncate<br>phys_rep<br>ignore_bad_table<br>weighted_standing_queue<br>load_cache_dumpmax_generated<br>load_cache_autocache_generated<br>cdb2_close<br>sc_downgrade</p>

2022-08-03 12:48 UTC, akshatsikarwar commented
I was thinking it might be better to simply track if `cdb2_run_statment` has ever received a ping-pong request, and if so skip donating to sockpool (and so no need to drain connection). Don't want to disable it by default.

2022-08-03 13:38 UTC, akshatsikarwar commented
Also need to patch `consume_previous_query` in the API.

2022-08-03 13:43 UTC, akshatsikarwar commented
bb-cdb2api does not have auto-consume in `cdb2_close`, but does in `cdb2_run_statement`:
```
   else if (hndl->ack) {
       hndl->ack = 0;
       if (hndl->sb) {
           int fd = cdb2buf_fileno(hndl->sb);
           shutdown(fd, SHUT_RDWR);
       }
   }
   else {
       while(cdb2_next_record_int(hndl) == CDB2_OK);
   }
```

This is insufficient, as user might have called `cdb2_clear_ack`. I think we need to track if prior `cdb2_run_statement` was for a consumer or not.

2022-08-03 15:24 UTC, riverszhang89 commented
Yes you're right. We need to patch these places for a mixed use of 'exec procedure' on a consumer and regular queries.

2022-08-04 20:20 UTC, akshatsikarwar commented
Disable for now - we can make it robust later.

2022-08-05 14:05 UTC, akshatsikarwar approved these changes

2022-08-05 14:05 UTC, merged