Print queries and client info on too many verify errors
bloomberg/comdb2 pull request #3387
Opened 2022-08-18 22:56 UTC by riverszhang89

If a transaction retries too many times on verify error, print its osql history and client info. This will help developers identify the application code that generates the contention.

(DRQS 170139901)

2022-08-18 23:00 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2022-08-18 23:51 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2022-08-19 11:56 UTC, mponomar submitted a review, later dismissed

2022-08-19 14:06 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2022-08-19 14:27 UTC, markhannum approved these changes
Good to merge!

2022-08-19 15:05 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>4/440 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logarchive [core dumped]<br>sc_truncate<br>ignore_bad_table<br>load_cache<br>logarchive</p>

2022-08-19 19:33 UTC, markhannum approved these changes
Reviewed before- good to merge!

2022-09-08 14:41 UTC, merged