guid_str(): Fix off-by-one error (ported from 7.0)
bloomberg/comdb2 pull request #3396
Opened 2022-08-24 13:52 UTC by nirbhayc

guid_str() function returned one extra length, including the
terminating NULL byte, causing cstring validations to fail.

Note: It turns out this issue was already fixed in master branch
(https://github.com/bloomberg/comdb2/pull/2427), so this cherry-
pick only has test changes.

Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

To help us review your pull request, please consider providing an overview of the following:
* What is the type of the change (bug fix, feature, documentation and etc.) ?
* What are the current behavior and expected behavior, if this is a bugfix ?
* What are the steps required to reproduce the bug, if this is a bugfix ?
* What is the current behavior and new behavior, if this is a feature change or enhancement ?
* [Optional] Why is the new behavior better than the current behavior, if this is a feature change ?

2022-08-24 15:09 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>7/440 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>sql_datetime_interval_arithmetic_leak<br>phys_rep<br>ignore_bad_table<br>selectv_deadlock<br>load_cache_dumpmax_generated<br>guid</p>

2022-08-24 17:30 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/440 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>sc_truncate_lockorder_generated<br>ignore_bad_table</p>

2022-09-09 14:07 UTC, riverszhang89 approved these changes

2022-09-09 14:13 UTC, merged

2022-09-09 14:13 UTC, nirbhayc commented
@riverszhang89 thanks!!