pushnext for non-singlemeta
bloomberg/comdb2 pull request #3425
Opened 2022-09-19 14:20 UTC by riverszhang89

Simple fix to make pushnext work on non-singlemeta databases.

2022-09-19 14:30 UTC, roborivers reviewed
Lint check:

```diff


@@ db/pushlogs.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2022-09-19 16:51 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/441 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>updcolsbug<br>ignore_bad_table<br>load_cache_dumpmax_generated</p>

2023-05-15 17:24 UTC, mponomar approved these changes

2023-05-15 18:20 UTC, riverszhang89 commented
@mponomar Thank you for the review!

2023-05-15 18:20 UTC, merged