Core if watchdog times-out
bloomberg/comdb2 pull request #3468
Opened 2022-10-17 13:32 UTC by markhannum

Signed-off-by: Mark Hannum <mhannum72@gmail.com>

Produce a core if watchdog alarms while printing useful debugging information.

2022-10-17 16:50 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2022-10-17 20:27 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/449 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>selectv_rcode_disable_svonly_nop_generated<br>ignore_bad_table<br>updater_latency</p>

2022-10-18 13:54 UTC, akshatsikarwar approved these changes

2022-10-18 13:57 UTC, merged

2022-10-18 14:28 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>