Adjust zap of inline portion by one byte
bloomberg/comdb2 pull request #3470
Opened 2022-10-18 20:14 UTC by chands10

See conditional above lines added. Size copied to out buffer is (inlen - 1), not inlen, so zap an extra byte

Signed-off-by: Salil Chandra <schandra107@bloomberg.net>

To help us review your pull request, please consider providing an overview of the following:
* What is the type of the change (bug fix, feature, documentation and etc.) ?
* What are the current behavior and expected behavior, if this is a bugfix ?
* What are the steps required to reproduce the bug, if this is a bugfix ?
* What is the current behavior and new behavior, if this is a feature change or enhancement ?
* [Optional] Why is the new behavior better than the current behavior, if this is a feature change ?

2022-10-31 21:52 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2022-11-08 20:24 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/451 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ufid_recovery [core dumped]<br>ignore_bad_table<br>load_cache_dumpmax_generated</p>

2022-11-18 19:27 UTC, markhannum approved these changes
Good to merge!

2022-11-21 19:04 UTC, chands10 commented
Thanks Mark!

2022-11-21 19:04 UTC, merged