cdb2api: shut down SSL before donating to sockpool
bloomberg/comdb2 pull request #3490
Opened 2022-10-26 14:56 UTC by riverszhang89

Make sure that an SSL connection is shut down before its underlying file descriptor is donated to the sockpool.

2022-10-26 15:00 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

2022-10-26 15:57 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>4/449 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated<br>sql<br>ignore_bad_table<br>sp_snapshot_generated</p>

2022-11-23 15:36 UTC, mohitkhullar approved these changes
looks good

2022-11-23 15:36 UTC, riverszhang89 commented
@mohitkhullar thank you so much again!

2022-11-23 15:36 UTC, merged