Switch order of conds to compress prev correctly
bloomberg/comdb2 pull request #3492
Opened 2022-10-27 17:53 UTC by chands10

This will separate out prev from pfx prev in encode_repeat_rev Thanks Akshat for test!

Given:
```
create table test {
schema {
    u_short a
    vutf8   b[1000]
    vutf8   c[500]
}
}$$
```
Then `insert into test values (0, 'hi', 'hj')`
```
Previously:
compressComdb2RLE_hints
   encode_repeat: 2 x 0x080000
     encode_prev: 0x0003686900000(many many 0s)000800000003686a
encode_wellknown: 498 x 0x00
Now:
compressComdb2RLE_hints
   encode_repeat: 2 x 0x080000
     encode_prev: 0x00036869
encode_wellknown: 998 x 0x00
     encode_prev: 0x0800000003686a
encode_wellknown: 498 x 0x00
```
This is because the record starts with 080000080000, so a will be compressed with part of b since 080000 repeats, so now you are at middle of b. Compression code says go to beginning of next field (c) in this case. We still need to compress the rest of b. Call what we still need to compress from b variable prev:
```
00036869 00000000 00000000 00000000  |..hi............|
(1000 0s)
3c0:00000000 00000000 00000000 00000000  |................|
3d0:00000000 00000000 00000000 00000000  |................|
```
Since c can also be compressed, the code calls encode_repeat_rev. Encode_repeat_rev will append the prefix of c ('hj') (0800 000003686A) to the end prev. With this new prev variable, the code will now encode it. But now prev doesn't end in 0s which is problematic. The code detects repetition by checking for a repeating byte from the end of prev, but the last byte isn't 0 anymore. Now when you encode prev though, the repeating 0s won't be detected and prev will not be compressed at all. So the problem is just that you are trying to compress the 1000 0s with the prefix of c tagged on at the end, and the fix is to separate them out so that the code can detect the 1000 0s. To do this, just call encode_prev_rev on prev before calling encode_repeat_rev on c. This can be done by just switching the two conditionals in the code, and changing an else if to an if.

2022-10-27 17:55 UTC, roborivers reviewed
Lint check:

```diff


@@ comdb2rle/comdb2rle.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2022-10-27 17:56 UTC, chands10 commented
I also think now that whenever encode_repeat_rev is called, *prev will be 0, so it may not be needed anymore, but I still kept it in just in case.

2022-10-27 18:36 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2022-10-28 13:36 UTC, roborivers reviewed
Lint check:

```diff


@@ comdb2rle/comdb2rle.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2022-10-28 14:28 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2022-10-28 14:32 UTC, chands10 commented
Decided to remove prev as parameter for encode_repeat_rev

2022-10-28 14:36 UTC, roborivers reviewed
Lint check:

```diff


@@ comdb2rle/comdb2rle.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2022-10-28 15:14 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2022-10-28 15:20 UTC, roborivers reviewed
Lint check:

```diff


@@ comdb2rle/comdb2rle.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2022-10-28 16:05 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2022-10-28 17:45 UTC, roborivers reviewed
Lint check:

```diff


@@ comdb2rle/comdb2rle.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2022-10-28 18:48 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/449 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated<br>sc_truncate<br>ignore_bad_table<br>selectv_deadlock<br>load_cache_dumpmax_generated</p>

2022-10-28 19:42 UTC, akshatsikarwar commented
I have a failing test case: `short(0), short(0), 10000('hi'), short(1), 5000('HI')` -- When I was looking at this with you earlier, I had come up with a slightly different patch. I consume prev _only_ when we land in the middle of a field (https://github.com/akshatsikarwar/crle/commit/25698f5957bcee1f1e6bfe5ed06a343c891f3a4d). But I like your patch better. Perhaps we need to keep tracking `prev`? My program updated with the schema above: https://github.com/akshatsikarwar/crle

2022-10-28 20:03 UTC, chands10 commented
I think I see what happens here, when getting to short(1), which = 0, so you don't go in there, so encode_prev_rev is never called. I don't think which should matter for encode_prev_rev though, so I think just moving the encode_prev_rev conditional I have in my new code outside of which solves the problem

2022-10-28 20:07 UTC, chands10 commented
I don't think prev is needed for encode_repeat_rev anymore, but I can add the parameter back if you want. With my new code, it is only called 1) after encode_prev_rev, so *prev will be 0 at this point, and 2) in encode_prev_rev if (repeats_rev() == True). In this case *prev is set to 0 and it doesn't matter either

2022-10-31 15:58 UTC, chands10 commented
Made a new patch that works

2022-10-31 17:16 UTC, roborivers reviewed
Lint check:

```diff


@@ comdb2rle/comdb2rle.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2022-10-31 17:16 UTC, chands10 commented
I also think with this change encode_prev_rev would not be needed anymore since there should not be any repeating chars in prev, but have left that unchanged

2022-10-31 18:07 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2022-10-31 18:46 UTC, roborivers reviewed
Lint check:

```diff


@@ comdb2rle/comdb2rle.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2022-10-31 19:41 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/449 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ufid_recovery [core dumped]<br>sql<br>ignore_bad_table<br>sc_timepart<br>weighted_standing_queue<br>load_cache<br>load_cache_dumpmax_generated</p>

2022-10-31 20:55 UTC, roborivers reviewed
Lint check:

```diff


@@ comdb2rle/comdb2rle.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2022-10-31 21:53 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/449 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated<br>phys_rep<br>ignore_bad_table<br>load_cache_dumpmax_generated<br>load_cache<br>reorder_inserts_noreorder_generated</p>

2022-11-07 15:52 UTC, chands10 commented
Thanks!

2022-11-07 15:56 UTC, merged