Move commit-delay-on-copy logic into the database
bloomberg/comdb2 pull request #3503
Opened 2022-11-02 18:06 UTC by markhannum

Signed-off-by: Mark Hannum <mhannum72@gmail.com>

Setting a database's commit-delay from copycomdb2 is inherently fragile- so this PR moves this logic into the database.  Any replicant which is being used for a copy asks the leader to delay its commits for a period of time (determined by the commit_delay_timeout_seconds tunable, which defaults to 10 seconds).  commit_delay_on_copy_ms is the amount of time that a single-commit will be delayed (it defaults to 8 ms).

The commit_delay_on_copy test demonstrates this logic.

2022-11-02 18:10 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ db/comdb2.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2022-11-02 19:03 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/450 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ignore_bad_table<br>weighted_standing_queue<br>commit_delay_on_copy<br>tunables</p>

2022-11-02 21:24 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/450 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>sql_datetime_interval_arithmetic_leak<br>phys_rep<br>ignore_bad_table<br>load_cache</p>

2022-11-03 12:44 UTC, mponomar approved these changes

2022-11-03 13:36 UTC, merged