ssl prefer modes
bloomberg/comdb2 pull request #3519
Opened 2022-11-08 17:13 UTC by riverszhang89

This patch adds 4 SSL modes which are useful if a client talks to multiple data sources that may or may not speak SSL, and the client wants to use SSL whenever possible.

2022-11-08 17:15 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

2022-11-08 18:40 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/453 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ignore_bad_table<br>datacopy</p>

2022-11-18 22:36 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

2022-11-18 23:41 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/453 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated<br>sql_datetime_interval_arithmetic_leak<br>ignore_bad_table<br>load_cache_autocache_generated</p>

2022-11-23 15:34 UTC, mohitkhullar approved these changes
looks good

2022-11-23 15:35 UTC, riverszhang89 commented
@mohitkhullar Thank you for the review!

2022-11-23 15:35 UTC, merged