Fix lazy_id_mutex deadlock
bloomberg/comdb2 pull request #3521
Opened 2022-11-08 21:24 UTC by riverszhang89

Ensure that lazy_id_mutex is always released.

(DRQS 170729627)

2022-11-08 21:26 UTC, riverszhang89 commented on berkdb/dbreg/dbreg_util.c
> -#if 0
This is a bad rebase from #3452. It should not be commented out.

2022-11-08 21:30 UTC, riverszhang89 commented on berkdb/dbreg/dbreg_util.c
> +		MUTEX_UNLOCK(dbenv, &lp->lazy_id_mutex);
This is the real fix for the dev issue.

2022-11-08 21:42 UTC, markhannum approved these changes
Good to merge!

2022-11-08 22:29 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/451 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ignore_bad_table<br>upsert<br>reorder_inserts_noreorder_generated</p>

2022-11-09 13:13 UTC, riverszhang89 commented
@markhannum thanks for the review!

2022-11-09 13:13 UTC, merged