Limit queue scan
bloomberg/comdb2 pull request #3546
Opened 2022-11-17 20:20 UTC by mponomar

Port 7.0 behavior of limiting queue scans for consumer/trigger queues.

2022-11-17 20:25 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2022-11-17 21:27 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>11/451 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_inserts_deletes_logicalsc_generated<br>sc_truncate<br>load_cache_autocache_generated<br>basic_singlenode_generated<br>basic_rowset_generated<br>basic_rte_generated<br>basic_snapshot_generated<br>basic_nolibevent_generated<br>basic_off_osql_odh_blob_generated<br>basic_nogenid48_generated</p>

2022-11-18 19:46 UTC, markhannum approved these changes

2024-02-15 13:37 UTC, mponomar commented
No need to do this, issue was with locks held by queue scan.

2024-02-15 13:37 UTC, closed without merging