Allow auto analyze on IAM enabled databases
bloomberg/comdb2 pull request #3551
Opened 2022-11-21 20:13 UTC by mohitkhullar

Will need only for connect, for rest in_sqlite_init/no_transaction (7.0) takes care of it
{DRQS 170823925}
Signed-off-by: mohitkhullar <mkhullar1@bloomberg.net>

2022-11-21 20:16 UTC, mponomar submitted a review, later dismissed

2022-11-21 22:49 UTC, mohitkhullar commented
Also pass IAM info to new thread

2022-11-21 22:57 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/452 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>weighted_standing_queue<br>op_makerecord<br>sc_lotsoftables_logicalsc_generated</p>

2022-11-22 19:26 UTC, mponomar approved these changes

2022-11-23 14:25 UTC, mohitkhullar commented
Thanks

2022-11-23 14:27 UTC, merged