Tunable to control warning about mismatch of equiv types (upmerge from 7.0)
bloomberg/comdb2 pull request #3559
Opened 2022-11-22 21:04 UTC by nirbhayc

Comdb2 can additionally run an older Sqlite version to ensure it returns stable column names and data types across major Comdb2 versions. It also emits a warning in the server logs when a mismatch is detected.

This patch introduces a tunable 'warn_on_equiv_type_mismatch' (off by default), which when disabled, forces Comdb2 to not warn on mismatch of equivalent data types.

This tunable only takes effect when 'old_column_names' is enabled.

Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

2022-11-22 21:05 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2022-11-22 21:20 UTC, markhannum approved these changes

2022-11-23 00:22 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/452 tests failed</b> &#x26A0;.</p>

2022-11-28 17:21 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2022-11-28 18:14 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/452 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>sc_truncate_lockorder_generated<br>basic_nogenid48_generated</p>

2022-11-28 19:38 UTC, mponomar approved these changes

2022-11-28 19:45 UTC, nirbhayc commented
Thank you guys!

2022-11-28 19:45 UTC, merged