rebuild should support table options. Deprecate REBUILD table option.
bloomberg/comdb2 pull request #3561
Opened 2022-11-25 19:11 UTC by aakash10292

Porting https://github.com/bloomberg/comdb2/pull/3539

2022-11-25 19:15 UTC, roborivers reviewed
Lint check:

```diff


@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
```

2022-11-25 20:42 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/455 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover<br>yast_stat4scan_generated<br>yast<br>phys_rep</p>

2022-12-16 14:43 UTC, nirbhayc commented
/runtests

2022-12-20 16:43 UTC, mponomar approved these changes

2022-12-20 16:43 UTC, merged