Fix tracking dirty tables for higher isolation levels {DRQS 170886119}
bloomberg/comdb2 pull request #3568
Opened 2022-12-02 19:04 UTC by akshatsikarwar

/silent

2022-12-02 20:05 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/455 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>transchunk_manyins</p>

2022-12-06 01:25 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/455 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>weighted_standing_queue</p>

2022-12-06 14:34 UTC, mponomar approved these changes

2022-12-06 16:02 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/455 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite</p>

2022-12-06 16:08 UTC, merged