fix rollback when a legacy tpt creation fails
bloomberg/comdb2 pull request #3571
Opened 2022-12-05 21:35 UTC by dorinhogea

Currently, legacy tpt creation commits llmeta for tpt before checking if it can create the first shard.  In this case, we can get in a situation when we have a tpt with missing shards and the server fails to restart.
Example:
create table t(a int);
create time partition on t as tv ...
drop time partition tv #user change mind, shards remain in place though
create time partition on t as tv ... # this fails because shards exist, but create the llmeta entry never less
drop table ... # manual shard drop
# at this point we have a tpt saved in llmeta that has no shards; restart will abort 

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

2022-12-05 22:44 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/455 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_downgrade</p>

2022-12-06 13:02 UTC, mponomar commented on db/fdb_fend.c
> +//#pragma GCC diagnostic ignored "-Wformat-truncation"
This generates a warning on newer compilers for the snprintf below

2022-12-15 19:59 UTC, mponomar approved these changes

2022-12-15 20:32 UTC, dorinhogea commented
Thanks Mike!

2022-12-15 20:32 UTC, merged