Fix an issue with comdb2_sc_status
bloomberg/comdb2 pull request #3573
Opened 2022-12-07 21:57 UTC by nirbhayc

In version R8, some backwards incompatible changes got introduced into the schema change object that broke the object's original deserializer function (buf_get_schemachange()). As a result, reading an sc status object created by R7 would fail if read by R8 (via comdb2_sc_status).

The fix was to keep the both the versions of the deserializer functions and invoke them appropriately.

The current (potential hackish) method to pick the right version on the deserializer function is based on the content of the first 4 bytes of the LLMETA_SCHEMACHANGE_STATUS payload, where it is assumed that the valid values of s->kind (between  SC_INVALID and SC_LAST, exclusive) will not coincide with the first 4 bytes of the rqid (fastseed) stored as the first member in  old (7.0's) LLMETA_SCHEMACHANGE_STATUS payload.

Refer: DRQS-170879936

Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

2022-12-07 22:53 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2022-12-08 21:04 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2022-12-09 16:42 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/455 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>weighted_standing_queue<br>sc_transactional<br>sc_downgrade</p>

2022-12-12 18:19 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/455 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>selectv_deadlock</p>

2022-12-12 20:33 UTC, akshatsikarwar approved these changes
LGTM

2022-12-13 15:12 UTC, merged

2022-12-13 15:12 UTC, nirbhayc commented
Thanks @akshatsikarwar!