Fix for missing log in longreqs file after a long chunked transaction completes
bloomberg/comdb2 pull request #3582
Opened 2022-12-13 13:29 UTC by aakash10292

porting https://github.com/bloomberg/comdb2/pull/3400

2022-12-13 13:39 UTC, riverszhang89 commented on db/sqlinterfaces.c
> +    if (sideeffects != TRANS_CLNTCOMM_CHUNK){
format is off.

2022-12-13 14:41 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/456 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>sc_parallel_logicalsc_generated<br>tunables</p>

2022-12-13 14:49 UTC, nirbhayc submitted a review, later dismissed

2022-12-13 18:13 UTC, mponomar submitted a review, later dismissed

2022-12-13 18:30 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/456 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>sc_truncate<br>triggersc_latency</p>

2022-12-14 04:48 UTC, riverszhang89 commented
Looks good. Can you please fix the format?

2022-12-15 13:53 UTC, mponomar approved these changes

2022-12-15 14:16 UTC, mponomar approved these changes

2022-12-15 14:17 UTC, merged