Fix SSL_get1_session crash
bloomberg/comdb2 pull request #3586
Opened 2022-12-15 02:58 UTC by riverszhang89

The SSL session code may segfault in `SSL_get1_session`. This patch fixes it.

2022-12-15 03:01 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

2022-12-15 04:11 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/456 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>phys_rep<br>weighted_standing_queue<br>tunables</p>

2022-12-15 13:58 UTC, mponomar approved these changes

2022-12-16 13:27 UTC, riverszhang89 commented
@mponomar Thank you, Mike!

2022-12-16 13:27 UTC, merged