physrep_ignore lrl option allows physreps to ignore traffic to certain tables
bloomberg/comdb2 pull request #3589
Opened 2022-12-19 17:39 UTC by markhannum

Signed-off-by: Mark Hannum <mhannum72@gmail.com>

Tables which are ignored are truncated to 2 pages as the database starts.  SQL against any ignored table will fail with a 'no such table' error.  I will add similar logic to tagged api.  The behavior is verified by the physrep_ignore_table test.

2022-12-19 17:41 UTC, roborivers reviewed
Lint check:

```diff


@@ bdb/phys_rep_lsn.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2022-12-19 18:29 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2022-12-19 21:12 UTC, riverszhang89 commented
```
^[[0m^[[91m/comdb2/bdb/file.c:4272:21: error: ignoring return value of 'truncate', declared with attribute warn_unused_result [-Werror=unused-result]
4272 |                     truncate(bdb_trans(tmpname, new), pagesize * 2);

```

2022-12-19 22:07 UTC, markhannum commented
> Thanks Rivers!

2022-12-19 22:11 UTC, roborivers reviewed
Lint check:

```diff


@@ bdb/phys_rep_lsn.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2022-12-19 23:37 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/457 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ufid_recovery [core dumped]<br>sc_timepart<br>yast_stat4scan_generated</p>

2022-12-20 01:41 UTC, roborivers reviewed
Lint check:

```diff


@@ bdb/phys_rep_lsn.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2022-12-20 02:36 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/457 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>weighted_standing_queue</p>

2022-12-20 15:20 UTC, nirbhayc approved these changes
Good to go!

2022-12-20 15:23 UTC, merged