Improving log->put performance
bloomberg/comdb2 pull request #3595
Opened 2022-12-22 15:04 UTC by riverszhang89

This patch introduces a new tunable to toggle the O_SYNC flag for log files. If O_SYNC isn't used, after the log buffer is written out when it's full, an synchronous sync_file_range() call is issued on the log file, to speed up future fsync() calls. In other words, We turn the synchronous IO in log->put() into an asynchronous write-out of page cache, and hence we can move much of the IO latency off the critical path. log->flush(), however, does issue an fsync() call after flushing out the log buffer, to ensure data has made it to disk.

2022-12-22 15:57 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>458/458 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sirace [setup failure]<br>cldeadlock [setup failure]<br>truncatesc [setup failure]<br>socksql_master_swings [setup failure]<br>maxtable [setup failure]<br>incremental_backup_load [setup failure]<br>verify_writes [setup failure]<br>systable_locking [setup failure]<br>sc_downgrade [setup failure]<br>rebuild_table_options [setup failure]</p>

2022-12-22 17:56 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ berkdb/log/log_put.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2022-12-22 19:03 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/458 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>phys_rep</p>

2022-12-22 22:37 UTC, roborivers reviewed
<p>Sysbench Transactions Per Second (commit: b8675cef):</p>

<pre lang=diff>
@@ sysbench/select_random_points @@
-19.18%
@@ sysbench/bulk_insert @@
+38.98%
@@ sysbench/select_random_ranges @@
-14.19%
@@ sysbench/oltp_insert @@
+111.03%
@@ sysbench/oltp_read_only @@
-23.12%
@@ sysbench/oltp_point_select @@
+17.71%
@@ sysbench/oltp_update_non_index @@
+16.67%
@@ sysbench/oltp_delete @@
+27.71%
@@ sysbench/oltp_update_index @@
+23.77%
@@ sysbench/oltp_read_write @@
-7.03%
@@ sysbench/oltp_write_only @@
+11.79%
</pre>

2022-12-22 23:16 UTC, markhannum commented
Holy Moly!

2022-12-23 20:32 UTC, markhannum approved these changes
Wow - good to merge!

2022-12-27 14:30 UTC, riverszhang89 commented
Passing rm, as well!

```
cdb2test   Dec 22 13:57:27 2022  in-comdb2db log_osync.R20221222.5
```

2022-12-27 14:31 UTC, riverszhang89 commented
@markhannum Thanks for the review!

2022-12-27 14:31 UTC, merged