libevent: don't report SSL_ERROR_SYSCALL errors
bloomberg/comdb2 pull request #3622
Opened 2023-01-11 13:48 UTC by riverszhang89

SSL_ERROR_SYSCALL is a fairly common error (e.g., an ECONNRESET will result in an SSL_ERROR_SYSCALL). Don't report such errors.

2023-01-11 14:44 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>1/458 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep</p>

2023-01-11 14:45 UTC, akshatsikarwar commented
Why is this special for SSL sockets? We report `errno`s for regular sockets.. https://github.com/bloomberg/comdb2/blob/master/net/net.c#L706

2023-01-12 19:30 UTC, mponomar approved these changes

2023-01-12 19:38 UTC, akshatsikarwar commented
Hang on now.. not so fast. Why are we seeing increased syscall errors? I don’t want to lose all trace of them happening. Want to special case ECONNRESET perhaps?

2023-01-12 19:44 UTC, riverszhang89 commented
I'm testing another patch that may reduce the errors. I think my[ 'fast-ssl-shutdown' ](https://github.com/bloomberg/comdb2/blob/master/util/ssl_io.c#L461)trick may be causing this.

2023-01-17 14:56 UTC, closed without merging