mark resume flag de-novo sc for missing shards during resume
bloomberg/comdb2 pull request #3647
Opened 2023-01-30 19:39 UTC by dorinhogea

Currently, if we have to resume more than sc_async_maxthreads during master swing, server deadlocks, unless the schemachange objects are marked s->resume == SC_RESUME.
Unfortunately, the de novo schema changes for missing shards, created during resume, do not have this flag marked, deadlocking the master.   This fixes it.
 
Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

2023-01-31 00:22 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/461 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>sc_truncate<br>verify_error</p>

2023-02-01 16:27 UTC, mohitkhullar approved these changes
lgtm

2023-02-01 16:29 UTC, mponomar approved these changes

2023-02-01 16:30 UTC, dorinhogea commented
Thank you Mohit!

2023-02-01 16:30 UTC, merged