Don't block on lock from the delete-old-files thread
bloomberg/comdb2 pull request #3650
Opened 2023-01-31 15:13 UTC by markhannum

This branch introduces a workaround for the "leaked-handle-lock" scenario that we've observed a few times against 8.0, where the delete-files thread is blocked for a significant time while holding an open-transaction.  It turns out that this operation is completely safe to attempt optimistically.  The changes in this PR provide the 'dont_block_delete_files_thread' tunable which do exactly that.

The 'delfile_block' test verifies this behavior by intentionally leaking handle-locks which subsequently block the delete-files thread.  We verify our success by comparing the most recent checkpoint with its checkpoint LSN.  Running this test with 'dont_block_delete_files_thread' enabled will always show these to be within a short-range of each other.  If this tunable is disabled, the delete-files transaction will remain open indefinitely.  The 'failure' test case I ran showed the last-ckp and ckp-lsn differing by more than 20 log files.

This is 'part 1' of this work.  Part 2 will provide a way to audit cases where handle-locks are leaked.

Signed-off-by: Mark Hannum <mhannum72@gmail.com>

2023-01-31 16:45 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/462 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>sc_truncate<br>phys_rep<br>ddl_no_csc2<br>tunables</p>

2023-01-31 18:46 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2023-01-31 19:45 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/462 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>phys_rep<br>verify_error_partial_index_off_generated</p>

2023-02-04 00:06 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2023-02-04 01:57 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/463 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated [core dumped]<br>sc_timepart<br>lostwrite<br>sc_timepart_logicalsc_generated</p>

2023-02-07 13:50 UTC, mponomar approved these changes

2023-02-07 13:51 UTC, merged