we already have a views lock
bloomberg/comdb2 pull request #3651
Opened 2023-02-01 18:41 UTC by dorinhogea

Views are accessed during prepare stage by sql threads, during rollout by cron thread on master, and by recover callbacks following rollbacks on the replicants.  We get a read lock in the first case, and a write one during the second event.  I fail to see an issue and a need for an additional persistent berkdb lock.

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

2023-02-01 19:48 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/461 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart [core dumped]<br>socksql_master_swings<br>triggersc_latency<br>verify_error<br>sc_timepart</p>

2023-02-01 21:12 UTC, markhannum approved these changes
Tx Dorin!  Sorry I misunderstood.  Good to merge!

2023-02-01 22:00 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/461 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart [core dumped]<br>phys_rep<br>incremental_backup_usenames<br>sc_timepart</p>

2023-02-02 19:21 UTC, dorinhogea commented
Thanks Mark

2023-02-02 19:21 UTC, merged