Tiered physical replicants
bloomberg/comdb2 pull request #3672
Opened 2023-02-08 21:39 UTC by nirbhayc

2023-02-08 21:41 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ util/sbuf2.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/reverse_conn.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/phys_rep.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/reversesql/reversesql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reverse_conn.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
@@ plugins/reversesql/reversesql.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2023-02-08 22:51 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>6/464 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart [core dumped]<br>sc_truncate<br>truncatesc<br>truncatesc_offline_generated<br>sc_addfield<br>op_makerecord<br>sc_timepart</p>

2023-03-02 20:13 UTC, nirbhayc commented
/runtests

2023-03-03 14:46 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ util/sbuf2.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/reverse_conn.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/reversesql/reversesql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reverse_conn.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
@@ plugins/reversesql/reversesql.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2023-03-03 18:43 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/468 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill_logput_window_generated<br>logfill<br>truncatesc<br>truncatesc_offline_generated<br>ddl_analyze<br>tunables</p>

2023-03-07 19:11 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ util/sbuf2.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/reverse_conn.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/reversesql/reversesql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reverse_conn.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
@@ plugins/reversesql/reversesql.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2023-03-07 20:35 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/469 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated<br>sc_truncate<br>selectv_deadlock<br>tunables</p>

2023-03-07 21:11 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ util/sbuf2.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/reverse_conn.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/reversesql/reversesql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reverse_conn.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
@@ plugins/reversesql/reversesql.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2023-05-01 18:30 UTC, nirbhayc commented on bdb/rep.c
> +int gbl_set_coherent_state_trace = 1;
Turn off

2023-05-01 18:38 UTC, nirbhayc commented on berkdb/rep/rep_record.c
> +int gbl_rep_badgen_trace = 1;
Turn off

2023-05-01 18:39 UTC, nirbhayc commented on berkdb/rep/rep_record.c
> +        //printf("==>%s:%d\n", __func__, __LINE__);
Remove

2023-05-01 18:39 UTC, nirbhayc commented on berkdb/rep/rep_record.c
> +        //logmsg(LOGMSG_USER, "%s:%d processing %d\n", __func__, __LINE__, rp->rectype);
Remove

2023-05-01 18:40 UTC, nirbhayc commented on berkdb/rep/rep_record.c
> +        //       rp->rectype);
Remove

2023-05-01 18:41 UTC, nirbhayc commented on berkdb/rep/rep_record.c
> +                //       __func__, __LINE__, rp->rectype,
Remove

2023-05-01 19:33 UTC, nirbhayc commented on db/sqlinterfaces.c
> +        // TODO (NC): Temporary hack to suppress this annoying warning, fixme.
Remove

2023-05-01 19:56 UTC, nirbhayc commented on plugins/reversesql/reversesql.c
> +       * Only allow readonly queries
REmove

2023-05-01 20:19 UTC, nirbhayc commented on db/phys_rep.c
> +        physrep_logmsg(LOGMSG_ERROR, "%s:%d Failed to connect to %s@%s (rc: %d)\n",
Cleanup handle.

2023-05-01 20:21 UTC, nirbhayc commented on db/reverse_conn.c
> +    snprintf(msg, sizeof(msg), "reversesql\n%s\n%s\n%s\n",
Use new protobuf hello message.

2023-06-07 12:46 UTC, markhannum submitted a review, later dismissed
Reviewed extensively in person over several days .. this is good to merge .. !

2023-06-12 18:52 UTC, markhannum approved these changes

2023-06-13 13:21 UTC, merged