Allow high port numbers, stop listen on same port twice, use_pmux
bloomberg/comdb2 pull request #3684
Opened 2023-02-16 12:56 UTC by mohitkhullar

Allow high port numbers
Don't listen (and fail) on same port twice
add option to not use portmux at all : use_portmux off

2023-02-17 21:55 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2023-02-21 14:31 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2023-02-21 15:31 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/464 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>phys_rep<br>weighted_standing_queue<br>tunables</p>

2023-02-24 15:44 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/464 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>weighted_standing_queue<br>sc_transactional_rowlocks_generated</p>

2023-02-24 21:18 UTC, mponomar approved these changes

2023-02-25 13:31 UTC, mohitkhullar commented
Thanks

2023-02-25 13:31 UTC, merged