port sqlite fix for view coroutines
bloomberg/comdb2 pull request #3685
Opened 2023-02-16 19:13 UTC by dorinhogea

Currently when data from a view (or partition in the 171341108 case), code does an extra table lookup for row, and this is slow.   We have a patch from sqlite that effectively turn the extra columns to NULL, so the deferred lookup is never materialized.

2023-02-17 22:50 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2023-02-21 14:38 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2023-02-22 17:13 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/464 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>phys_rep<br>weighted_standing_queue<br>selectv_deadlock<br>physrep_ignore_table</p>

2023-02-22 18:56 UTC, mponomar approved these changes

2023-02-27 14:23 UTC, merged

2023-02-27 14:23 UTC, dorinhogea commented
Thank you Mike!