{171483098} net: Do not hold rd-lock while waiting for ack in net_send
bloomberg/comdb2 pull request #3701
Opened 2023-02-27 16:48 UTC by akshatsikarwar

/silent

2023-02-27 17:44 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/466 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep<br>weighted_standing_queue</p>

2023-03-01 16:51 UTC, akshatsikarwar commented
Tested here: https://github.com/akshatsikarwar/comdb2/commit/b40a8c29959bea22e4dcf93799e59d9f4d697aa1

Works correctly with libevent-net. Does not work with legacy-net, where the connect-thread tries to free up host and `pthread_mutex_destory` fails:
```
[FATAL] rem_from_netinfo_ll:2618 pthread_mutex_destroy(0x555555e5f9a0) rc:16 (Device or resource busy) thd:0x7fffee699700
```

2023-03-01 17:57 UTC, mponomar approved these changes

2023-03-01 19:02 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/468 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill<br>phys_rep<br>tunables</p>

2023-03-01 19:06 UTC, merged