Fixing local replicant edge case
bloomberg/comdb2 pull request #3702
Opened 2023-02-27 19:11 UTC by riverszhang89

If the last column of a replicated table is vutf8 without an inline size hint, and the new ondisk data for the column is an empty string, we mistakenly write 1 byte after what's allocated for its comdb2_oplog entry, e.g.:

```
==134601== Invalid write of size 1
==134601==    at 0x50163B: local_replicant_log_add (localrep.c:260)
==134601==    by 0x552790: add_record (record.c:618)
==134601==    by 0x51A23A: osql_process_packet (osqlcomm.c:6509)
==134601==    by 0x506FFE: process_this_session (osqlblockproc.c:987)
==134601==    by 0x5075A6: apply_changes (osqlblockproc.c:1092)
==134601==    by 0x505C0A: osql_bplog_commit (osqlblockproc.c:348)
==134601==    by 0x603669: toblock_main_int (toblock.c:4637)
==134601==    by 0x6071F5: toblock_main (toblock.c:5866)
==134601==    by 0x5FC65D: toblock_outer (toblock.c:2266)
==134601==    by 0x5FB9DF: toblock (toblock.c:2011)
==134601==    by 0x5687F0: handle_op_local (sltdbt.c:167)
==134601==    by 0x568C72: handle_op_block (sltdbt.c:254)
==134601==  Address 0x14999624 is 0 bytes after a block of size 308 alloc'd
==134601==    at 0x40397BB: malloc (vg_replace_malloc.c:393)
==134601==    by 0x500FB7: local_replicant_log_add (localrep.c:150)
==134601==    by 0x552790: add_record (record.c:618)
==134601==    by 0x51A23A: osql_process_packet (osqlcomm.c:6509)
==134601==    by 0x506FFE: process_this_session (osqlblockproc.c:987)
==134601==    by 0x5075A6: apply_changes (osqlblockproc.c:1092)
==134601==    by 0x505C0A: osql_bplog_commit (osqlblockproc.c:348)
==134601==    by 0x603669: toblock_main_int (toblock.c:4637)
==134601==    by 0x6071F5: toblock_main (toblock.c:5866)
==134601==    by 0x5FC65D: toblock_outer (toblock.c:2266)
==134601==    by 0x5FB9DF: toblock (toblock.c:2011)
==134601==    by 0x5687F0: handle_op_local (sltdbt.c:167)
```

This patch fixes it.

2023-02-27 19:21 UTC, mohitkhullar approved these changes
lgtm

2023-02-27 20:11 UTC, nirbhayc approved these changes

2023-02-27 20:44 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/466 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated<br>ddl_analyze</p>

2023-02-28 14:18 UTC, riverszhang89 commented
@mohitkhullar @nirbhayc Thanks for the review!

2023-02-28 14:18 UTC, merged