manual partition updates
bloomberg/comdb2 pull request #3722
Opened 2023-03-08 19:43 UTC by dorinhogea

Updates:
- the backend table "comdb2_logical_cron" is automatically created when first manual partition is created, if it does not exist
- the start value for a counter is optional, and defaults to 0 if missing in the statement
- rollout increment fix: now it starts properly from start value + 1, rather that default to 0

2023-03-08 19:46 UTC, roborivers reviewed
Lint check:

```diff


@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
```

2023-03-08 20:45 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/469 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>phys_rep<br>sc_timepart<br>verify_error_partial_index_off_generated<br>tunables<br>put_logical_cron<br>manual_partition_lgcy</p>

2023-04-03 19:23 UTC, mponomar approved these changes

2023-04-06 14:44 UTC, dorinhogea commented
Thank you Mike!

2023-04-06 14:44 UTC, merged