Trigger systable inversion
bloomberg/comdb2 pull request #3744
Opened 2023-03-16 20:47 UTC by markhannum

Reproduces and fixes a lock-inversion bug that occurs when viewing comdb2_triggers table by forcing sql-threads which access comdb2_triggers to acquire the splock prior to any Berkley locks.

2023-03-17 01:24 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/471 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>yast_stat4scan_generated<br>yast<br>logfill<br>window</p>

2023-03-17 12:46 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/src/vdbeInt.h @@
+ If the order of members in struct Mem is changed, columnNullValue (defined in sqlite/vdbeapi.c) needs to be reordered accordingly.
```

2023-03-17 12:53 UTC, mponomar submitted a review, later dismissed

2023-03-17 14:26 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/src/vdbeInt.h @@
+ If the order of members in struct Mem is changed, columnNullValue (defined in sqlite/vdbeapi.c) needs to be reordered accordingly.
```

2023-03-17 15:33 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/471 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>yast_stat4scan_generated<br>yast<br>sc_truncate<br>window<br>ddl_analyze</p>

2023-03-21 15:06 UTC, mponomar approved these changes

2023-03-21 15:06 UTC, merged