{171621407} fix index reorder bug
bloomberg/comdb2 pull request #3745
Opened 2023-03-21 19:45 UTC by aakash10292

While collecting and reordering index operations in the defered index table, we don't allocate sufficient memory for keys into the table. Specifically for dup indexes of length >= 512, we end up overwriting memory and corrupting fields in the dti key structure. This patch fixes the bug and updates the test cases to exercise the edge case.

2023-03-21 20:18 UTC, riverszhang89 submitted a review, later dismissed
Please fix format; otherwise good to merge!

2023-03-21 22:34 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>94/471 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>yast_stat4scan_generated<br>yast<br>logfill_logput_window_generated<br>sc_truncate<br>sc_transactional_rowlocks_generated<br>window<br>sp_twofiles_generated<br>verify_error<br>sc_transactional</p>

2023-03-22 18:26 UTC, riverszhang89 approved these changes

2023-03-22 18:27 UTC, aakash10292 commented
Thanks Rivers!

2023-03-22 18:27 UTC, merged