{171652600} Fixing internal stmt-cache leak
bloomberg/comdb2 pull request #3748
Opened 2023-03-22 20:01 UTC by riverszhang89

Simple change to fix a memory leak in the internal statement caching.

2023-03-22 20:29 UTC, nirbhayc commented on db/sqlinterfaces.c
> -            stmt_cache_add_entry(thd->stmt_cache, clnt->sql, 0, stmt, clnt);
I think we should just finalize/free this stmt here if `stmt_cache_add_entry` returns `-1`, as `stmt_cached_add_entry` already checks for duplicates.

2023-03-23 12:43 UTC, nirbhayc commented on db/sqlinterfaces.c
> -            stmt_cache_add_entry(thd->stmt_cache, clnt->sql, 0, stmt, clnt);
We discussed this; the cached stmt was also removed during find() so stmt_cache_add_entry wouldn't fail.

2023-03-23 12:44 UTC, nirbhayc approved these changes

2023-03-23 14:25 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/471 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>physrep_ignore_table<br>pmux_sqlite_file_generated</p>

2023-03-23 17:43 UTC, riverszhang89 commented
@nirbhayc Thanks for the review!

2023-03-23 17:43 UTC, merged