Adding systables that list files in database directory
bloomberg/comdb2 pull request #3758
Opened 2023-03-28 23:34 UTC by riverszhang89

This pull request adds 3 system tables `comdb2_files`, `comdb2_log_files` and `comdb2_tmp_files` that list files in the database's main, log and tmp directory, respectively (similar to PG's `pg_ls_dir`, `pg_ls_waldir` and `pg_ls_tmpdir`). For example, the statement below returns the names of llmeta and meta:

```
cdb2sql> SELECT * FROM comdb2_files WHERE file LIKE '%meta%'
(file='comdb2_llmeta.dta')
(file='comdb2_metadata.dta')
[SELECT * FROM comdb2_files WHERE file LIKE '%meta%'] rc 0
```

2023-03-28 23:35 UTC, roborivers reviewed
Lint check:

```diff


@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
```

2023-03-29 00:37 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/472 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>userschema_queueodh_generated<br>userschema<br>ddl_analyze</p>

2023-03-30 13:26 UTC, roborivers reviewed
Lint check:

```diff


@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
```

2023-04-11 20:07 UTC, chands10 requested changes

2023-04-11 20:07 UTC, chands10 commented on sqlite/ext/comdb2/files.c
> +    dirp = opendir(dir);
Looks like this directory is opened twice (also on line 44)

2023-04-11 20:07 UTC, chands10 commented on sqlite/ext/comdb2/files.c
> +    free(data);
I think you need to free each element of data?

2023-04-12 19:19 UTC, riverszhang89 commented
@chands10 Thanks for catching those!

2023-04-13 13:57 UTC, riverszhang89 commented
@chands10 Thanks for the review! However Nirbhay has a more complete version of this in https://github.com/bloomberg/comdb2/pull/2726. Withdrawing mine ...

2023-04-13 13:57 UTC, closed without merging