Change nodeix-indexed arrays into hash-tables
bloomberg/comdb2 pull request #3764
Opened 2023-04-04 13:38 UTC by markhannum

Change arrays which are sized by MAXNODES to hash-tables so that the nodeix value isn't forced to be less than MAXNODES.  This is a WIP- I'm submitting a PR early to allow RR to run it, and to open discussions about this or other approaches.

2023-04-04 13:41 UTC, roborivers reviewed
Lint check:

```diff


@@ bdb/file.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ bdb/rep.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-04-04 14:37 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>4/472 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>ddl_analyze<br>read_committed_unique<br>transchunk_manyins</p>

2023-04-05 13:11 UTC, roborivers reviewed
Lint check:

```diff


@@ bdb/file.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ bdb/rep.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ util/rtcpu.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-06-16 00:55 UTC, markhannum commented
Being reviewed under https://github.com/bloomberg/comdb2/pull/3768

2023-06-16 00:55 UTC, closed without merging