{171755293}: fixing race on clnt->appdata
bloomberg/comdb2 pull request #3767
Opened 2023-04-05 19:15 UTC by riverszhang89

After being freed by an appsock thread or a libevent event-loop, clnt->appdata may still be read from another thread of control.  This patch fixes it.

/plugin-branch exit_race

2023-04-05 19:20 UTC, roborivers reviewed
Lint check:

```diff


@@ plugins/newsql/newsql_evbuffer.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/newsql/newsql_sbuf.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-04-05 19:26 UTC, nirbhayc approved these changes

2023-04-05 19:28 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2023-04-10 12:55 UTC, riverszhang89 commented
@nirbhayc Thanks for the review, Nirbhay!

2023-04-10 12:55 UTC, merged

2023-04-10 14:08 UTC, mohitkhullar commented on plugins/newsql/newsql_evbuffer.c
> +    pthread_mutex_t *lk = (clnt->thd && clnt->thd->sqlthd) ? clnt->thd->sqlthd->lk : NULL;
&clnd->thd->sqlthd->lk ?