{171755293}: Fixing race on clnt
bloomberg/comdb2 pull request #3778
Opened 2023-04-12 14:59 UTC by riverszhang89

After being freed by an appsock thread or a libevent event-loop, clnt may still be read from another thread of control. This patch fixes it.

The original patch that attempted to address this issue, unfortunately, triggered a different race condition between sql-thread-exiting and newsql-cleanup. This patch adds a test to verify that both of these 2 races are addressed.

2023-04-12 15:01 UTC, roborivers reviewed
.

2023-04-12 15:18 UTC, akshatsikarwar commented on db/sqlinterfaces.c
> +    Pthread_mutex_unlock(&clnt->sql_lk);
or does that deadlock?

2023-04-12 15:20 UTC, akshatsikarwar commented
I prefer if in `cleanup_clnt`, we remove the clnt from `sql_threads` lists under big lock as first operation. Then rest can proceed without any other synchronization.

2023-04-12 15:56 UTC, riverszhang89 commented
Akshat has a better idea for this. I'll rework this a bit.

2023-04-12 16:32 UTC, roborivers requested changes
.

2023-04-12 19:26 UTC, roborivers reviewed
Lint check:

```diff


@@ db/sqlinterfaces.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-04-12 19:28 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2023-04-12 19:33 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2023-04-13 11:31 UTC, roborivers reviewed
.

2023-04-13 16:03 UTC, akshatsikarwar commented
Does this still work if txn is retrying? Would `thd` need `clnt` during retry? Maybe we need to set it during `done_cb_evbuffer`?

2023-05-09 13:08 UTC, mponomar submitted a review, later dismissed

2023-05-09 13:11 UTC, akshatsikarwar commented
/silent

2023-06-14 14:59 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/479 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover_noroll1_generated<br>api_events</p>

2023-06-14 18:22 UTC, akshatsikarwar approved these changes

2023-06-14 18:25 UTC, riverszhang89 commented
@akshatsikarwar Thanks for the review!

2023-06-14 18:25 UTC, merged

2023-06-14 19:14 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>4/479 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>sc_timepart_logicalsc_generated</p>