Docs update for new partitioned table syntax
bloomberg/comdb2 pull request #3787
Opened 2023-04-18 20:16 UTC by dorinhogea

Time to make this public.

2023-04-18 21:19 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/472 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>cldeadlock<br>sc_timepart_logicalsc_generated<br>sc_timepart<br>temp_table_truncate_leak</p>

2023-04-19 13:48 UTC, riverszhang89 submitted a review, later dismissed

2023-04-19 13:56 UTC, nirbhayc submitted a review, later dismissed
Pointed some minor typos inline. Looks good otherwise.

2023-04-19 13:56 UTC, nirbhayc commented on docs/pages/programming/sql.md
> +semantic was added in verson 8.0.  A partitioned table is a union of table shards
version

2023-04-19 13:56 UTC, nirbhayc commented on docs/pages/programming/sql.md
> +supports a time-based retention and manual retention partititioning.
partitioning

2023-04-19 13:56 UTC, nirbhayc commented on docs/pages/programming/table_partition.md
> +#creating a time partiton
partition

2023-04-19 13:56 UTC, nirbhayc commented on docs/pages/programming/table_partition.md
> +Implementing such a constrain would require that every write operation access and lock pages in each shard during constraint validation, effectively denying the main advantage of partitioning, which
localized

2023-04-19 14:24 UTC, nirbhayc approved these changes
Go go go!

2023-04-19 14:25 UTC, merged