{171830607}: Show time partitions in comdb2_columns, comdb2_keys and comdb2_keycomponents
bloomberg/comdb2 pull request #3792
Opened 2023-04-20 13:55 UTC by riverszhang89

This patch also fixes a deadlock between views_lk and the "comdb2_tables" berkdb lock. The solution is simple: don't acquire views_lk from within time partition systable code, but instead rely on the "comdb2_tables" lock to protect the in-memory data structures (similar to #3784).

2023-04-20 14:11 UTC, roborivers reviewed
Lint check:

```diff


@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
```

2023-04-20 16:53 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2023-04-20 16:58 UTC, chands10 commented on db/views_systable.c
> +        rv = &empty;
Does this return something on the stack?

2023-04-20 17:51 UTC, roborivers reviewed
Lint check:

```diff


@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
```

2023-04-20 19:27 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2023-04-21 11:41 UTC, roborivers reviewed
Lint check:

```diff


@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
```

2023-04-24 12:55 UTC, dorinhogea commented on tests/comdb2sys.test/comdb2sys.expected
> +[CREATE TIME PARTITION ON tbase1 AS tview1 PERIOD 'YEARLY' RETENTION 1 START '2038-01-01T00:00:00 UTC'] rc 0
Do you mind using the new syntax here?
https://bloomberg.github.io/comdb2/table_partition.html

2023-06-27 18:16 UTC, roborivers reviewed
Lint check:

```diff


@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
```

2023-06-27 19:27 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/479 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>phys_rep_tiered<br>sc_timepart_logicalsc_generated</p>

2023-07-12 15:01 UTC, riverszhang89 commented on db/views_systable.c
> -    Pthread_rwlock_rdlock(&views_lk);
Dorin's idea: grab `views_lk` in a system table query, as long as the database has a TPT. This is implemented [here](https://github.com/bloomberg/comdb2/pull/3792/files#diff-a0a9ddbc73870e09e5062d35480c25b430e20d3b1c0baa3d2703e95808a8e5a8R7647).

2023-07-28 14:33 UTC, dorinhogea approved these changes
Looks good to me! Thank you!

2023-07-31 12:33 UTC, merged