Don't acquire queue lk unless db:consumer is successful
bloomberg/comdb2 pull request #3805
Opened 2023-04-26 18:48 UTC by akshatsikarwar

/silent

2023-04-26 20:12 UTC, roborivers requested changes
.

2023-04-27 13:14 UTC, akshatsikarwar commented
/silent

2023-04-27 14:13 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/472 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>lostwrite</p>

2023-04-27 21:00 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/472 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill<br>sc_truncate<br>sc_timepart_logicalsc_generated</p>

2023-05-02 13:32 UTC, mponomar approved these changes

2023-05-02 13:35 UTC, merged