Recover_blkseq fix & blkseq_race test
bloomberg/comdb2 pull request #3808
Opened 2023-04-28 20:46 UTC by markhannum

Only add committed-blkseqs to the blkseq temp-tables.  A new test, blkseq_race, failed prior to this change because a new master would incorrectly add an uncommitted transaction to it's blkseq tables.

2023-04-28 20:50 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ db/osqlblkseq.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-04-28 22:16 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>4/473 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>tunables<br>basic_off_osql_odh_blob_generated<br>basic_nogenid48_generated</p>

2023-05-01 14:36 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2023-05-01 15:36 UTC, markhannum commented on db/db_tunables.h
> +REGISTER_TUNABLE("debug_blkseq_race", "Pause after adding blkseq to reproduce blkseq race.  (Default: off)",
sounds good 👍

2023-05-01 17:51 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2023-05-01 18:48 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>1/473 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_repeated_updates</p>

2023-05-02 14:13 UTC, merged