{171141266}: Ensure that heartbeat is stopped before sending last row
bloomberg/comdb2 pull request #3822
Opened 2023-05-09 19:29 UTC by riverszhang89

A stored procedure may send a heartbeat after the last row, which can break the SSL protocol when sockpool is present, as shown below.

|    | SERVER               |     CLIENT-1                                 |     CLIENT-2                            |
|----|----------------------|----------------------------------------------|-----------------------------------------|
| T0 | send ROW_LAST        |//////////////////////////////////////////////|/////////////////////////////////////////|
| T1 |//////////////////////| recv ROW_LAST, this is considered an OK_DONE |/////////////////////////////////////////|
| T2 | send HEARTBEAT       |//////////////////////////////////////////////|/////////////////////////////////////////|
| T3 |//////////////////////| cdb2_close; connection returned to sockpool  |/////////////////////////////////////////|
| T4 |//////////////////////|//////////////////////////////////////////////| cdb2_open; reuse the connection from T3; start SSL protocol; send SSLCONN packet |
| T5 | recv SSLCONN; call SSL_accept           |//////////////////////////////////////////////|/////////////////////////////////////////|
|----|----------------------|----------------------------------------------|-----------------------------------------|
| T6 |//////////////////////|//////////////////////////////////////////////| read 1st byte of the HEARTBEAT from T2; since it's not 'N', call SSL_connect.   now read the remainder of the heartbeat, which isn't part of SSL negotiation. SSL_connect fails.                      |
| T8 | SSL_accept fails     |//////////////////////////////////////////////|/////////////////////////////////////////|

This patch fixes it by switching off the ready_for_heartbeats flag before sending ROW_LAST, so that no heartbeats will go out after ROW_LAST and potentially be read by the next process that reuses the connection. The SSL-ability byte check in the API is also changed from `rc == 'N'` to `rc != 'Y'`, to avoid mishandling of a heartbeat packet (as shown at T6 in the table above).

2023-05-09 19:55 UTC, nirbhayc submitted a review, later dismissed

2023-05-09 19:55 UTC, nirbhayc commented
Good catch!!

2023-05-10 19:14 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>225/474 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>cldeadlock<br>logfill_logput_window_generated<br>sc_truncate<br>silogdel<br>selectv_timepart<br>serialstep<br>occ_selectv<br>snapisol_partial_index_off_generated<br>snapisol<br>eventlog</p>

2023-05-11 19:01 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/sql.h @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-05-11 20:52 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>6/474 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated<br>phys_rep<br>sc_timepart_logicalsc_generated<br>selectv_deadlock<br>recover_deadlock<br>commit_lsn_map</p>

2023-06-13 14:40 UTC, closed without merging