Poll a bit in llmeta after deadlock
bloomberg/comdb2 pull request #3839
Opened 2023-05-23 15:17 UTC by markhannum

ddl_analyze fails frequently because set-high-genid in schema change hits the deadlock limit.  This PR introduces a random poll after any transaction-less llmeta function receives a deadlock from Berkley.

2023-05-23 17:23 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/474 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep<br>sc_timepart<br>pmux_sqlite_memory_generated</p>

2023-05-24 14:56 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2023-05-24 15:05 UTC, riverszhang89 approved these changes
Looks good to merge!

2023-05-24 15:11 UTC, riverszhang89 approved these changes

2023-05-24 15:14 UTC, merged