configure every replicant in test
bloomberg/comdb2 pull request #3862
Opened 2023-06-07 15:47 UTC by dorinhogea

Need to run PUT on every node to be able to discover comdb2db replacement.

2023-06-07 17:00 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/476 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>incoh_remsql</p>

2023-06-07 23:42 UTC, markhannum commented on tests/tools/foreigndbconfig.c
> +                mach = optarg;
break;

2023-06-08 18:23 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/476 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>queuedb_rollover<br>sc_timepart_logicalsc_generated</p>

2023-06-08 19:52 UTC, dorinhogea commented
Thank you Salil!

2023-06-08 19:52 UTC, merged