Fixing statreqs misreporting after schemachange
bloomberg/comdb2 pull request #3867
Opened 2023-06-13 15:06 UTC by riverszhang89

Minor bug: the first statreqs diff after an alter-table or a truncate-table would misreport all the osql opcode counters. This change fixes it.

2023-06-13 16:15 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/478 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>recover_deadlock</p>

2023-06-15 14:36 UTC, chands10 approved these changes

2023-06-15 14:38 UTC, riverszhang89 commented
@chands10 Thanks for the review!

2023-06-15 14:38 UTC, merged

2023-06-15 15:02 UTC, chands10 commented
NPR!