Metrics for Queries Allowed/Denied
bloomberg/comdb2 pull request #3878
Opened 2023-06-27 13:42 UTC by mohitkhullar

2023-06-27 14:45 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/479 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated</p>

2023-06-27 17:05 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/479 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>queuedb_rollover_noroll1_generated<br>basic_off_osql_odh_blob_generated</p>

2023-06-27 17:22 UTC, nirbhayc requested changes

2023-06-27 17:33 UTC, mohitkhullar commented on db/db_access.c
> +    ATOMIC_ADD64(gbl_num_auth_allowed, 1);
in case of failure we return with an error over here

2023-06-27 17:34 UTC, mohitkhullar commented on db/db_access.c
> +         ATOMIC_ADD64(gbl_num_auth_allowed, 1);
Yes

2023-06-27 17:35 UTC, nirbhayc commented on db/db_access.c
> +    ATOMIC_ADD64(gbl_num_auth_allowed, 1);
Yes, right.

2023-06-27 17:44 UTC, nirbhayc submitted a review, later dismissed
Okay to merge

2023-06-28 13:22 UTC, mohitkhullar commented
Thanks

2023-06-28 14:12 UTC, nirbhayc approved these changes

2023-06-28 14:43 UTC, merged