Improved long-replication stats
bloomberg/comdb2 pull request #3884
Opened 2023-06-29 22:51 UTC by markhannum

The DBAs requested more insight into how long replication events are spending their time.  The 'longreq_stat' test  does a basic sanity-check.

2023-06-29 22:55 UTC, roborivers reviewed
Lint check:

```diff


@@ bdb/bdb.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2023-06-30 00:05 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2023-06-30 12:36 UTC, roborivers reviewed
Lint check:

```diff


@@ bdb/bdb.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2023-06-30 13:40 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/480 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>phys_rep<br>queuedb_rollover<br>sc_timepart_logicalsc_generated</p>

2023-06-30 15:06 UTC, roborivers reviewed
Lint check:

```diff


@@ bdb/bdb.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2023-06-30 17:09 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/480 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>queuedb_rollover_noroll1_generated</p>

2023-06-30 19:30 UTC, chands10 commented on berkdb/lock/lock.c
> +        }
Fix spacing here

2023-06-30 19:30 UTC, chands10 commented on berkdb/lock/lock.c
> +            p->n_locks++;
And here

2023-06-30 19:33 UTC, chands10 approved these changes
LGTM!

2023-06-30 19:34 UTC, merged