sbuf2: Fix valgrind errors when per-thread-malloc is disabled
bloomberg/comdb2 pull request #3908
Opened 2023-07-14 14:20 UTC by akshatsikarwar

```
==1078== Invalid read of size 8
==1078==    at 0x57BD53: comdb2_free (mem.c:1035)
==1078==    by 0x41FD57: SERVER_sbuf2free (sbuf2.c:141)
==1078==    by 0x41B5C1: portmux_cmd (portmuxusr.c:194)
==1078==    by 0x21079B: setup_net_listen_all (glue.c:5974)
==1078==    by 0x1C63AD: init (comdb2.c:3791)
==1078==    by 0x1B7139: main (comdb2.c:5570)
==1078==  Address 0x51deb58 is 8 bytes before a block of size 296 alloc'd
==1078==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==1078==    by 0x41F288: SERVER_sbuf2open (sbuf2.c:808)
==1078==    by 0x41B57B: portmux_cmd (portmuxusr.c:185)
==1078==    by 0x21079B: setup_net_listen_all (glue.c:5974)
==1078==    by 0x1C63AD: init (comdb2.c:3791)
==1078==    by 0x1B7139: main (comdb2.c:5570)
```

2023-07-14 14:21 UTC, akshatsikarwar commented
/silent

2023-07-14 14:23 UTC, mponomar submitted a review, later dismissed

2023-07-14 16:10 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2023-07-17 16:17 UTC, mponomar approved these changes

2023-07-18 13:31 UTC, merged