Disable seekscan optimization
bloomberg/comdb2 pull request #3911
Opened 2023-07-17 18:55 UTC by nirbhayc

2023-07-17 18:57 UTC, mponomar approved these changes

2023-07-17 19:59 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/482 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep<br>op_makerecord<br>transchunk_manyins<br>seekscan</p>

2023-07-17 22:47 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/482 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill_logput_window_generated<br>sc_truncate<br>phys_rep_tiered<br>queuedb_rollover_noroll1_generated</p>

2023-07-18 11:46 UTC, riverszhang89 approved these changes

2023-07-18 13:03 UTC, merged