Redirect spew to trc.c
bloomberg/comdb2 pull request #3915
Opened 2023-07-20 19:37 UTC by akshatsikarwar

/silent

2023-07-20 20:21 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2023-07-21 14:07 UTC, mponomar approved these changes

2023-07-21 15:21 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/483 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>cldeadlock<br>sc_truncate<br>sc_transactional_rowlocks_generated<br>queuedb_rollover<br>rep_blocker</p>

2023-07-21 17:55 UTC, nirbhayc approved these changes

2023-07-21 18:02 UTC, mponomar approved these changes

2023-07-21 18:34 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/483 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover</p>

2023-07-24 13:12 UTC, merged