Fixing use of dbstore CURRENT_TIMESTAMP
bloomberg/comdb2 pull request #3925
Opened 2023-07-27 17:28 UTC by riverszhang89

#3873 does not handle `dbstore=CURRENT_TIMESTAMP`. This patch completes it.

2023-07-27 17:57 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2023-07-27 18:07 UTC, chands10 approved these changes

2023-07-27 20:13 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2023-07-31 12:34 UTC, riverszhang89 commented
@chands10 Thanks for the review, Salil!

2023-07-31 12:34 UTC, merged