Physrep: Add a tunable that marks replication metadb
bloomberg/comdb2 pull request #3929
Opened 2023-07-28 15:59 UTC by nirbhayc

This tunable is needed to internally differentiate a replication metadb node from a source node.

This patch also addresses the following issues:
* Fix the logic to query the right comdb2db when populating the list of source cluster members
* Fix cluster member list begin sent to metadb, use nodes from the sanctioned list
* Forbid replicated cluster nodes from inserting dummy records (suppresses a warning)
* Expose more tunables to tweak 'reverse connections' logic
* Remove an incorrect placement of cdb2_close()

2023-07-28 16:10 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2023-07-28 18:16 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/485 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>sc_timepart_logicalsc_generated<br>analyze_partial_index_off_generated<br>analyze<br>analyze_sample</p>

2023-07-31 17:52 UTC, markhannum submitted a review, later dismissed

2023-07-31 18:28 UTC, markhannum approved these changes

2023-07-31 18:33 UTC, merged