support for bound parameters in fdb push (no datetime yet and byte array
bloomberg/comdb2 pull request #3966
Opened 2023-08-29 18:58 UTC by dorinhogea

Quick patch for performance testing.  Will follow-up with support for datetime and intervals.

2023-08-30 18:28 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>125/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>systable_locking<br>queuedb_rollover<br>writes_remsql_names_partial_index_off_generated<br>writes_remsql_names_negativerowid_generated<br>writes_remsql_names<br>ssl_remsql<br>sc_remsql_fdbpush_generated<br>remsql<br>fdb_push<br>load_remsql</p>

2023-08-31 17:07 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep<br>queuedb_rollover</p>

2023-09-01 13:13 UTC, mponomar approved these changes

2023-09-01 13:25 UTC, dorinhogea commented
Thank you Mike!

2023-09-01 13:25 UTC, merged