RDSICOMDB2-280: pmux secure port routing
bloomberg/comdb2 pull request #3970
Opened 2023-09-02 01:27 UTC by riverszhang89

In addition to routing connections to databases on 5105, listen on an additional port. Connections on this port should be routed to databases just like 5105, except:

1) They must be TLS-enabled
2) They must have a valid IAM token
3) Database must have IAM enabled

2023-09-02 16:39 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/488 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>prepare</p>

2024-02-28 17:59 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>6/521 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart<br>sc_truncate<br>systable_locking<br>queuedb_rollover_noroll1_generated<br>sc_repeated_updates<br>truncatesc_ufid_on_generated</p>

2024-05-08 14:14 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/533 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated<br>schemalk<br>schemalk_extralock_generated<br>queuedb_rollover_noroll1_generated<br>truncatesc_offline_generated<br>comdb2sys_queueodh_generated<br>comdb2sys<br>comdb2sys_pagesize_generated</p>

2024-05-08 15:40 UTC, riverszhang89 commented
`cdb2test   May  8 10:10:51 2024  in-comdb2db auth2.R20240508.2`

2024-05-09 13:41 UTC, mohitkhullar approved these changes
lgtm

2024-05-09 13:42 UTC, riverszhang89 commented
@mohitkhullar Thanks for the review!

2024-05-09 13:42 UTC, merged