Allow cdb2api policy configuration
bloomberg/comdb2 pull request #3974
Opened 2023-09-05 15:08 UTC by morgando

The changes in this PR provide database operators with a command that allows them to dynamically configure the cdb2api policy used when pushing a query to a foreign db.

The command takes the form `set_cdb2api_policy <policy>`, where `policy` can be one of 'random' (for CDB2_RANDOM), 'random_room' (for CDB2_RANDOMROOM), or 'room' (for CDB2_ROOM).

2023-09-05 17:21 UTC, markhannum approved these changes

2023-09-05 18:05 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>systable_locking<br>sc_truncate<br>sc_redo<br>sc_transactional_rowlocks_generated<br>lostwrite<br>transchunk_manyins</p>

2023-09-05 19:15 UTC, morgando commented
/runtests

2023-09-05 19:16 UTC, morgando commented
/runtests

2023-09-06 13:18 UTC, dorinhogea submitted a review, later dismissed
Looks good to me, thank you!

2023-09-06 14:34 UTC, morgando commented
/runtests

2023-09-06 20:26 UTC, aakash10292 submitted a review, later dismissed

2023-09-06 20:50 UTC, aakash10292 approved these changes

2023-09-06 20:50 UTC, merged