slowing down retries when remsql hits incoherent nodes with a dynamic backoff
bloomberg/comdb2 pull request #3978
Opened 2023-09-05 18:16 UTC by dorinhogea

Port https://github.com/bloomberg/comdb2/pull/3977 to main branch

2023-09-05 18:21 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2023-09-06 01:13 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>sc_transactional_rowlocks_generated<br>queuedb_rollover<br>queuedb_rollover_noroll1_generated<br>sc_timepart_logicalsc_generated<br>prepare<br>tunables<br>incoh_remsql</p>

2023-09-06 12:55 UTC, markhannum submitted a review, later dismissed

2023-09-06 13:32 UTC, markhannum approved these changes

2023-09-06 13:37 UTC, dorinhogea commented
Thank you Mark!

2023-09-06 13:38 UTC, merged