replace thread based fdb heartbeats with libevent
bloomberg/comdb2 pull request #3993
Opened 2023-09-14 16:54 UTC by dorinhogea

8.0 timeouts when longer sql runs during a cross-db transaction.  This adds libevent heartbeats to prevent it.

2023-09-14 16:55 UTC, roborivers reviewed
Lint check:

```diff


@@ net/net_evbuffer.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-09-14 17:55 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>6/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>phys_rep<br>phys_rep_tiered<br>queuedb_rollover_noroll1_generated<br>simple_timepart_reptimeout_generated<br>sys_cmd_access</p>

2023-09-28 14:51 UTC, roborivers reviewed
Lint check:

```diff


@@ net/net_evbuffer.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-09-28 15:54 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>4/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>legacy_defaults [setup core dumped]<br>sc_transactional_rowlocks_generated<br>phys_rep_tiered<br>analyze_exit_immediately</p>

2023-10-02 18:19 UTC, akshatsikarwar approved these changes

2023-10-02 18:19 UTC, merged