Compress/Uncompress functions
bloomberg/comdb2 pull request #4003
Opened 2023-09-20 15:57 UTC by nirbhayc

2023-09-21 20:50 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_tiered<br>prepare<br>auth_twofiles_generated<br>auth_queueodh_generated<br>auth<br>transchunk_manyins<br>tunables</p>

2023-09-22 14:53 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>phys_rep_tiered<br>queuedb_rollover<br>tunables</p>

2024-02-27 16:01 UTC, mponomar approved these changes

2024-02-27 17:36 UTC, closed without merging

2024-02-27 17:39 UTC, nirbhayc commented
This was a bit old. Re-opend as https://github.com/bloomberg/comdb2/pull/4243.