newsql: Support for old APIs
bloomberg/comdb2 pull request #4005
Opened 2023-09-21 14:52 UTC by nirbhayc

2023-09-21 14:56 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

2023-09-21 21:48 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>sc_transactional_rowlocks_generated<br>phys_rep_tiered<br>queuedb_rollover_noroll1_generated<br>tunables</p>

2023-10-05 18:56 UTC, mponomar submitted a review, later dismissed

2023-10-06 14:04 UTC, mponomar approved these changes

2023-10-06 14:10 UTC, merged