{173158536}: Fixing catchup
bloomberg/comdb2 pull request #4022
Opened 2023-10-06 17:11 UTC by riverszhang89

The ALL_REQ dedup counters are reset on repdb-truncation and REP_VOTE1 to allow replication to proceed. The chances of the ALL_REQ storm are further reduced, as well.

2023-10-06 17:16 UTC, roborivers reviewed
Lint check:

```diff


@@ berkdb/rep/rep_record.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-10-06 18:19 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>5/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>phys_rep_tiered<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>tunables</p>

2023-10-10 12:20 UTC, markhannum approved these changes

2023-10-10 12:20 UTC, riverszhang89 commented
@markhannum thanks for the review!

2023-10-10 12:20 UTC, merged