nested bdb_thread_event calls, only last frees
bloomberg/comdb2 pull request #4032
Opened 2023-10-12 15:39 UTC by dorinhogea

Trace:
"delete_thread_lock_info: thread stop before init!" 
(shows on LOGMSG_WARN level).
There are cases when we acquire first the bdb lock in read mode, and later on we switch to write mode.  Each call prepares the call tracing info by calling bdb_thread_event, and frees the tracing with a secondary call.
When calls are nested, the second free call believes the thread was never initialized.
The patch is tracking and freeing the locking tracing structure on the last release call.

2023-10-12 17:15 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>systable_locking<br>sc_truncate<br>phys_rep<br>phys_rep_tiered<br>queuedb_rollover<br>sp_snapshot_generated</p>

2023-10-30 15:57 UTC, markhannum commented on bdb/bdblock.c
> +         */
Should this decrement lk->callers?

2023-10-30 16:19 UTC, dorinhogea commented on bdb/bdblock.c
> +         */
duh, fixed that

2023-10-30 17:35 UTC, markhannum approved these changes

2023-10-30 18:18 UTC, dorinhogea commented
Thank you Mark!

2023-10-30 18:18 UTC, merged