Adding test for the views_lk issue
bloomberg/comdb2 pull request #4039
Opened 2023-10-16 19:11 UTC by riverszhang89

This patch adds a test which would reproduce the views_lk issue without the ez-systable rewriting for comdb2_columns.

2023-10-16 20:23 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover_noroll1_generated<br>queuedb_rollover</p>

2023-10-17 13:38 UTC, akshatsikarwar approved these changes

2023-10-17 13:38 UTC, akshatsikarwar commented
Thank you @riverszhang89

2023-10-17 13:42 UTC, riverszhang89 commented
@akshatsikarwar Thanks for the review!

2023-10-17 13:42 UTC, merged