add limit for how many parallel schema changes we can have on a partition
bloomberg/comdb2 pull request #4040
Opened 2023-10-17 14:03 UTC by dorinhogea

In addition to existing limit for parallel doh sql executions for partitions, we also have to limit the amount of parallel schema changes we generate.

2023-10-17 14:06 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2023-10-17 15:20 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>phys_rep_tiered<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>systable_locking</p>

2023-10-19 14:39 UTC, mponomar approved these changes

2023-10-19 14:46 UTC, dorinhogea commented
Thank you Mike!

2023-10-19 14:46 UTC, merged