Fixing typo in test
bloomberg/comdb2 pull request #4041
Opened 2023-10-18 14:30 UTC by riverszhang89

An incomplete DDL statement causes the systable_locking test to time out. This patch fixes it.

2023-10-18 14:52 UTC, akshatsikarwar submitted a review, later dismissed

2023-10-18 15:41 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>6/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>systable_locking<br>sc_truncate<br>phys_rep<br>phys_rep_tiered<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover</p>

2023-10-18 20:09 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_tiered<br>sc_timepart<br>lostwrite<br>systable_locking</p>

2023-10-18 20:12 UTC, chands10 commented
ughh

2023-10-18 20:13 UTC, akshatsikarwar commented
ughhh

2023-10-18 23:30 UTC, riverszhang89 commented
"I swear it works on my machine!"

2023-10-18 23:58 UTC, riverszhang89 commented
/cbuild-compile-only

2023-10-19 00:59 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_tiered<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover</p>

2023-10-19 13:29 UTC, akshatsikarwar approved these changes

2023-10-19 13:34 UTC, riverszhang89 commented
@akshatsikarwar Thanks for the review!

2023-10-19 13:34 UTC, merged