{173263890}: Speeding up logc->get(DB_FIRST)
bloomberg/comdb2 pull request #4042
Opened 2023-10-18 14:31 UTC by riverszhang89

This patch adds a simple cache inside the berkdb layer to avoid opening and reading all log files for every `logc->get(DB_FIRST)` call.

The blkseq code is also tweaked to avoid blocking replication while getting the very first log record.

2023-10-18 15:53 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>phys_rep_tiered<br>systable_locking</p>

2023-10-25 18:53 UTC, markhannum approved these changes
Looks great!

2023-10-30 12:06 UTC, roborivers reviewed
Lint check:

```diff


@@ berkdb/log/log.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ bdb/bdb_blkseq.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-10-31 11:36 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>488/488 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>truncatesc [setup failure]<br>maxtable [setup failure]<br>sirace [setup failure]<br>systable_locking [setup failure]<br>verify_writes [setup failure]<br>incremental_backup_load [setup failure]<br>socksql_master_swings [setup failure]<br>rebuild_table_options [setup failure]<br>cldeadlock [setup failure]<br>sc_force [setup failure]</p>

2023-11-01 20:01 UTC, roborivers reviewed
Lint check:

```diff


@@ berkdb/log/log.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ bdb/bdb_blkseq.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-11-02 14:34 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>402/488 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>systable_locking<br>logfill<br>scindex<br>phys_rep_tiered<br>sc_resume_logicalsc_generated<br>sc_resume<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>truncatesc<br>truncatesc_ufid_on_generated</p>

2023-11-03 19:46 UTC, roborivers reviewed
Lint check:

```diff


@@ berkdb/log/log.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ bdb/bdb_blkseq.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-11-03 20:51 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>252/508 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>systable_locking<br>scindex<br>phys_rep_tiered<br>sc_resume_logicalsc_generated<br>sc_resume<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>truncatesc<br>truncatesc_ufid_on_generated<br>logarchive</p>

2023-11-06 18:26 UTC, roborivers reviewed
Lint check:

```diff


@@ berkdb/log/log.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ bdb/bdb_blkseq.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-11-06 19:32 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/509 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>scindex<br>phys_rep_tiered<br>sc_resume_logicalsc_generated<br>sc_resume<br>queuedb_rollover_noroll1_generated</p>

2024-02-05 18:29 UTC, markhannum approved these changes

2024-02-05 18:58 UTC, markhannum approved these changes

2024-02-05 18:59 UTC, riverszhang89 commented
@markhannum Thanks for the review, Mark!

2024-02-05 18:59 UTC, merged