{173291085}: Reducing memory footprint of cascading transaction
bloomberg/comdb2 pull request #4046
Opened 2023-10-20 21:11 UTC by riverszhang89

The `list` type of temp-table, used by the constraints subsystem, is incapable of spilling to the disk. This patch changes it to use btree-backed temp-tables. Since the constraints subsystem is the only user of the `temp-list`, the patch gets rid of the implementation all together.

2023-10-20 22:43 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_tiered<br>queuedb_rollover_noroll1_generated<br>constraints_noreorder_generated<br>constraints_partial_index_off_generated<br>constraints<br>ddl_no_csc2</p>

2023-10-25 16:16 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_tiered<br>queuedb_rollover</p>

2023-10-30 14:59 UTC, mponomar approved these changes

2023-10-30 15:04 UTC, riverszhang89 commented
@mponomar Thanks for the review!

2023-10-30 15:04 UTC, merged