Fixing incorrect rcode in longreqs
bloomberg/comdb2 pull request #4047
Opened 2023-10-20 21:12 UTC by riverszhang89

reqlog may log a good rcode for an error. The example below shows that a failed query is recorded with a "rc 0" in the longreqs.

```
osql_sock_commit line 1066 setting rcout to (210) from -6
LONG REQUEST (240025 ms) finished (see mydb.longreqs for details)

10/20 14:03:57: LONG REQUEST 240025 msec for fingerprint 4c9553ff0390f309285ce1e210f7457e pid 236623 task cdb2sql rqid 74d1c790-03b0-422f-9750-a65b1f2eaade from localhost rc 0
```

This patch fixes it.

2023-10-20 23:53 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>456/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>sirace<br>serial_randtest2<br>sicountbug<br>sc_force<br>maxtable<br>phys_rep_tiered<br>selectv_deadlock<br>sc_constraints<br>sc_constraints_logicalsc_generated</p>

2023-10-23 14:36 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>461/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>systable_locking<br>sirace<br>serial_randtest2<br>sicountbug<br>sc_force<br>maxtable<br>phys_rep_tiered<br>selectv_deadlock<br>sc_constraints</p>

2023-10-23 16:10 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>queuedb_rollover</p>

2023-10-23 17:33 UTC, nirbhayc approved these changes
Looks good.

2023-10-23 19:06 UTC, riverszhang89 commented
@nirbhayc Thanks for the review!

2023-10-23 19:06 UTC, merged