2pc review
bloomberg/comdb2 pull request #4084
Opened 2023-11-13 14:21 UTC by markhannum

Logic for 2-phased commit

2023-11-13 14:26 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/txn/txn_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlsession.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/disttxn.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlblockproc.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-11-13 15:21 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2023-11-13 23:46 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/txn/txn_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlsession.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/disttxn.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlblockproc.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-11-14 00:50 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2023-11-14 12:31 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/txn/txn_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlsession.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/disttxn.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlblockproc.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-11-14 13:57 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/511 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>sc_resume<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>lostwrite<br>dupewrite<br>cdb2api_2pc<br>tunables</p>

2023-11-16 16:51 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/txn/txn_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlsession.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/disttxn.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlblockproc.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-11-16 18:36 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>10/511 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>sc_transactional_rowlocks_generated<br>scindex<br>phys_rep_tiered<br>sc_resume_logicalsc_generated<br>sc_resume<br>queuedb_rollover<br>queuedb_rollover_noroll1_generated<br>dupewrite<br>cdb2api_2pc</p>

2023-11-16 19:31 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/txn/txn_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlsession.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/disttxn.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlblockproc.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-11-16 21:20 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>162/511 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>sc_transactional_rowlocks_generated<br>scindex<br>phys_rep_tiered<br>sc_resume_logicalsc_generated<br>sc_resume<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>sp<br>dupewrite</p>

2023-11-17 14:26 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/txn/txn_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlsession.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/disttxn.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlblockproc.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-11-17 15:37 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/511 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>2pc<br>sc_resume_logicalsc_generated<br>sc_resume<br>queuedb_rollover<br>dupewrite</p>

2023-11-17 17:46 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/511 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>phys_rep<br>scindex<br>phys_rep_tiered<br>sc_resume_logicalsc_generated<br>sc_resume<br>queuedb_rollover_noroll1_generated<br>dupewrite</p>

2023-11-17 19:26 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/txn/txn_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlsession.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/disttxn.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlblockproc.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-11-17 20:49 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/511 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>phys_rep<br>scindex<br>phys_rep_tiered<br>sc_resume_logicalsc_generated<br>sc_resume<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>dupewrite</p>

2023-11-29 13:11 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/txn/txn_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ bdb/rep.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlsession.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/disttxn.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlblockproc.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-11-29 14:37 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/512 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>phys_rep_tiered<br>queuedb_rollover_noroll1_generated<br>dupewrite<br>tunables</p>

2023-11-29 16:56 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/txn/txn_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ bdb/rep.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlsession.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/disttxn.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlblockproc.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-11-29 18:18 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/512 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>cldeadlock<br>dupewrite</p>

2023-12-15 15:41 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/txn/txn_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ bdb/rep.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlsession.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/disttxn.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlblockproc.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/toblock.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-12-15 16:55 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/513 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>2pc<br>scindex<br>queuedb_rollover_noroll1_generated<br>incoherent_slow<br>dupewrite</p>

2023-12-15 18:56 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/txn/txn_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ bdb/rep.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlsession.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/disttxn.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlblockproc.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/toblock.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2023-12-15 19:46 UTC, riverszhang89 approved these changes

2023-12-15 19:46 UTC, riverszhang89 commented on db/toblock.c
> +                                    if (iq->sorese->is_coordinator) {
note to myself- The "wait-for-propagation" logic is here

2023-12-15 19:46 UTC, riverszhang89 commented on db/toblock.c
> +                                    irc = trans_commit_adaptive(iq, parent_trans, source_host);
note to myself - commit here

2023-12-15 19:46 UTC, riverszhang89 commented on db/disttxn.c
> +            commit_participants_lk(dtran);
note to myself- now tell participants to commit

2023-12-15 19:46 UTC, riverszhang89 commented on db/sltdbt.c
> +        dispatch_participants(iq->sorese->dist_txnid);
note to myself - prepare here

2023-12-15 20:00 UTC, riverszhang89 approved these changes
Looks good to merge!

Do records in comdb2_distributed_transactions get deleted? Maybe we can extend the table with an "lsn-file" field, that records the current logfile, and then log-delete code can also delete records in this table if they're past MIN_KEEP_LOGS.

2023-12-15 20:07 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/513 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>cldeadlock<br>sc_truncate_lockorder_generated<br>dupewrite</p>

2023-12-18 20:47 UTC, riverszhang89 approved these changes

2023-12-19 10:06 UTC, merged