Verify prev_lsn before logc->get in recover_blkseq
bloomberg/comdb2 pull request #4087
Opened 2023-11-14 21:37 UTC by markhannum

Recover blkseq emits scary-looking trace when the previous-isn of a logical-commit is zero.  This can happen in snapshot isolation when the purge-old-files thread doesn't delete any files in its transaction.  This PR stops the trace by skipping the logc->get call for this case.

2023-11-14 21:50 UTC, morgando approved these changes

2023-11-14 22:50 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/509 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>phys_rep<br>phys_rep_tiered<br>sc_resume_logicalsc_generated<br>sc_resume<br>lostwrite</p>

2023-11-15 14:45 UTC, riverszhang89 commented on bdb/bdb_blkseq.c
> +                            rc = -1;
Do we need to continue here?

2023-11-15 14:49 UTC, riverszhang89 commented on bdb/bdb_blkseq.c
> +                            rc = -1;
This is okay, actually. rc is reset to 0 by the logc->get(DB_SET) call at the end of the loop, and we'll be able to continue the loop.

2023-11-15 14:49 UTC, riverszhang89 approved these changes

2023-11-15 16:47 UTC, merged