WIP Snapshot
bloomberg/comdb2 pull request #4100
Opened 2023-11-28 22:32 UTC by morgando

2023-11-28 23:42 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>9/512 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>serialstep [setup failure]<br>modsnap [setup failure]<br>sc_truncate<br>sc_transactional_rowlocks_generated<br>phys_rep<br>phys_rep_tiered<br>queuedb_rollover_noroll1_generated<br>tunables<br>prepare</p>

2024-02-29 19:59 UTC, morgando commented on berkdb/mp/mp_versioned.c
Versioned memory pool implementation.

**This is the meat and potatoes of this snapshot implementation**

2024-02-29 19:59 UTC, morgando commented on berkdb/txn/txn.c
Add child transactions to the commit map atomically with their parent. This is required for snapshot correctness.

2024-02-29 19:59 UTC, morgando commented on db/comdb2.c
Tunable definitions

2024-02-29 19:59 UTC, morgando commented on db/config.c
Disables modsnap in legacy_options.

2024-02-29 19:59 UTC, morgando commented on db/db_metrics.c
Add snapshot metrics (TODO)

2024-02-29 19:59 UTC, morgando commented on db/db_tunables.h
Tunable declarations.

2024-02-29 19:59 UTC, morgando commented on db/fdb_bend.c
Add `TRANLEVEL_MODSNAP` as a valid isolation level.

2024-02-29 19:59 UTC, morgando commented on db/glue.c
Add start function for modsnap

2024-02-29 19:59 UTC, morgando commented on db/osql_srs.c
High level isolation level specific logic (check this)

2024-02-29 19:59 UTC, morgando commented on db/osqlshadtbl.c
Tell `bdb_cursor_open` if it should open a snapshot cursor or not.

2024-02-29 19:59 UTC, morgando commented on db/osqlsqlthr.c
High level isolation level specific logic (check this)

2024-02-29 19:59 UTC, morgando commented on db/sql.h
1. Adds TRANLEVEL_MODSNAP to transaction_level enum 
2. Adds members to clnt for latching snapshot state

2024-02-29 19:59 UTC, morgando commented on berkdb/db/db_cam.c
1. Makes a duplicate cursor a snapshot cursor if the original cursor is a snapshot cursor.
2. Replaces memp_fget with PAGEGET and memp_fput with PAGEPUT

2024-02-29 19:59 UTC, morgando commented on berkdb/build/db_int.h
Defines PAGEGET and PAGEPUT macros

2024-02-29 19:59 UTC, morgando commented on berkdb/btree/bt_split.c
All of the changes in this file are related to replacing memp_fget with PAGEGET and memp_fput with PAGEPUT

2024-02-29 19:59 UTC, morgando commented on berkdb/btree/bt_rsearch.c
All of the changes in this file are related to replacing memp_fget with PAGEGET and memp_fput with PAGEPUT

2024-02-29 19:59 UTC, morgando commented on berkdb/btree/bt_snaprec.c
Snapshot uses these functions to rollback pages. These functions depend on the refactor done in [https://github.com/bloomberg/comdb2/pull/4179](https://github.com/bloomberg/comdb2/pull/4179)

2024-02-29 19:59 UTC, morgando commented on berkdb/btree/bt_rec.c
Refactor of recovery functions. Review here: [https://github.com/bloomberg/comdb2/pull/4179](https://github.com/bloomberg/comdb2/pull/4179)

2024-02-29 19:59 UTC, morgando commented on berkdb/btree/bt_curadj.c
Skip adjustments on snapshot cursors. Snapshot cursors should not be adjusted because they are always looking at independent page images. (what about duplicate cursors? Is the dbt copied or does the dup call mempfget)

2024-02-29 19:59 UTC, morgando commented on berkdb/btree/bt_compare.c
All of the changes in this file are related to replacing memp_fget with PAGEGET and memp_fput with PAGEPUT

2024-02-29 19:59 UTC, morgando commented on bdb/fetch.c
Make a cursor created from a parent a snapshot cursor if the parent is a snapshot cursor.

2024-02-29 19:59 UTC, morgando commented on bdb/cursor_ll.c
Set snapshot state in cursor.

2024-02-29 19:59 UTC, morgando commented on bdb/cursor.c
Set snapshot state in cursor.

2024-02-29 19:59 UTC, morgando commented on berkdb/btree/bt_recno.c
Skip adjustments on snapshot cursors. Snapshot cursors should not be adjusted because they are always looking at independent page images. (what about duplicate cursors? Is the dbt copied or does the dup call mempfget)

2024-02-29 19:59 UTC, morgando commented on berkdb/btree/bt_put.c
(TODO) All of the changes in this file are related to replacing memp_fget with PAGEGET and memp_fput with PAGEPUT

2024-02-29 19:59 UTC, morgando commented on bdb/bdb_osqlcur.c
Add `TRANCLASS_MODSNAP` to recognized transaction modes.

2024-03-01 16:54 UTC, morgando commented on db/sqlglue.c
High level isolation level specific logic (check this)

2024-03-01 16:54 UTC, morgando commented on db/sqlinterfaces.c
High level isolation level specific logic (check this)

2024-03-01 16:54 UTC, morgando commented on db/sqlinterfaces.c
>          return "TRANLEVEL_RECOM";
TODO

2024-03-01 16:54 UTC, morgando commented on db/sqloffload.c
High level isolation level specific logic (check this)

2024-03-01 16:54 UTC, morgando commented on plugins/newsql/newsql.c
> -                                                 "high availability\n");
TODO add log

2024-03-01 16:54 UTC, morgando commented on plugins/remsql/fdb_comm.c
>          return "RECOM";
TODO

2024-03-01 19:45 UTC, morgando commented on db/sqlglue.c
> +	    &thedb->static_table; /* this is not used but required */
TODO remove comment

2024-03-01 22:50 UTC, morgando commented on berkdb/mp/mp_vcache.c
> +static int num_cached_pages = 0; // TODO: make this per cache
TODO

2024-03-04 19:22 UTC, morgando commented on db/sqlinterfaces.c
> +        return !clnt->sent_data_to_client; // TODO
TODO: support `gbl_snapshot_serial_verify_retry`

2024-03-04 19:22 UTC, morgando commented on db/sqlinterfaces.c
> +        return 1; // TODO
TODO: support `gbl_snapshot_serial_verify_retry`

2024-03-04 21:29 UTC, morgando commented on bdb/bdb_int.h
> +    DB_LSN highest_ckpt_commit_lsn;
TODO: Rename

2024-03-04 21:29 UTC, morgando commented on bdb/cursor.c
> +    DB_LSN highest_ckpt_commit_lsn;
TODO: Rename

2024-03-04 21:30 UTC, morgando commented on db/sql.h
> +    u_int32_t highest_ckpt_commit_lsn_offset;
TODO: Rename

2024-03-05 18:39 UTC, morgando commented on berkdb/env/env_open.c
> +	__mempv_destroy(dbenv);
Free list of outstanding modsnaps. free outstanding modsnap lock.

2024-03-05 18:40 UTC, morgando commented on berkdb/mp/mp_versioned.c
> +	return 1;
Destroy cache and mempv

2024-03-20 18:37 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ berkdb/rep/rep_record.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/txn/txn_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/txn/txn.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/mp/mp_versioned.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/mp/mp_sync.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ bdb/cursor.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ bdb/tran.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/mp/mp_vcache.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
@@ bdb/tran.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2024-03-20 19:41 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/523 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>sc_transactional_rowlocks_generated<br>queuedb_rollover</p>

2024-04-29 18:49 UTC, morgando commented
/runtests

2024-04-30 13:16 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ berkdb/rep/rep_record.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/txn/txn_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/txn/txn.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/mp/mp_versioned.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/mp/mp_vcache.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/mp/mp_sync.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ bdb/cursor.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ bdb/tran.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/mp/mp_vcache.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
@@ bdb/tran.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2024-04-30 14:27 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>420/532 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume<br>truncatesc<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>yast_stat4scan_generated<br>yast<br>analyze_recover_deadlock<br>autoanalyze<br>analyze_partial_index_off_generated<br>analyze</p>

2024-05-02 19:13 UTC, mponomar approved these changes

2024-05-02 19:31 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ berkdb/rep/rep_record.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/txn/txn_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/txn/txn.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/mp/mp_versioned.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/mp/mp_vcache.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/mp/mp_sync.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ bdb/cursor.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ bdb/tran.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/mp/mp_vcache.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
@@ bdb/tran.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2024-05-02 22:06 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/532 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>logfill<br>sc_downgrade<br>truncatesc<br>truncatesc_offline_generated<br>comdb2sys_queueodh_generated<br>comdb2sys_pagesize_generated<br>comdb2sys</p>

2024-05-03 00:46 UTC, merged