need to disable live sc upon error before freeing stuff; 173695058
bloomberg/comdb2 pull request #4117
Opened 2023-12-07 17:11 UTC by dorinhogea

173695058; live_sc_off is not called until too late, at which point schema changes are freed and concurrent live writes crash

2023-12-07 18:20 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/510 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>incoh_remsql [setup failure]<br>sc_truncate<br>sc_resume_logicalsc_generated<br>sc_resume<br>queuedb_rollover_noroll1_generated</p>

2023-12-07 18:45 UTC, mponomar submitted a review, later dismissed

2023-12-12 15:35 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/510 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>sc_resume<br>scindex<br>queuedb_rollover</p>

2023-12-12 22:24 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/510 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional<br>sc_transactional_rowlocks_generated<br>scindex<br>queuedb_rollover_noroll1_generated</p>

2023-12-13 17:09 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/510 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover</p>

2023-12-13 17:40 UTC, mponomar approved these changes

2023-12-13 17:53 UTC, dorinhogea commented
@mponomar thank you!

2023-12-13 17:53 UTC, merged