cdb2jdbc: adding identity callback
bloomberg/comdb2 pull request #4123
Opened 2023-12-12 16:47 UTC by riverszhang89

Changes needed to integrate IAM into cdb2jdbc.

2023-12-12 16:47 UTC, riverszhang89 commented
/skipbuild

2023-12-22 16:14 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/513 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>cdb2api_2pc [setup failure]<br>logfill_logput_window_generated<br>sc_truncate_lockorder_generated<br>sc_truncate<br>sc_transactional<br>maxtable<br>simple_timepart_reptimeout_generated<br>dupewrite</p>

2024-01-05 18:51 UTC, markhannum approved these changes

2024-01-12 15:41 UTC, riverszhang89 commented
@markhannum Thanks for the review!

2024-01-12 15:41 UTC, merged