Fix check constraint failure for blobs (WIP)
bloomberg/comdb2 pull request #4128
Opened 2023-12-15 02:20 UTC by nirbhayc

2023-12-15 03:24 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/511 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>scindex<br>queuedb_rollover_noroll1_generated</p>

2023-12-18 22:31 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/511 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>sc_transactional_rowlocks_generated<br>scindex</p>

2023-12-20 14:53 UTC, riverszhang89 approved these changes

2023-12-20 15:39 UTC, merged

2023-12-20 15:39 UTC, nirbhayc commented
Thanks @riverszhang89!