Only add DB_AM_RECOVER to ufid-hash, enable ufid-logging by default
bloomberg/comdb2 pull request #4132
Opened 2023-12-18 20:44 UTC by markhannum

Only allow DB_AM_RECOVER dbps to be added to the ufid-hash.

2023-12-18 20:45 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2023-12-18 21:51 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/511 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>sc_transactional_rowlocks_generated<br>scindex<br>queuedb_rollover_noroll1_generated<br>prepare<br>sc_downgrade</p>

2023-12-19 14:56 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2023-12-19 16:06 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/513 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>delfile_block_reproleak_generated<br>sirandtest<br>queuedb_rollover<br>prepare<br>dupewrite<br>sc_truncate_lockorder_generated</p>

2023-12-29 19:07 UTC, riverszhang89 approved these changes

2023-12-29 21:36 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2023-12-29 22:54 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/513 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>prepare<br>dupewrite<br>ddl_no_csc2</p>

2024-01-02 13:35 UTC, merged