{173891382}: Capturing remote queries and their fingerprints
bloomberg/comdb2 pull request #4137
Opened 2023-12-29 17:31 UTC by riverszhang89

Signed-off-by: Rivers Zhang <hzhang320@bloomberg.net>

2023-12-29 18:44 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/513 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>schemalk_extralock_generated<br>sc_transactional_rowlocks_generated<br>ioerror_remsql<br>ioerror_remsql_fdbpush_generated<br>incremental_backup_usenames<br>queuedb_rollover<br>dupewrite<br>remsql<br>ddl_no_csc2</p>

2024-01-05 16:43 UTC, markhannum submitted a review, later dismissed

2024-01-12 17:10 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/511 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>ioerror_remsql_fdbpushredirect_generated<br>ioerror_remsql_fdbpush_generated<br>ioerror_remsql<br>queuedb_rollover<br>prepare<br>transchunk_manyins<br>remsql</p>

2024-01-12 22:01 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/511 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>ioerror_remsql_fdbpushredirect_generated<br>ioerror_remsql<br>ioerror_remsql_fdbpush_generated<br>prepare<br>remsql</p>

2024-02-27 14:12 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/520 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ioerror_remsql_fdbpushredirect_generated<br>ioerror_remsql_fdbpush_generated<br>ioerror_remsql<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>prepare<br>remsql</p>

2024-02-27 15:59 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>5/520 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>delfile_block [setup failure]<br>sc_timepart_logicalsc_generated<br>sc_timepart<br>queuedb_rollover_noroll1_generated<br>prepare</p>

2024-02-27 20:36 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/520 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>delfile_block [setup failure]<br>sc_timepart_logicalsc_generated<br>sc_truncate<br>queuedb_rollover_noroll1_generated<br>truncatesc</p>

2024-02-28 14:11 UTC, riverszhang89 commented
passing rm: cdb2test   Feb 27 15:26:00 2024  in-comdb2db fingerprint_fdb.R20240227.11

2024-02-28 14:32 UTC, dorinhogea approved these changes
looks good to me, thank you!

2024-02-28 14:33 UTC, merged