dbs_idx is used only for writes reordering; simplify
bloomberg/comdb2 pull request #4149
Opened 2024-01-08 20:38 UTC by dorinhogea

NOTE: reordering writes on master based on table name could be done without the need to use a table index value.  Eliminating a bunch of confusing code and set dbs_idx upon indexing in thedb table array only.

2024-01-08 21:38 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/511 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover_noroll1_generated<br>prepare<br>constraints_partial_index_off_generated<br>constraints<br>constraints_noreorder_generated<br>sc_transactional_rowlocks_generated<br>sc_transactional_logicalsc_generated<br>sc_transactional<br>ddl_no_csc2</p>

2024-01-10 16:18 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/511 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>cldeadlock<br>sc_transactional_rowlocks_generated<br>queuedb_rollover_noroll1_generated<br>prepare<br>ddl_no_csc2<br>basic_nolibevent_generated</p>

2024-01-11 19:24 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/511 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>prepare<br>ddl_no_csc2</p>

2024-01-17 15:31 UTC, mponomar approved these changes

2024-01-17 17:20 UTC, dorinhogea commented
@mponomar thank you!

2024-01-17 17:20 UTC, merged