reuse field to remove an extra sc member
bloomberg/comdb2 pull request #4151
Opened 2024-01-10 15:44 UTC by dorinhogea

One less field  for sc (removing ADD table dedicated status); we already have "already_finalize" that is used with the other sc types.

2024-01-10 16:57 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-01-10 18:18 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>4/511 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional<br>queuedb_rollover<br>prepare<br>ddl_no_csc2</p>

2024-01-11 17:49 UTC, akshatsikarwar approved these changes

2024-01-11 17:54 UTC, dorinhogea commented
@akshatsikarwar thank you!

2024-01-11 17:54 UTC, merged