Don't recover on replicant if we don't unwind any txns
bloomberg/comdb2 pull request #4163
Opened 2024-01-19 16:59 UTC by markhannum

It turns out running recovery on the replicant is unnecessary in the vast majority of cases.  When 'rep_skip_recovery' is enabled, orderly downgrades (where the replicants are in-sync with the old master) cause none of the replicants to run recovery after syncing with the new master.  If the replicants are in-sync and the master crashes, replicants avoid recovery roughly 2/3rds of the time.

This is being submitted initially with 'rep_skip_recovery' enabled- I will disable prior to merge.

2024-01-19 17:01 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2024-01-19 18:05 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/512 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>delfile_block_reproleak_generated<br>sc_transactional<br>queuedb_rollover<br>lostwrite</p>

2024-01-19 18:46 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2024-01-19 19:48 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/512 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>tunables</p>

2024-01-23 13:38 UTC, riverszhang89 approved these changes
Looks good to merge!

2024-01-23 13:44 UTC, merged