{173871120}: Allowing cold-started replicants to participate in election
bloomberg/comdb2 pull request #4171
Opened 2024-01-24 19:48 UTC by riverszhang89

Currently replicants brought up afresh do not participate in election unless they are marked 'caught up' after the global bdb_env is initialized. However when half or more of the cluster are in this state, and the leader downgrades the cluster will then not be able to elect because of lack of quorum, as seen below

```
3333 2024/01/24 14:21:20 0x0x7fc1954f9700: calling for election with cluster of 3 nodes (3 connected) : c2btda-pw-053 c2btda-pw-928 c2btda-pw-922 ,  2.388000 secs timeout and priority 100
3343 2024/01/24 14:21:20 __rep_elect line 1453 not enough vote1s, failing
3344 2024/01/24 14:21:20 __rep_elect line 1533 ret is -30979
3345 2024/01/24 14:21:20 __rep_elect_done line 846 clearing PHASE1/PHASE2/TALLY, inelect is 1
3346 2024/01/24 14:21:20 __rep_elect_done called from __rep_elect line 1536
3347 2024/01/24 14:21:20 __rep_elect_done line 856 setting rep->egen from 168 to 169
3348 2024/01/24 14:21:20 __rep_elect line 1544 returning -30979 master .invalid egen is 168
3349 2024/01/24 14:21:20 failed to reach consensus in election with 2.388000 secs timeout. network timeout or received votes of a different egen

```

This patch gets rid of the 'caught-up' check. As long as a replicant is connected to the leader, and the leader requests election, the replicant should always respond to that request.

A new test electbug2 is added to reproduce this bug.

2024-01-24 20:02 UTC, riverszhang89 commented
We're seeing this issue more often than before because of the new db-copy process that brings up all copied nodes at once ...

2024-01-24 21:51 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/513 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>electbug2 [setup failure]<br>sc_truncate<br>sc_transactional_rowlocks_generated<br>queuedb_rollover<br>lostwrite<br>commit_lsn_map<br>truncatesc</p>

2024-01-26 16:35 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/134 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>electbug2 [setup failure]<br>queuedb_rollover_noroll1_generated</p>

2024-01-26 17:16 UTC, riverszhang89 commented
The `electbug2` test fails without this bug fix, as expected:

```
3716 2024/01/26 11:17:12 0x0x7fb56ace2700: calling for election with cluster of 3 nodes (3 connected) : m3 m2 m1 ,  6.152000 secs timeout and priority 100
3717 2024/01/26 11:17:12 thedb_set_master: .invalid -> .invalid
3718 2024/01/26 11:17:12 __rep_elect_init line 1600 setting master_id to .invalid
3719 2024/01/26 11:17:12 __rep_elect start sending master req
...
3728 2024/01/26 11:17:12 __rep_elect line 1453 not enough vote1s, failing
3729 2024/01/26 11:17:12 __rep_elect line 1533 ret is -30979
3730 2024/01/26 11:17:12 __rep_elect_done line 846 clearing PHASE1/PHASE2/TALLY, inelect is 1
3731 2024/01/26 11:17:12 __rep_elect_done called from __rep_elect line 1536
3732 2024/01/26 11:17:12 __rep_elect_done line 856 setting rep->egen from 188 to 189
3733 2024/01/26 11:17:12 __rep_elect line 1544 returning -30979 master .invalid egen is 188
3734 2024/01/26 11:17:12 failed to reach consensus in election with 6.152000 secs timeout. network timeout or received votes of a different egen
```

I'm putting the code back.

2024-01-26 17:17 UTC, riverszhang89 commented
```
cdb2test   Jan 25 07:32:49 2024  in-comdb2db elect.R20240125.0
```

2024-01-26 18:48 UTC, akshatsikarwar approved these changes

2024-01-26 18:49 UTC, merged