only generate index tag schemas for ONDISK and DEFAULT
bloomberg/comdb2 pull request #4172
Opened 2024-01-25 00:18 UTC by dorinhogea

Currently, for a schema like:
ondisk
{ 
int a
}
tag "t"
{
int a
}
keys
{
"a" = a
}
We generate tag schema for ONDISK_IX_0, but also for t_IX_0, which we do not use.  Patch removes the extra tag schemas.

2024-01-25 01:19 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/512 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>manual_partition_lgcy<br>lostwrite<br>prepare</p>

2024-01-25 05:31 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/512 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>delfile_block [setup failure]<br>sc_truncate<br>queuedb_rollover</p>

2024-01-26 17:05 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/512 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>prepare</p>

2024-01-26 18:45 UTC, mponomar approved these changes

2024-01-26 19:16 UTC, dorinhogea commented
@mponomar thank you!

2024-01-26 19:16 UTC, merged