clear table if comdb2sc add table fails after finalizing
bloomberg/comdb2 pull request #4178
Opened 2024-01-29 21:33 UTC by dorinhogea

Currently, issue reproduceable with comdb2sc, if an error is forced during mark_schemachange_over_tran() call in do_finalize() stage.  At this point a table is added to the list of tables, under global schema lock.   The ddl schema change common code (i.e. common with comdb2sc) does its job and abort the transaction, which removes all llmeta entries added during finalize_add_table().  But the legacy comdb2sc fails early and does not clear the in-memory table from the list of tables.
Everything goes unnoticed until a new schema change arrives and commits successfully.  Because we construct LLMETA_TABLES list of tables in llmeta based on the list of tables in memory, this commit wrongly adds the failed/non-persistent table to the list.  At this point the db is corrupted and cannot restart (unless ignore_bad_table lrl option is used).
Fix the comdb2sc add by clearing properly on error.

2024-01-29 23:06 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>427/513 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>timepart_retention1<br>timepart_auth<br>timepart_changeretention<br>simple_timepart_reptimeout_generated<br>simple_timepart<br>sc_timepart_logicalsc_generated<br>sc_timepart<br>queuedb_rollover<br>lostwrite<br>prepare</p>

2024-01-30 14:55 UTC, mponomar approved these changes

2024-01-30 15:39 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/513 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>delfile_block [setup failure]<br>sc_truncate<br>phys_rep_tiered<br>queuedb_rollover_noroll1_generated</p>

2024-01-30 15:53 UTC, dorinhogea commented
@mponomar thank you!

2024-01-30 15:53 UTC, merged