{174213508} Check for timer-thd liveness
bloomberg/comdb2 pull request #4185
Opened 2024-02-02 18:44 UTC by akshatsikarwar

/silent

2024-02-02 19:51 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/515 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite<br>pmux_sqlite_file_generated</p>

2024-02-02 21:37 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>4/515 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>delfile_block [setup failure]<br>queuedb_rollover<br>prepare<br>sc_downgrade</p>

2024-02-05 16:04 UTC, mponomar approved these changes

2024-02-05 16:29 UTC, merged

2024-02-05 17:13 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/515 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>selectv_rcode_serialretry_generated<br>queuedb_rollover_noroll1_generated<br>sc_downgrade</p>