set csc2_schema upon creation and remove a bunch of code while doing it
bloomberg/comdb2 pull request #4197
Opened 2024-02-06 21:08 UTC by dorinhogea

We can allocate csc2_schema when we create the dbtable, not randomly in various places.  This eliminates some redundant code.

2024-02-06 22:40 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-02-07 04:22 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-02-07 16:26 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>6/515 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>delfile_block [setup failure]<br>electbug2 [setup failure]<br>prepare<br>load_cache_autocache_generated<br>load_cache<br>sc_downgrade</p>

2024-02-07 20:41 UTC, dorinhogea commented
@mponomar thank you!

2024-02-07 20:42 UTC, merged