removing patch no longer needed to fix lrl and ixlens
bloomberg/comdb2 pull request #4211
Opened 2024-02-13 15:02 UTC by dorinhogea

With the recent restructuring in schema change code, we consolidated the creation of a dbtable in a single function.   It is reasonable to set dbtable structure fields at the creation time, if possible.
One of these fields are the length of ondisk row (lrl) and indexes (ix_keylen).  The lengths are different than the sum of the field value lengths, as provided by the csc2 parser, and a conversion is required (as done by fix_lrl_ixlen function in the past).  With the consolidation, we have this conversion done at the time when the dbtable is created.
Another field of dbtable is a cache of csc2 schema (csc2_schema), which is also stored at the time of dbtable creation, instead of being read later on from llmeta.
This structural change has a few benefits:
- whenever a schema change happens; fix_lrl_ixlen used to compute row lengths and collect csc2 string for every single table in the database; this is inefficient, since a schema change only affects one table, the rest of the work is redundant and increases llmeta contention; this does not happen anymore
- we avoid reading transactionally from llmeta to retrieve csc2_schema and table version, for every table, which provides less lock contention
- code is considerably simpler

2024-02-13 16:32 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-02-16 14:44 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/519 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_tiered<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>analyze_partial_index_off_generated</p>

2024-02-21 20:17 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/520 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>phys_rep_tiered<br>queuedb_rollover_noroll1_generated<br>sc_swapfields_logicalsc_generated</p>

2024-02-27 18:44 UTC, dorinhogea commented
dhogea     Feb 27 10:00:33 2024  in-comdb2db clean_fix_lrl_ixlen_calls.R20240227.4

2024-02-29 19:20 UTC, mponomar approved these changes

2024-02-29 19:23 UTC, dorinhogea commented
@mponomar thank you

2024-02-29 19:24 UTC, merged