Do not send intrans results during replays
bloomberg/comdb2 pull request #4229
Opened 2024-02-22 20:47 UTC by nirbhayc

When client has 'intransresults' enabled, comdb2 should avoid sending results while replaying transaction statements.

2024-02-22 20:50 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2024-02-22 21:55 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/521 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>sc_truncate<br>sc_transactional_rowlocks_generated<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>prepare</p>

2024-02-23 13:01 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2024-02-23 15:42 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/521 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill_logput_window_generated<br>systable_locking<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>prepare<br>sc_swapfields_logicalsc_generated<br>truncatesc</p>

2024-02-27 16:00 UTC, mponomar approved these changes

2024-02-27 17:16 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2024-02-27 18:28 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/521 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>queuedb_rollover_noroll1_generated<br>prepare<br>truncatesc</p>

2024-02-28 14:14 UTC, nirbhayc commented
```cdb2test   Feb 27 13:26:11 2024  in-comdb2db comdb2-replay-intrans-issue.R20240227.8```

2024-02-28 14:18 UTC, mponomar approved these changes

2024-02-28 14:21 UTC, merged