Clear message when a schema change starts.
bloomberg/comdb2 pull request #4231
Opened 2024-02-23 17:25 UTC by dorinhogea

When we start a schema change on a master we should clearly print the name of the table and the kind of schema change.
This PR addresses this.

Also, make sure this is printed with the default logmsg level.

2024-02-23 18:29 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/520 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart<br>sc_transactional_rowlocks_generated<br>queuedb_rollover<br>prepare</p>

2024-02-26 15:29 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>274/520 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart<br>systable_locking<br>yast_stat4scan_generated<br>yast<br>prepare<br>analyze_recover_deadlock<br>analyze_partial_index_off_generated<br>autoanalyze<br>analyze<br>temp_table_truncate_leak</p>

2024-02-26 20:49 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>8/520 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>delfile_block [setup failure]<br>sc_timepart_logicalsc_generated<br>sc_truncate<br>sc_transactional_rowlocks_generated<br>queuedb_rollover_noroll1_generated<br>prepare<br>load_cache_autocache_generated<br>truncatesc_ufid_on_generated</p>

2024-02-27 05:25 UTC, dorinhogea commented
closing this, since it cannot pass rowlock_update with current copycomdb2 tool (binary path too long).

2024-02-27 05:25 UTC, closed without merging

2024-02-27 05:30 UTC, dorinhogea commented
resubmitted with shorter name here https://github.com/bloomberg/comdb2/pull/4240