{174149262}: Executing JDBC batch in transaction
bloomberg/comdb2 pull request #4233
Opened 2024-02-23 22:42 UTC by riverszhang89

Allow a JDBC batch to be executed in its own transaction. This behavior is toggled by the `use_txn_for_batch` URL parameter.

2024-02-23 22:42 UTC, riverszhang89 commented
/cbuild-compile-only

2024-02-23 23:54 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>375/520 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>yast_stat4scan_generated<br>yast<br>prepare<br>analyze_recover_deadlock<br>autoanalyze<br>analyze_partial_index_off_generated<br>analyze<br>temp_table_truncate_leak</p>

2024-03-01 15:19 UTC, markhannum approved these changes

2024-03-01 15:22 UTC, riverszhang89 commented
@markhannum Thanks for the review!

2024-03-01 15:22 UTC, merged