remove useless argument for sc_set_running
bloomberg/comdb2 pull request #4239
Opened 2024-02-26 21:57 UTC by dorinhogea

Once upon a time (i.e. around 2007AD) sc_set_running was being called on a replicant. Never more.

/plugin-branch sc_set_running_not_on_replicant

2024-02-26 21:57 UTC, dorinhogea commented
/plugin-branch sc_set_running_not_on_replicant

2024-02-26 21:59 UTC, dorinhogea commented on schemachange/sc_global.c
> - * The seed was a silly idea to stop imaginary race conditions on the
The idea was not so silly, as we learnt later on.  Hi Sam!

2024-02-27 00:25 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/520 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill_logput_window_generated<br>sc_truncate<br>queuedb_rollover<br>prepare</p>

2024-02-27 05:31 UTC, dorinhogea commented
resubmitted with shorter name here https://github.com/bloomberg/comdb2/pull/4241

2024-02-27 05:31 UTC, closed without merging