pass proper schema object for default tag
bloomberg/comdb2 pull request #4244
Opened 2024-02-27 17:58 UTC by dorinhogea

For default tag, when building keys, we need to use ondisk schema as source.

2024-02-27 19:08 UTC, mponomar approved these changes

2024-02-27 20:28 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>4/520 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>queuedb_rollover<br>prepare<br>lostwrite</p>

2024-02-28 00:21 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/520 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>prepare<br>truncatesc_ufid_on_generated</p>

2024-02-28 06:55 UTC, dorinhogea commented on db/macc_glue.c
> +            if (rc > 0)
here, we ignore negative rc values

2024-02-28 08:04 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/520 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>sc_transactional_rowlocks_generated<br>prepare</p>

2024-02-28 13:47 UTC, mponomar approved these changes

2024-02-28 14:06 UTC, dorinhogea commented
cdb2test   Feb 28 02:56:22 2024  in-comdb2db fix_default_keys.R20240228.2

2024-02-28 14:06 UTC, merged