Port https://github.com/bloomberg/comdb2/pull/4258 to 8.0
bloomberg/comdb2 pull request #4259
Opened 2024-02-28 20:21 UTC by dorinhogea

Port https://github.com/bloomberg/comdb2/pull/4258 to 8.0

2024-02-28 21:32 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/519 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sp<br>pmux_sqlite_memory_generated<br>truncatesc_ufid_on_generated</p>

2024-02-28 23:47 UTC, dorinhogea commented
cdb2test   Feb 28 16:30:22 2024  in-comdb2db one_more_tpt_resume_fix8.R20240228.9

2024-02-29 19:11 UTC, mponomar approved these changes

2024-02-29 19:12 UTC, dorinhogea commented
@mponomar @riverszhang89 thank you!

2024-02-29 19:12 UTC, merged