Need a LLMETA_SC_SEED per table
bloomberg/comdb2 pull request #4260
Opened 2024-02-29 05:05 UTC by dorinhogea

otherwise resume fails.  This is a follow-up on a previous resume fix.

NOTE: as it stands, code treats schema changes for which uuid=0 as standalone and the rest as part of a multi-table ddl transaction.  If a master swings interrupts the transaction, the resume is different in the two cases. For standalone table schema changes, the replicant does not retry the bplog if it detects a master swing, and returns an error. Instead, a new master resumes and finalize the schema change.
In the second case, the master resumes each schema change but does not finalize it. Instead, it is the replicant that retries the bplog, and the code on the master detects the pending schema changes and only runs the finalize part once the first part is completed.

NOTE2: as a consequence of the above, the single-node clusters do not finalize a multi-table ddl txn upon restart. This will be the subject of a future PR.

2024-03-05 19:18 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/520 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>schemalk_extralock_generated<br>queuedb_rollover<br>truncatesc<br>truncatesc_ufid_on_generated</p>

2024-03-06 15:38 UTC, dorinhogea commented
cdb2test   Mar  5 14:15:18 2024  in-comdb2db fix_resume_multi_ddl_schema.R20240305.4

2024-04-11 18:36 UTC, mponomar approved these changes

2024-04-15 20:32 UTC, dorinhogea commented
@mponomar thank you

2024-04-15 20:32 UTC, merged