Removing code to avoid a roundrip per replicant during schema change
bloomberg/comdb2 pull request #4267
Opened 2024-03-05 16:16 UTC by dorinhogea

In the early days we have tried to detect schema change collisions on replicants, and that failed shortly.   It used a broadcasting mechanism to let replicants know when schema change started and ended. 
Currently, we still go around and ping each replicant at the start of any schema change.  The callbacks do nothing except to ack back.
This is needed only by the legacy queue alter (in which case we make sure all replicants are up before trying to alter the queue), if any.
Removing code for greater simplicity and speed.

2024-03-05 18:03 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>262/520 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>incoherent_slow [setup failure]<br>sc_addfield_logicalsc_generated [setup failure]<br>sc_addfield [setup failure]<br>tmptbl_leak [setup failure]<br>tmptbl_leak_bigpool_generated [setup failure]<br>ssl_san [setup failure]<br>sql_func_mem_leak [setup failure]<br>sc_rebuilds_logicalsc_generated [setup failure]<br>sc_rebuilds_extralock_generated [setup failure]<br>nextsequence [setup failure]</p>

2024-03-05 20:28 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>1/520 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover_noroll1_generated</p>

2024-03-07 19:19 UTC, dorinhogea commented
cdb2test   Mar  5 13:01:20 2024  in-comdb2db no_moar_broadcasting.R20240305.2

2024-04-11 13:24 UTC, markhannum approved these changes

2024-04-11 13:28 UTC, dorinhogea commented
@markhannum thank you

2024-04-11 13:28 UTC, merged