Redefine useless origin_master_node
bloomberg/comdb2 pull request #4268
Opened 2024-03-05 16:28 UTC by dorinhogea

We have used origin_master_node to detect schema change resuming, though this is not how the resume has been working for awhile.   While I cannot remove the 256 bytes useless field from schema change object for now, I am removing the checks, which should make the 256 bytes field available for better usage (like tracking replicant who sent the request).

2024-03-05 19:20 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/520 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>queuedb_rollover<br>op_makerecord<br>sc_downgrade</p>

2024-03-06 15:37 UTC, dorinhogea commented
cdb2test   Mar  5 14:07:16 2024  in-comdb2db original_master_node.R20240305.5

2024-04-11 18:39 UTC, mponomar approved these changes

2024-04-15 20:34 UTC, dorinhogea commented
@mponomar thank you

2024-04-15 20:34 UTC, merged