{174371954}: Fixing memory leaks
bloomberg/comdb2 pull request #4275
Opened 2024-03-06 19:20 UTC by riverszhang89

An unterminated transaction (e.g., client executes "BEGIN", and disconnects without issuing a "COMMIT" or "ROLLBACK") may leak memory in a few places. This patch fixes it.

2024-03-06 19:21 UTC, riverszhang89 commented
/plugin-branch leak

2024-03-06 19:45 UTC, mohitkhullar approved these changes

2024-03-06 19:52 UTC, mohitkhullar commented on db/sqlinterfaces.c
> +    free(clnt->authdata);
if (clnt->authdata) ?

2024-03-06 20:29 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>6/521 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>sc_swapfields_logicalsc_generated<br>truncatesc<br>truncatesc_ufid_on_generated</p>

2024-03-06 21:42 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/521 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover_noroll1_generated<br>queuedb_rollover</p>

2024-03-07 13:25 UTC, riverszhang89 commented
cdb2test   Mar  6 17:53:19 2024  in-comdb2db recsize.R20240306.7

2024-03-07 13:25 UTC, riverszhang89 commented
@mohitkhullar Thanks for the review!

2024-03-07 13:25 UTC, merged