offset is not computed for non-ondisk tags
bloomberg/comdb2 pull request #4276
Opened 2024-03-06 21:28 UTC by dorinhogea

Per title, recsize is already set for non-ondisk tag, do not reset it to 0 accidentally.

2024-03-06 22:56 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/521 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_datacopy_logicalsc_generated</p>

2024-03-07 13:28 UTC, dorinhogea commented
Submitted by cdb2test on Mar  6 17:53:19 2024 (in-comdb2db).

2024-03-07 14:28 UTC, mponomar approved these changes

2024-03-07 14:33 UTC, dorinhogea commented
@mponomar thank you

2024-03-07 14:34 UTC, merged