Add explain comments for Virtual Table opcodes
bloomberg/comdb2 pull request #4279
Opened 2024-03-07 17:54 UTC by aakash10292

Currently Vtable opcodes show up as '???' which makes it slightly cumbersome to understand the plan for a query plan involving system table. This patch adds descriptions for these opcodes

2024-03-07 18:57 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/521 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>analyze_exit_immediately</p>

2024-03-13 15:22 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/522 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover_noroll1_generated</p>

2024-03-13 19:06 UTC, riverszhang89 approved these changes

2024-03-13 19:13 UTC, aakash10292 commented
cdb2test   Mar 13 11:20:24 2024  in-comdb2db aar_vtab_explain.R20240313.2

2024-03-13 19:13 UTC, aakash10292 commented
Thanks for the review @riverszhang89!

2024-03-13 19:13 UTC, merged