From 7.0 - give transactions some time to finish
bloomberg/comdb2 pull request #4282
Opened 2024-03-08 04:22 UTC by mponomar

When we're asked to exit, give running transactions a small grace period to let them try to finish.

2024-03-08 04:25 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ db/sqlinterfaces.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2024-03-08 06:32 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>4/520 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover<br>queuedb_rollover_noroll1_generated<br>sc_partial_datacopy_logicalsc_generated<br>truncatesc_offline_generated</p>

2024-03-08 14:01 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ db/sqlinterfaces.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2024-03-08 15:06 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/520 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>queuedb_rollover_noroll1_generated<br>truncatesc_offline_generated</p>

2024-03-08 19:25 UTC, akshatsikarwar approved these changes
{LETS<GO>}

2024-03-11 14:11 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2024-03-11 18:05 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/520 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill_logput_window_generated<br>tunables<br>truncatesc_offline_generated</p>

2024-03-12 00:56 UTC, mponomar commented
cdb2test   Mar 11 12:42:19 2024  in-comdb2db transaction-grace-period-8.0.R20240311.3

2024-03-12 00:56 UTC, merged