Fix duplicated bound param
bloomberg/comdb2 pull request #4287
Opened 2024-03-11 22:36 UTC by dorinhogea

sqlite Expr name still has the prefix @ for named bound parameters; make sure we skip that when we checked for reused named parameters.  This is a bug impacting queries that are parallelized and use named parameters multiple times

2024-03-12 00:59 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/521 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill</p>

2024-03-12 13:56 UTC, dorinhogea commented
cdb2test   Mar 11 19:33:22 2024  in-comdb2db fix_duplicated_bound_param.R20240311.10

2024-04-01 13:01 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/524 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_tiered<br>queuedb_rollover<br>truncatesc_offline_generated</p>

2024-04-02 19:10 UTC, dorinhogea commented
cdb2test   Apr  1 08:59:10 2024  in-comdb2db fix_duplicated_bound_param.R20240401.0

2024-04-03 13:37 UTC, mponomar approved these changes

2024-04-03 13:53 UTC, merged