Log test progress to a db if enabled
bloomberg/comdb2 pull request #4288
Opened 2024-03-12 18:45 UTC by mponomar

2024-03-12 20:03 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/521 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover_noroll1_generated<br>yast_stat4scan_generated<br>yast<br>truncatesc_ufid_on_generated</p>

2024-03-14 02:22 UTC, riverszhang89 commented on tests/yast.test/runit
> +. $TESTSROOTDIR/testsutil
testutils, not testsutil.

2024-03-14 02:22 UTC, riverszhang89 commented on tests/yast.test/runit
> +    testdb_note "$test end"
This line needs to be moved after the `$?` check.

2024-03-14 13:24 UTC, riverszhang89 approved these changes

2024-03-14 13:24 UTC, riverszhang89 commented
go go go

2024-03-14 13:27 UTC, merged