Add partition name (if any) and sqlname (if any) to stat size.
bloomberg/comdb2 pull request #4289
Opened 2024-03-12 21:21 UTC by dorinhogea

per title.

2024-03-12 22:32 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/521 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>timepart_trunc</p>

2024-03-13 11:57 UTC, dorinhogea commented
cdb2test   Mar 12 18:31:01 2024  in-comdb2db statsize_for_aliased.R20240312.11

2024-03-13 18:43 UTC, riverszhang89 approved these changes

2024-03-27 14:04 UTC, dorinhogea commented
@riverszhang89 thank you

2024-03-27 14:04 UTC, merged