{174676593}: Fixing trigger lock inversion
bloomberg/comdb2 pull request #4306
Opened 2024-03-22 14:34 UTC by riverszhang89

`dbq_poll()` acquires trigger-subscription-lock first, and `bdb-read-lock/recovery-write-lock` second. On the other hand, `rep_verify_match()`, when matching a `dbreg_register` log record on a queue file, acquires `bdb-write-lock/recovery-write-lock` first, and trigger-subscription-lock second. Therefore it can deadlock.

In this patch, all `trigger-subscrption-locks` are acquired, before `rep_verify_match` starts matching, to maintain the same lock ordering as `dbq_poll()`.

2024-03-22 14:35 UTC, roborivers reviewed
Lint check:

```diff


@@ berkdb/db/trigger_subscription.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/env/env_method.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2024-03-22 16:07 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/524 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_tiered<br>queuedb_rollover_noroll1_generated<br>lostwrite<br>analyze_exit_immediately<br>truncatesc</p>

2024-03-25 13:16 UTC, roborivers reviewed
Lint check:

```diff


@@ berkdb/db/trigger_subscription.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/env/env_method.c @@
+ Please make sure that a mutex is unlocked before returning.
```

2024-03-25 14:42 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/524 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover<br>truncatesc_offline_generated</p>

2024-03-26 13:20 UTC, akshatsikarwar approved these changes

2024-03-26 15:16 UTC, riverszhang89 commented
@akshatsikarwar Thanks for the review!

2024-03-26 15:16 UTC, merged