Fix build
bloomberg/comdb2 pull request #4324
Opened 2024-04-01 20:52 UTC by aakash10292

fix broken build on Mac OS Sonoma. Also suppress new warnings

2024-04-01 20:54 UTC, aakash10292 commented
/silent

2024-04-01 22:23 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/524 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover<br>truncatesc_offline_generated</p>

2024-04-02 20:13 UTC, chands10 submitted a review, later dismissed
LGTM

2024-04-02 20:40 UTC, chands10 approved these changes

2024-04-02 20:41 UTC, merged