faster inserts during tpt schema change
bloomberg/comdb2 pull request #4335
Opened 2024-04-04 17:01 UTC by dorinhogea

Leave the current shard for tpt last, to eliminate double writes for inserts.

2024-04-04 18:22 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/525 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover<br>truncatesc_offline_generated</p>

2024-04-29 19:09 UTC, mponomar approved these changes

2024-04-29 20:21 UTC, dorinhogea commented
dhogea     Apr 24 13:08:09 2024  in-comdb2db reverse_sc_order.R20240424.4

2024-04-29 20:39 UTC, aakash10292 approved these changes

2024-04-29 20:40 UTC, dorinhogea commented
@mponomar @aakash10292 thank you!

2024-04-29 20:40 UTC, merged