{174899913}: Fixing sporadic ENOENT errors
bloomberg/comdb2 pull request #4349
Opened 2024-04-11 20:35 UTC by riverszhang89

`comdb2_get_tmp_dir()` isn't thread-safe and may return an empty string. This causes the sqlite sorter to fail with ENOENT intermittently, when opening a temporary file.

This patch correctly sets the `once` flag in `comdb2_get_tmp_dir()`, to make it thread-safe for calls after the very first call.

2024-04-11 21:40 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/525 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>cdb2sql_queueodh_generated<br>cdb2sql<br>truncatesc_ufid_on_generated<br>truncatesc_offline_generated</p>

2024-04-12 13:17 UTC, markhannum submitted a review, later dismissed

2024-04-12 15:02 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/526 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated<br>queuedb_rollover_noroll1_generated<br>cdb2sql_queueodh_generated<br>cdb2sql<br>pmux_sqlite_memory_generated<br>sorter_tmpdir_race<br>truncatesc_offline_generated</p>

2024-04-12 18:07 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/526 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>autoanalyze<br>cdb2sql_queueodh_generated<br>cdb2sql<br>sorter_tmpdir_race<br>truncatesc<br>truncatesc_offline_generated</p>

2024-04-15 14:56 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>7/526 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated<br>sc_transactional_rowlocks_generated<br>queuedb_rollover<br>cdb2sql_queueodh_generated<br>cdb2sql<br>sorter_tmpdir_race<br>truncatesc_offline_generated</p>

2024-04-15 18:40 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>6/526 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover<br>cdb2sql_queueodh_generated<br>cdb2sql<br>sorter_tmpdir_race<br>truncatesc_offline_generated<br>truncatesc</p>

2024-04-17 14:07 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/527 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>schemalk<br>pmux_sqlite_file_generated<br>truncatesc_offline_generated</p>

2024-04-17 15:28 UTC, akshatsikarwar commented
Confused why `once` was not set by call to `clear_temp_tables` which happens _before_ any SQL runs.

2024-04-17 19:23 UTC, riverszhang89 commented
> Confused why `once` was not set by call to `clear_temp_tables` which happens _before_ any SQL runs.

The flag was never set. Every call into `comdb2_get_tmp_dir()` would copy the temp file path. I've added a new sorter_tmpdir_race test in this patch to reproduce this race.

2024-04-18 12:14 UTC, riverszhang89 commented
cdb2test   Apr 17 08:44:19 2024  in-comdb2db once.R20240417.1

2024-04-18 12:26 UTC, markhannum approved these changes

2024-04-18 12:42 UTC, riverszhang89 commented
@markhannum Thanks again for the review!

2024-04-18 12:42 UTC, merged