{174271358 } SQLite interstage heuristic
bloomberg/comdb2 pull request #4351
Opened 2024-04-12 18:40 UTC by akshatsikarwar

/silent

2024-04-12 19:44 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/525 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover_noroll1_generated<br>yast_stat4scan_generated<br>yast<br>cdb2sql_queueodh_generated<br>cdb2sql<br>truncatesc_offline_generated</p>

2024-04-15 19:21 UTC, akshatsikarwar commented
`cdb2test   Apr 12 15:32:39 2024  in-comdb2db sqlite-interstage-heuristic.R20240412.7`

2024-04-15 20:16 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/525 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover_noroll1_generated<br>pmux_sqlite_file_generated<br>truncatesc_offline_generated</p>

2024-05-06 14:09 UTC, markhannum approved these changes

2024-05-06 14:19 UTC, merged