avoid lock inversion during partition rollout
bloomberg/comdb2 pull request #4365
Opened 2024-04-18 17:07 UTC by dorinhogea

Short fix for partition lock inversion: do not read from llmeta during triggers update.

2024-04-18 17:11 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ berkdb/db/trigger_subscription.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/env/env_method.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/reversesql/reversesql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/reversesql/reversesql.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2024-04-18 19:51 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ berkdb/db/trigger_subscription.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/env/env_method.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/reversesql/reversesql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/reversesql/reversesql.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2024-04-19 14:27 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>7/523 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>truncatesc_offline_generated<br>queuedb_rollover<br>sc_timepart_logicalsc_generated<br>tunables<br>sc_downgrade<br>selectv_rcode_disable_svonly_nop_generated</p>

2024-04-23 18:03 UTC, dorinhogea commented
cdb2test   Apr 18 14:00:13 2024  in-comdb2db fix_lock_inversion_partitions.R20240418.6

2024-04-29 19:19 UTC, mponomar approved these changes

2024-04-29 20:55 UTC, dorinhogea commented
@mponomar thank you

2024-04-29 20:55 UTC, merged