fix partition rollout and remove scdone outside finalizing txn
bloomberg/comdb2 pull request #4367
Opened 2024-04-18 18:09 UTC by dorinhogea

3 things:
- avoid reading llmeta during views update (lock inversion prevention) (ported https://github.com/bloomberg/comdb2/pull/4365 to main)
- remove code and tunable sc_done_same_tran (only on going forward)
- fix scdone for comdb2sc and partition rollouts, where it is sent outside finalizing txn

2024-04-22 17:34 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>374/528 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>simple_timepart_reptimeout_generated<br>timepart_changeretention<br>timepart_retention1<br>simple_timepart<br>sc_timepart_logicalsc_generated<br>sc_timepart<br>timepart_auth<br>renametable<br>renametable_lightweight_generated<br>timepart_readonly</p>

2024-04-24 22:28 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>447/529 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>systable_locking<br>timepart_retention1<br>timepart_changeretention<br>simple_timepart_reptimeout_generated<br>simple_timepart<br>sc_timepart_logicalsc_generated<br>sc_resume_logicalsc_generated<br>sc_resume<br>sc_timepart<br>timepart_auth</p>

2024-04-26 21:13 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>436/529 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>systable_locking<br>timepart_retention1<br>simple_timepart_reptimeout_generated<br>timepart_changeretention<br>simple_timepart<br>sc_timepart<br>sc_resume_logicalsc_generated<br>sc_timepart_logicalsc_generated<br>sc_resume<br>queuedb_rollover</p>

2024-04-29 22:18 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-05-07 20:25 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/532 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>schemalk_logicalsc_generated<br>sc_transactional_rowlocks_generated<br>timepart_trunc<br>comdb2sys_queueodh_generated<br>truncatesc_offline_generated</p>

2024-05-08 16:11 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>396/532 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>replay_history<br>truncatesc<br>sc_resume_logicalsc_generated<br>sc_resume<br>timepart_auth<br>timepart_changeretention<br>renametable_lightweight_generated<br>renametable<br>timepart_readonly<br>timepart_constraints</p>

2024-05-13 15:50 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-05-17 20:29 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-05-20 14:27 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-05-20 17:11 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/534 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume<br>schemalk_extralock_generated<br>schemalk<br>phys_rep_tiered_nosource_generated<br>phys_rep_tiered<br>transchunk_manyins<br>comdb2sys<br>sc_downgrade<br>truncatesc_offline_generated</p>

2024-05-28 18:13 UTC, dorinhogea commented
resubmitted with shorted name because it breaks robom (https://github.com/bloomberg/comdb2/pull/4457)

2024-05-28 18:13 UTC, closed without merging