{175017306} enable bypass_auth flag for triggers
bloomberg/comdb2 pull request #4369
Opened 2024-04-19 18:15 UTC by mohitkhullar

We currently had it enabled only for auto analyze (for table reads), bypass for writes too.

2024-04-19 19:33 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/528 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>schemalk_extralock_generated<br>schemalk<br>truncatesc_offline_generated</p>

2024-04-22 16:10 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/529 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>sc_resume<br>schemalk_extralock_generated<br>sc_transactional_rowlocks_generated<br>queuedb_rollover_noroll1_generated<br>sc_downgrade<br>truncatesc_offline_generated<br>truncatesc_ufid_on_generated</p>

2024-04-23 17:15 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>7/529 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>schemalk_extralock_generated<br>queuedb_rollover<br>recover_deadlock<br>sc_lotsoftables_logicalsc_generated<br>sc_downgrade<br>truncatesc_offline_generated</p>

2024-04-24 15:14 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>9/529 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>schemalk<br>schemalk_extralock_generated<br>sc_transactional_rowlocks_generated<br>queuedb_rollover_noroll1_generated<br>transchunk_manyins<br>sc_lotsoftables_logicalsc_generated<br>sc_downgrade<br>truncatesc_offline_generated</p>

2024-04-25 01:11 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>5/529 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>sc_resume<br>schemalk_extralock_generated<br>sc_downgrade<br>truncatesc_offline_generated</p>

2024-04-25 15:09 UTC, mohitkhullar commented
cdb2test   Apr 23 09:29:40 2024  in-comdb2db trigger_bypass_auth.R20240423.1

2024-04-25 15:10 UTC, akshatsikarwar approved these changes

2024-04-25 15:11 UTC, merged