Archive old files on db --create
bloomberg/comdb2 pull request #4392
Opened 2024-04-30 17:57 UTC by morgando

The changes in this PR archive database files in the database directory at the time of `--create`. A file is a database file if it ends with one of the following extensions: `".dta", ".index", ".datas*", ".blobs*"`. Note that `.datas*` and `.blobs*` contain a wildcard. Files are archived in the directory given by `get_savdir()`.

The motivation for disallowing preexisting direntries on initialization is to remove ambiguity as to whether files in a database directory were created by the running db or by a previous db that lived in the same directory. #4376 contains an alternative approach to solve this problem.

2024-04-30 19:07 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/532 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>schemalk_extralock_generated<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>sc_downgrade<br>truncatesc_ufid_on_generated<br>truncatesc_offline_generated<br>comdb2sys_queueodh_generated<br>comdb2sys<br>comdb2sys_pagesize_generated</p>

2024-05-01 15:34 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>10/532 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>truncatesc_ufid_on_generated<br>schemalk_extralock_generated<br>queuedb_rollover<br>triggersc_latency<br>sc_downgrade<br>truncatesc_offline_generated<br>comdb2sys_queueodh_generated<br>comdb2sys_pagesize_generated<br>comdb2sys</p>

2024-05-01 19:51 UTC, chands10 approved these changes

2024-05-02 16:07 UTC, morgando commented on db/comdb2.c
> +    if (gbl_create_mode && (archive_old_files(thedb->basedir) != 0)) {
Files can get created before this point -- must archive sooner!

2024-05-02 18:26 UTC, chands10 submitted a review, later dismissed

2024-05-03 01:55 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>11/532 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart<br>sc_resume<br>schemalk_extralock_generated<br>schemalk<br>schemalk_logicalsc_generated<br>queuedb_rollover<br>sc_lotsoftables_logicalsc_generated<br>truncatesc_offline_generated<br>comdb2sys_queueodh_generated<br>comdb2sys_pagesize_generated</p>

2024-05-03 14:09 UTC, chands10 approved these changes

2024-05-03 14:11 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2024-05-03 15:21 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/532 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume<br>schemalk<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>sc_downgrade<br>truncatesc_offline_generated<br>comdb2sys_pagesize_generated<br>comdb2sys_queueodh_generated<br>comdb2sys</p>

2024-05-03 18:08 UTC, merged