workaround stock sqlite token count limit
bloomberg/comdb2 pull request #4399
Opened 2024-05-01 21:06 UTC by aakash10292

exclude token count check as we've hit stock sqlite limit. Also expand Expr.op field to u16 since we now have more than 255 tokens

2024-05-01 21:10 UTC, roborivers reviewed
Lint check:

```diff


@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
```

2024-05-02 15:26 UTC, morgando submitted a review, later dismissed
No Wconversion errors from this change -- LGTM once the robots approve!

2024-05-02 15:27 UTC, riverszhang89 commented on sqlite/src/sqliteInt.h
> +  u16 op;                 /* Operation performed by this node */
I'd ifdef-guard this as well.

2024-05-02 15:29 UTC, aakash10292 commented on sqlite/src/sqliteInt.h
> +  u16 op;                 /* Operation performed by this node */
will do

2024-05-03 06:05 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/532 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume<br>truncatesc<br>schemalk_extralock_generated<br>truncatesc_offline_generated<br>comdb2sys_queueodh_generated<br>comdb2sys_pagesize_generated<br>comdb2sys</p>

2024-05-08 14:54 UTC, aakash10292 commented
cdb2test   May  2 22:45:23 2024  in-comdb2db aar_increasing_token_limit.R20240502.10

2024-06-05 13:30 UTC, mponomar approved these changes

2024-06-05 13:32 UTC, merged