Make rebuild work for partitions that are created using "create .. partitioned" syntax.
bloomberg/comdb2 pull request #4406
Opened 2024-05-07 15:37 UTC by dorinhogea

Simple patch, use one shard to retrieve csc2 and make rebuild work.  
NOTE: rebuild work for partitions added to existing tables, because first tables are aliased and share the same name as the partition.

2024-05-07 22:01 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/532 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>schemalk<br>sc_transactional_rowlocks_generated<br>sc_downgrade<br>truncatesc_offline_generated<br>truncatesc_ufid_on_generated<br>comdb2sys<br>comdb2sys_pagesize_generated<br>comdb2sys_queueodh_generated</p>

2024-05-29 13:32 UTC, dorinhogea commented on tests/timepart_trunc.test/runit
> +$cmd "create table t18(a int) partitioned by time period 'daily' retention 2 start '20240101T'"
must have accidentally removed some lines, fixed.

2024-05-29 15:08 UTC, mponomar approved these changes

2024-05-29 16:19 UTC, dorinhogea commented
@mponomar thank you

2024-05-29 16:19 UTC, merged