{172983130}: Tweaking oldfile list
bloomberg/comdb2 pull request #4421
Opened 2024-05-08 19:08 UTC by riverszhang89

A few tweaks to the oldfile list logic to make it collect faster.

2024-05-09 00:00 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/532 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>schemalk_extralock_generated<br>schemalk<br>truncatesc_offline_generated<br>comdb2sys<br>comdb2sys_queueodh_generated<br>comdb2sys_pagesize_generated</p>

2024-05-16 19:45 UTC, chands10 commented on bdb/llmeta.c
> +    if (*resume == NULL) {
if *resume is NULL would this be valid for memcp in the line above?

2024-05-21 19:32 UTC, chands10 approved these changes

2024-05-21 20:11 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>10/534 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>schemalk_extralock_generated<br>phys_rep_tiered_nosource_generated<br>phys_rep_tiered<br>sc_lotsoftables<br>sc_lotsoftables_logicalsc_generated<br>truncatesc_offline_generated<br>comdb2sys<br>comdb2sys_queueodh_generated<br>comdb2sys_pagesize_generated</p>

2024-05-21 22:49 UTC, riverszhang89 commented
@chands10 Thanks for the review!

2024-05-21 22:49 UTC, merged