[8.0] {174996173}: Workaround for remote-insert that reads from the same remote
bloomberg/comdb2 pull request #4434
Opened 2024-05-15 13:24 UTC by riverszhang89

8.0 port of #4391. Again, this is a short-term fix. Dorin has a better idea to make remote+chunks work without all these tweaks.

2024-05-15 15:48 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/527 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill_logput_window_generated<br>truncatesc_offline_generated<br>sc_timepart_logicalsc_generated<br>sc_timepart<br>lostwrite<br>sc_downgrade</p>

2024-05-16 12:09 UTC, riverszhang89 commented
`cdb2test   May 15 10:33:51 2024  in-comdb2db chunk_remote_8.R20240515.2`

2024-05-16 12:26 UTC, markhannum approved these changes

2024-05-16 13:33 UTC, riverszhang89 commented
@markhannum Thanks for the review!

2024-05-16 13:33 UTC, merged