enable fdb auth by default
bloomberg/comdb2 pull request #4441
Opened 2024-05-22 17:54 UTC by mohitkhullar

2024-05-22 18:00 UTC, roborivers reviewed
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

2024-05-22 19:28 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>14/534 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart<br>sc_truncate<br>schemalk_logicalsc_generated<br>schemalk<br>schemalk_extralock_generated<br>sc_transactional_rowlocks_generated<br>phys_rep_tiered_nosource_generated<br>phys_rep_tiered<br>sc_downgrade<br>truncatesc_offline_generated</p>

2024-05-22 20:03 UTC, aakash10292 approved these changes

2024-05-23 11:46 UTC, mohitkhullar commented
Thanks

2024-05-23 11:49 UTC, merged