8.0 Add set statement to force fdb_push_redirect
bloomberg/comdb2 pull request #4447
Opened 2024-05-23 14:04 UTC by chands10

Add option set force_fdb_push with options redirect, remote, off to force one of these to be used, even if tunable is off

Note that if fdb push redirect + remote tunables are on, but set force_fdb_push off is run, the tunable still takes precedence and runs with the option on

8.0 version of https://github.com/bloomberg/comdb2/pull/4440

2024-05-23 14:05 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ berkdb/db/trigger_subscription.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/env/env_method.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/reversesql/reversesql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/reversesql/reversesql.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2024-05-23 14:10 UTC, aakash10292 approved these changes
Good to merge once in-comdb2db!

2024-05-23 15:12 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>4/528 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>truncatesc_offline_generated<br>sp_twofiles_generated<br>sc_downgrade<br>truncatesc</p>

2024-05-23 16:31 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/528 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sicomplex3 [setup failure]<br>truncatesc_offline_generated<br>lostwrite<br>sc_lotsoftables_logicalsc_generated<br>sc_downgrade</p>

2024-05-24 14:33 UTC, chands10 commented
cdb2test   May 23 12:26:18 2024  in-comdb2db set_redirect_8.0.R20240523.6

2024-05-24 14:33 UTC, merged