Resubmit https://github.com/bloomberg/comdb2/pull/4367 with shorter branch name
bloomberg/comdb2 pull request #4457
Opened 2024-05-28 18:12 UTC by dorinhogea

Breaks rm.

From the original PR:

3 things:
- avoid reading llmeta during views update (lock inversion prevention) (ported https://github.com/bloomberg/comdb2/pull/4365 to main)
- remove code and tunable sc_done_same_tran (only on going forward)
- fix scdone for comdb2sc and partition rollouts, where it is sent outside finalizing txn

2024-05-28 19:45 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/534 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill<br>sc_downgrade<br>sc_lotsoftables<br>truncatesc_offline_generated</p>

2024-05-28 20:31 UTC, dorinhogea commented
cdb2test   May 28 15:28:41 2024  in-comdb2db fixlockinversion_partitionsm.R20240528.3

2024-05-30 16:14 UTC, dorinhogea commented
cdb2test   May 30 10:55:19 2024  in-comdb2db fixlockinversion_partitionsm.R20240530.1

2024-05-31 17:16 UTC, mponomar approved these changes

2024-05-31 19:18 UTC, dorinhogea commented
@mponomar thank you

2024-05-31 19:18 UTC, merged