Do not keep views lock for the duration of a serial tpt schema change.
bloomberg/comdb2 pull request #4472
Opened 2024-06-04 18:32 UTC by dorinhogea

Currently the master node cannot create new sqlite engines during a partition schema change if there are too many shards (tunable dohsql_sc_max_threads, default 8).  Thi is because walking the shards require an exclusive mutex on views (to prevent a racing partition configuration change).  
This patch eliminates the long term mutex acquisition, instead doing lock-coupling kinda of shard walk.

2024-06-04 18:40 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ berkdb/db/trigger_subscription.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/env/env_method.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/reversesql/reversesql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/reversesql/reversesql.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2024-06-04 21:13 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/532 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>truncatesc_offline_generated<br>sc_lotsoftables_logicalsc_generated<br>sc_lotsoftables<br>truncatesc_ufid_on_generated</p>

2024-06-05 17:23 UTC, dorinhogea commented
cdb2test   Jun  4 17:11:18 2024  in-comdb2db asyncserialtpt.R20240604.7

2024-06-14 19:27 UTC, mponomar approved these changes

2024-06-25 15:53 UTC, dorinhogea commented
@mponomar thank you

2024-06-25 15:53 UTC, merged