Cherrypick of SQLite planner improvement on LIMIT
bloomberg/comdb2 pull request #4485
Opened 2024-06-11 13:45 UTC by riverszhang89

https://sqlite.org/src/info/c4a9dda2809c6e0e

2024-06-11 14:57 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/554 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>sc_transactional_rowlocks_generated<br>yast_stat4scan_generated<br>yast<br>analyze<br>sc_lotsoftables<br>truncatesc_offline_generated</p>

2024-06-12 20:18 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/554 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_downgrade<br>truncatesc_offline_generated</p>

2024-06-13 14:17 UTC, markhannum approved these changes

2024-06-13 15:11 UTC, riverszhang89 commented
@markhannum Thanks for the review!

2024-06-13 15:11 UTC, merged