Rep ssl
bloomberg/comdb2 pull request #4486
Opened 2024-06-12 16:33 UTC by akshatsikarwar

/silent

2024-06-12 17:42 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/554 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>sc_timepart<br>schemalk<br>incremental_backup_usenames<br>online_compaction<br>truncatesc_offline_generated<br>truncatesc_ufid_on_generated</p>

2024-06-13 14:00 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/556 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>selectv_rcode_disable_svonly_nop_generated<br>sc_transactional_rowlocks_generated<br>online_compaction<br>timepart_trunc<br>basic_ssl_generated<br>sc_downgrade<br>truncatesc_offline_generated</p>

2024-06-13 15:37 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/557 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>sc_timepart<br>sicountbug<br>sc_lotsoftables<br>sc_lotsoftables_logicalsc_generated<br>truncatesc_offline_generated</p>

2024-07-02 18:26 UTC, akshatsikarwar commented on tests/opt/bb/tmp_testdir_generated.test/lrl.options
Done!

2024-07-02 20:29 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/559 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>sc_timepart<br>sc_resume<br>dbcreate<br>sc_lotsoftables_logicalsc_generated<br>truncatesc_offline_generated</p>

2024-07-03 11:09 UTC, riverszhang89 approved these changes
Very surgical - good to merge!

2024-07-03 13:56 UTC, merged