Address out-of-date types in hatest.c
bloomberg/comdb2 pull request #4489
Opened 2024-06-13 14:12 UTC by morgando

`hatest.c` was using a copy of the definitions of `cdb2_hndl` and `sbuf2`. The real definition of `cdb2_hndl` changed, which broke the hatest tool since it would cast `cdb2_hndl` structs to its own out-of-date type.

The changes in this PR create a new private header for `cdb2api.c` called `cdb2api_p.h`. `hatest.c` includes this header to get the definition of `cdb2_hndl` instead of defining a copy of it. It also includes `sbuf2.c` to get the definition of `sbuf2` instead of defining a copy.

The definition of `sbuf2` could also potentially be moved to a private header file.

2024-06-13 14:15 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

2024-06-13 15:33 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/554 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>schemalk_logicalsc_generated<br>incoherent_slow<br>autoanalyze<br>sc_downgrade<br>truncatesc_offline_generated</p>

2024-06-17 19:34 UTC, LiSodium approved these changes

2024-06-18 15:49 UTC, morgando commented
`mdouglas47 Jun 18 10:29:02 2024  in-comdb2db refactor_cdb2api.R20240618.3`

2024-06-18 15:49 UTC, merged