Address warnings when compiling with -DTEST_OSQL
bloomberg/comdb2 pull request #4510
Opened 2024-06-25 17:35 UTC by morgando

Warnings were preventing compilation with -DTEST_OSQL. The changes in this PR address these warnings.

2024-06-25 17:40 UTC, roborivers reviewed
Lint check:

```diff


@@ db/osqlshadtbl.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

2024-06-25 18:45 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>5/555 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>sc_transactional_rowlocks_generated<br>autoanalyze<br>dbcreate<br>truncatesc_offline_generated</p>

2024-06-25 19:24 UTC, akshatsikarwar approved these changes

2024-06-25 19:31 UTC, mponomar approved these changes

2024-06-26 20:46 UTC, morgando commented
`mdouglas47 Jun 26 12:10:10 2024  in-comdb2db fix_warnings.R20240626.5`

2024-06-26 20:46 UTC, merged