Fix snapshot replication bug
bloomberg/comdb2 pull request #4521
Opened 2024-07-02 17:56 UTC by morgando

The changes in this PR fix these 2 bugs related to the new snapshot-isolation implementation (aka modsnap):

1. Replicants do not add transactions to the commit LSN map when early acks are disabled.
2. A replicant can early ack a commit LSN before it puts that LSN in the commit LSN map: A commit LSN is passed to `__rep_set_last_locked` before it is added to the commit LSN map, and a commit LSN can be early acked as soon as it is passed to `__rep_set_last_locked`.

Both of these bugs are fixed in this PR by unconditionally adding a transaction's commit LSN to the commit LSN map just before calling `__rep_set_last_locked`.

The changes in this PR also cause the `snapisol` test to run an iteration with early acks disabled.

2024-07-02 18:22 UTC, markhannum approved these changes

2024-07-02 19:03 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/556 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>sc_timepart<br>blkseq_race<br>dbcreate<br>truncatesc_offline_generated</p>

2024-07-03 19:05 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/560 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>dbcreate<br>truncatesc_offline_generated</p>

2024-07-05 20:12 UTC, morgando commented
`cdb2test   Jul  3 14:54:40 2024  in-comdb2db fix_modsnap_replication.R20240703.8`

2024-07-05 20:12 UTC, merged