Refactor osql_save_updrec
bloomberg/comdb2 pull request #4526
Opened 2024-07-03 15:16 UTC by morgando

Improvement upon #4519

- Add missing error checking.
- Save upsert flags into the insert hash at the point when upsert flags are saved into the update hash.
- Don't save upsert flags into the update hash if an update is getting squashed into an insert.

2024-07-03 15:25 UTC, LiSodium commented on db/osqlshadtbl.c
> +        }
```suggestion
        rc = upsert_flags_for_add ? save_rec_flags(thd->clnt, tbl, tmp, upsert_flags_for_add, 1 /*addrec*/) : save_rec_flags(thd->clnt, tbl, tmp, flags, 0 /* updrec */))
        if (rc) return -1;```

2024-07-03 16:02 UTC, LiSodium approved these changes

2024-07-03 16:35 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/559 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>ssl_rep [setup failure]<br>cldeadlock<br>sc_timepart_logicalsc_generated<br>online_compaction<br>dbcreate<br>sc_downgrade<br>truncatesc<br>truncatesc_offline_generated</p>

2024-07-10 15:41 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/562 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume<br>sc_transactional_rowlocks_generated<br>sc_lotsoftables_logicalsc_generated<br>sc_lotsoftables</p>

2024-07-11 18:19 UTC, merged