Clean up uncommittable txn error handling
bloomberg/comdb2 pull request #4531
Opened 2024-07-05 19:54 UTC by morgando

- Make the error message more descriptive for transactions that are uncommittable due to a duplicate key violation.
- Fix the spelling of "uncommittable" throughout the codebase -- it was previously spelled "uncommitable".

2024-07-05 20:27 UTC, LiSodium approved these changes

2024-07-05 21:14 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/560 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>sc_resume<br>incremental_backup_usenames<br>autoanalyze<br>reorder_deletes_noreorder_generated<br>dbcreate<br>sc_downgrade<br>truncatesc_offline_generated</p>

2024-07-08 13:43 UTC, riverszhang89 approved these changes

2024-07-09 19:05 UTC, morgando commented on db/osqlcomm.c
> +                    reqerrstr(iq, COMDB2_CSTRT_RC_DUP, "Transaction is uncommittable: "
The error code set in `reqerrstr` is normally sent to the replicant. But if it is set during a retry (as it is in uncommittable transaction cases), then this code gets overwritten with the rc [here](https://github.com/bloomberg/comdb2/blob/a39df61051770acc5167d2feefd4cbcbfe1be034/db/sltdbt.c#L444).

This is why the client ends up with `CDB2_VERIFY_ERROR` when they attempt an uncommittable transaction.

2024-07-09 19:06 UTC, morgando commented
`cdb2test   Jul  5 17:04:59 2024  in-comdb2db uncommittable_error.R20240705.6`

2024-07-09 19:06 UTC, merged