Allow tests to use custom LRLs for 2 & 3-ary database
bloomberg/comdb2 pull request #4547
Opened 2024-07-11 21:05 UTC by morgando

2024-07-11 22:17 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/562 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>timepart_trunc<br>sc_lotsoftables_logicalsc_generated<br>sc_lotsoftables</p>

2024-07-12 14:15 UTC, morgando commented on tests/setup
>      fi
If `lrl_secondary.options` doesn't exist and the database is a secondary database or if `lrl_tertiary.options` doesn't exist and the database is a tertiary database, then the database will use `lrl.options`, if it exists.

2024-07-12 18:32 UTC, riverszhang89 approved these changes
LGTM! This is going to be very useful!

2024-07-12 19:37 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/402 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sicountbug<br>sc_lotsoftables<br>sc_downgrade</p>

2024-07-22 16:48 UTC, merged