Clean
bloomberg/comdb2 pull request #4552
Opened 2024-07-16 19:30 UTC by akshatsikarwar

/silent

2024-07-16 20:41 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/562 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart<br>sc_resume<br>truncatesc</p>

2024-07-17 11:39 UTC, riverszhang89 approved these changes

2024-07-17 14:02 UTC, akshatsikarwar commented
/plugin-branch clean

2024-07-17 14:39 UTC, riverszhang89 approved these changes

2024-07-17 14:40 UTC, merged