Refactor comdb2_files test
bloomberg/comdb2 pull request #4563
Opened 2024-07-18 20:16 UTC by morgando

2024-07-18 21:26 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/562 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>sc_timepart<br>socksql_master_swings<br>lostwrite<br>sc_lotsoftables_logicalsc_generated<br>sc_lotsoftables</p>

2024-07-19 15:07 UTC, aakash10292 approved these changes
LGTM other than the failexit bit. It's upto you if you want to reuse that or not

2024-07-19 15:30 UTC, aakash10292 approved these changes

2024-07-19 16:37 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/562 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>sc_resume<br>sc_truncate<br>socksql_master_swings<br>sc_lotsoftables_logicalsc_generated<br>sc_lotsoftables</p>

2024-07-19 18:40 UTC, merged