[8.0] - Refactor comdb2_files test
bloomberg/comdb2 pull request #4584
Opened 2024-07-29 17:14 UTC by morgando

Port #4563 to 8.0

2024-07-29 17:46 UTC, roborivers reviewed
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
@@ berkdb/db/trigger_subscription.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/env/env_method.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ bdb/file.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/eventlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/reversesql/reversesql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlglue.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
@@ plugins/reversesql/reversesql.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

2024-07-29 21:38 UTC, LiSodium commented on tests/comdb2_files.test/runit
> +		local dbname=$1 dbdir=$2
Just curious why these are locally scoped since they're the same for all the tests.

2024-07-29 21:38 UTC, LiSodium commented on tests/comdb2_files.test/runit
> +function test_comdb2_files_restricted_file() {
```suggestion
function test_comdb2_no_restricted_file_access() {
```

2024-07-29 21:38 UTC, LiSodium commented on tests/comdb2_files.test/runit
> +function test_comdb2_files_restricted_directory() {
```suggestion
function test_comdb2_no_restricted_directory_access() {
```

2024-07-29 21:38 UTC, LiSodium commented on tests/comdb2_files.test/runit
> +function test_comdb2_files_large_file() {
```suggestion
function test_comdb2_query_large_file() {
```

2024-07-29 21:38 UTC, LiSodium commented on tests/comdb2_files.test/runit
> +	)
```suggestion
		return  ($query_rc != 0 || $res_size != exp_size)
```

2024-07-29 21:38 UTC, LiSodium commented on tests/comdb2_files.test/runit
> +		fi
```suggestion
		return $query_rc
```

2024-07-29 21:38 UTC, LiSodium commented on tests/comdb2_files.test/runit
> +		return $?
```suggestion
                query_rc = $?
		return !$query_rc
```

2024-07-29 21:38 UTC, LiSodium commented on tests/comdb2_files.test/runit
> +		return $?
```suggestion
               query_rc = $?
		return !$query_rc
```

2024-07-29 21:38 UTC, LiSodium commented on tests/comdb2_files.test/runit
> +		if ! $testcase $dbname $dbdir;
```suggestion
                rc = $testcase $dbname $dbdir
		if [[ $rc != 0 ]]
```

2024-07-29 21:38 UTC, LiSodium commented on tests/comdb2_files.test/runit
> +		echo "Passed $testcase"
should be in an else block

2024-07-29 21:38 UTC, LiSodium commented on tests/comdb2_files.test/runit
> +function test_comdb2_files_broken_symlink() {
```suggestion
function test_comdb2_broken_symlink() {
```

2024-07-29 22:36 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/550 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite<br>pglogs_seqnum<br>online_compaction<br>selectv_rcode_disable_svonly_nop_generated<br>truncatesc<br>truncatesc_offline_generated</p>

2024-07-30 15:06 UTC, mponomar approved these changes
Looks ok.  Returning 0 on success is a shell idiom, so not really worth inverting it, but it's really a style preference.  Stopping early on error also seems ok except for small independent tests (eg: yast*).

2024-07-30 15:14 UTC, LiSodium commented
> Looks ok. Returning 0 on success is a shell idiom, so not really worth inverting it, but it's really a style preference. Stopping early on error also seems ok except for small independent tests (eg: yast*).

Personally, feel like it's easier to read when passing tests return 0. Since these tests are shell scripts, we should probably follow the standard shell convention for success codes (also it's not a difficult change). These seem to be pretty short and fast tests, so I'm still on the side of running through all of them since that is what test runners in other languages (e.g. junit pytest) would do.

2024-07-30 15:29 UTC, morgando commented
I intended for every passing test to return 0 and every failing test to return non-0. Did I not get that right somewhere @LiSodium?

2024-07-30 16:01 UTC, LiSodium commented
> I intended for every passing test to return 0 and every failing test to return non-0. Did I not get that right somewhere @LiSodium?

Nothing wrong with what you did. Inverting the values is a stylistic preference for the tests to return 0 on success so that the caller (test runner in this case) can just handle printing whether the test succeeded or failed and does not have to handle return code being negated after the test

2024-07-30 18:24 UTC, morgando commented
`cdb2test   Jul 29 18:21:50 2024  in-comdb2db 8_refactor_test.R20240729.9`

2024-07-30 18:24 UTC, merged