Avoid deadlocking between partition rollout and queries accessing schema system tables
bloomberg/comdb2 pull request #4587
Opened 2024-07-30 15:10 UTC by dorinhogea

We record how many system tables a query needs, which requires "comdb2_tables" systable_lock.  If any, we get the views lock before getting table locks on those system tables.  The views lock is kept until the last of those system tables is collected, which happens at the beginning at the vdbe execution.   For the client driven next_record run, the views lock is available.

2024-07-30 21:17 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/562 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume</p>

2024-07-31 13:39 UTC, dorinhogea commented
cdb2test   Jul 30 14:06:52 2024  in-comdb2db fixcomdb2tables.R20240730.10

2024-07-31 13:44 UTC, mponomar approved these changes

2024-07-31 15:03 UTC, dorinhogea commented
@mponomar thank you

2024-07-31 15:03 UTC, merged