Enhance modsnap debugging
bloomberg/comdb2 pull request #4595
Opened 2024-08-02 22:03 UTC by morgando

The changes in this PR

- Cause adds to the commit LSN map to fail if the LSN being added is less than the largest LSN in the map.
- Add a header to versioned memory pool logs to provide better tracing.
- Turn on more verbose logging for the `sicountbug` test.

2024-08-02 23:15 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>524/562 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_tiered_nosource_generated<br>cldeadlock<br>truncatesc<br>truncatesc_offline_generated<br>pg_free_recovery<br>sc_resume_logicalsc_generated<br>sc_resume<br>systable_locking<br>sicountbug<br>sirace</p>

2024-08-05 19:48 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/562 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated<br>scupdates_logicalsc_generated</p>

2024-08-06 04:52 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/562 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume</p>

2024-10-23 02:32 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/586 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_redo [setup failure]<br>lock_views [setup failure]<br>verify_error [setup failure]<br>sc_remsql_fdbpushredirect_generated [setup failure]<br>snap_ha_retry_newsi_generated</p>

2025-02-27 16:22 UTC, chands10 approved these changes

2025-02-28 21:41 UTC, morgando commented
`cdb2test   Feb 27 17:31:17 2025      success debug_modsnap.R20250227.4`

2025-02-28 21:53 UTC, merged