Remote Table Aliases
bloomberg/comdb2 pull request #4599
Opened 2024-08-06 20:31 UTC by aakash10292

Get alias as advertised [here](https://tutti.prod.bloomberg.com/comdb2/programming/sql#get) is unimplemented. Additionally there doesn't seem to be a way to drop an alias once created. Furthermore, all alias operations currently seem to read and write directly from llmeta which can prove to be expensive in scenarios where resolving an alias name to a remote tablename occurs frequently . 

This patch addresses the above three : 
1.) Fetch the local alias for a remote table
2.) Delete an alias -> PUT ALIAS <aliasname> ""
3.) Maintain alias information in an in-memory hash table

2024-08-07 00:48 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/564 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>truncatesc_ufid_on_generated</p>

2024-08-07 01:35 UTC, aakash10292 commented
cdb2test   Aug  6 17:27:00 2024  in-comdb2db aar_alias.R20240806.1

2024-08-16 15:43 UTC, markhannum approved these changes

2024-08-16 21:39 UTC, markhannum approved these changes

2024-08-20 21:13 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/572 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>comdb2sys [setup failure]<br>scupdates [setup failure]<br>load_cache_dumpmax_generated [setup failure]<br>basic_nogenid48_generated [setup failure]<br>sc_resume_logicalsc_generated<br>truncatesc_ufid_on_generated</p>

2024-08-20 22:31 UTC, aakash10292 commented
cdb2test   Aug 20 14:06:09 2024  in-comdb2db aar_alias.R20240820.5

2024-08-20 22:31 UTC, merged