Add snapshot configuration tests
bloomberg/comdb2 pull request #4608
Opened 2024-08-14 18:37 UTC by morgando

The changes in this PR add snapshot configuration tests and encapsulate logic for disabling newsi.

2024-08-14 20:52 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-08-15 15:24 UTC, aakash10292 approved these changes
LGTM

2024-08-16 19:28 UTC, aakash10292 approved these changes

2024-08-16 23:43 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/575 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>copyschema_timepart [setup failure]<br>writes_remsql_names_rte_connect_generated [setup failure]<br>truncatesc</p>

2024-08-19 14:37 UTC, morgando commented
`cdb2test   Aug 16 16:31:28 2024  in-comdb2db add_siconfig_test.R20240816.4`

2024-08-19 14:47 UTC, merged