Fix mac build
bloomberg/comdb2 pull request #4609
Opened 2024-08-14 21:29 UTC by morgando

2024-08-14 22:22 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-08-14 22:43 UTC, markhannum approved these changes

2024-08-20 02:28 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/575 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>writes_remsql_fdbpushredirect_generated [setup failure]<br>vutf8_rowlocks_off_osql_odh_blob_generated [setup failure]<br>basic_rowlocks_generated [setup failure]<br>sc_resume_logicalsc_generated<br>truncatesc_ufid_on_generated</p>

2024-08-20 14:48 UTC, markhannum approved these changes

2024-08-20 15:00 UTC, merged