Fix elect-highest-committed-gen for full-recovery.
bloomberg/comdb2 pull request #4610
Opened 2024-08-14 21:49 UTC by markhannum

Test and fix for the elect-highest-committed-gen failure.  A new test, 'nogen_full_recovery', shows how the original bug unwound data, how we can lose data when elect-highest-committed-gen is not enabled, and how the non-bugged version of this tunable solves that case.  The README file in the testcase directory describes each test in detail.

2024-08-15 11:09 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-08-15 14:17 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-08-15 20:00 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-08-16 13:11 UTC, mponomar approved these changes

2024-08-16 13:27 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-08-16 13:45 UTC, merged