Stop storing utxnid 0 in commit LSN map
bloomberg/comdb2 pull request #4613
Opened 2024-08-15 16:08 UTC by morgando

The changes in this PR prevent transactions with utxnid 0 from being added to the commit LSN map -- txnid/utxnid 0 is a dummy transaction ID used by the database for internal transactions. It does not make sense to have these transactions in the map since they are not uniquely identified.

2024-08-15 18:02 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-08-15 23:27 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-08-20 15:28 UTC, markhannum approved these changes

2024-08-20 22:03 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/571 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>timepart_retention1 [setup failure]<br>comdb2sys [setup failure]<br>sicomplex2 [setup failure]<br>sc_resume<br>online_compaction<br>union_parallel</p>

2024-08-21 14:13 UTC, merged