Fix and test commit LSN map log deletion
bloomberg/comdb2 pull request #4622
Opened 2024-08-20 01:30 UTC by morgando

The changes in this PR fix bugs in the commit LSN map related to log deletion and update the test suite to catch the failing cases.

Bugs:
- `highest_commit_lsn` is not updated everywhere it should be when a record is added to the map.
- Deleting the last logfile in the map does not reset `smallest_logfile` to -1.

2024-08-20 05:48 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/576 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>vutf8_rowlocks [setup failure]<br>ssl_remsql_fdbpush_generated [setup failure]<br>blob2 [setup failure]<br>sc_resume_logicalsc_generated<br>sc_transactional_rowlocks_generated<br>commit_lsn_map_delete_generated<br>truncatesc_ufid_on_generated</p>

2024-08-20 14:19 UTC, morgando commented on berkdb/txn/txn_util.c
>  {
I re-wrote most of this function so I would suggest just reviewing the full function instead of the diff.

2024-08-20 14:47 UTC, morgando commented on tests/commit_lsn_map.test/runit
> -{
Same with this test -- read the full test instead of the diff

2024-08-20 16:04 UTC, morgando commented on berkdb/txn/txn_util.c
> +	DB_TXN_COMMIT_MAP * const txmap = dbenv->txmap;
There may be no commit in a logfile. Must handle this case.

2024-08-20 16:04 UTC, morgando commented on berkdb/txn/txn_util.c
> +	hash_del(txmap->logfile_lists, &del_log);
This does not take the key as an argument

2024-08-20 17:46 UTC, markhannum approved these changes

2024-08-21 01:18 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/572 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>siasof [setup failure]<br>ssl_remsql_fdbpushredirect_generated [setup failure]<br>union_parallel [setup failure]<br>sc_resume_logicalsc_generated<br>analyze_exit_immediately<br>auth</p>

2024-08-21 14:33 UTC, morgando commented
`cdb2test   Aug 20 17:58:49 2024  in-comdb2db fix_clm_log_del.R20240820.7`

2024-08-21 14:45 UTC, merged