Remove obsolete sqlwrtimeoutms tunable
bloomberg/comdb2 pull request #4635
Opened 2024-08-23 18:27 UTC by akshatsikarwar

/plugin-branch nosqlwrtimeout

2024-08-23 18:41 UTC, mponomar approved these changes

2024-08-24 04:18 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-08-26 12:49 UTC, akshatsikarwar commented
```
cdb2test   Aug 24 00:17:30 2024  in-comdb2db nosqlwrtimeout.R20240823.8
```

2024-08-26 15:04 UTC, merged

2024-08-26 17:03 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/574 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_newuniq [setup failure]<br>init_sc_race [setup failure]<br>ssl_remsql_fdbpush_generated [setup failure]<br>analyze_exit_immediately<br>truncatesc</p>