set identity callbacks correctly
bloomberg/comdb2 pull request #4647
Opened 2024-08-28 19:15 UTC by mohitkhullar

/plugin-branch fix_identity_cb

2024-08-28 19:15 UTC, mohitkhullar commented
/plugin-branch fix_identity_cb

2024-08-28 23:34 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/574 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>writes_remsql_names [setup failure]<br>verify_error_partial_index_off_generated [setup failure]<br>schemalk_extralock_generated<br>sc_resume<br>truncatesc<br>truncatesc_ufid_on_generated<br>dbcreate</p>

2024-08-29 17:59 UTC, mponomar approved these changes

2024-08-30 04:20 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>6/574 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>copyschema_timepart [setup failure]<br>writes_remsql_names [setup failure]<br>basic_nogenid48_generated [setup failure]<br>sc_resume<br>sc_partial_datacopy_logicalsc_generated<br>dbcreate</p>

2024-09-03 10:42 UTC, merged