8.0: Fix leaks in comdb2_files
bloomberg/comdb2 pull request #4651
Opened 2024-08-29 18:33 UTC by morgando

8.0 port of #4648

2024-08-30 17:48 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>8/553 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_lotsoftables_logicalsc_generated [setup failure]<br>writes_remsql_fdbpushredirect_generated [setup failure]<br>vutf8_rowlocks [setup failure]<br>comdb2_files<br>phys_rep_via_comdb2_files_generated<br>lostwrite<br>truncatesc_offline_generated</p>

2024-08-31 06:57 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/553 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>truncatesc_ufid_on_generated<br>truncatesc_offline_generated</p>

2024-09-05 21:04 UTC, LiSodium submitted a review, later dismissed

2024-09-06 19:56 UTC, markhannum approved these changes

2024-09-07 14:32 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/553 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>writes_remsql_names_fdbpush_generated [setup failure]<br>verify_error [setup failure]<br>lostwrite<br>truncatesc_offline_generated</p>

2024-09-09 15:16 UTC, merged