[8.0]{176316843}: Adding local-cache flag to clnt
bloomberg/comdb2 pull request #4689
Opened 2024-09-13 15:43 UTC by riverszhang89

These changes would help us identify whether a connection is truly leaked, or is being cached in the client process.

2024-09-15 01:44 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>10/556 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>autoanalyze [setup failure]<br>timepart_trunc_serialsc_generated<br>timepart_trunc<br>diskspace_nollmeta_nostripe_generated<br>diskspace_nollmeta<br>comdb2sys_queueodh_generated<br>comdb2sys_pagesize_generated<br>comdb2sys<br>truncatesc<br>truncatesc_offline_generated</p>

2024-09-26 22:13 UTC, morgando submitted a review, later dismissed

2024-10-08 19:06 UTC, morgando approved these changes

2024-10-08 19:07 UTC, riverszhang89 commented
@morgando Thanks for the review!

2024-10-08 19:07 UTC, merged