let open source run new tpt
bloomberg/comdb2 pull request #4695
Opened 2024-09-16 14:10 UTC by dorinhogea

The new tpt should be disabled only in BB build unless explicitely enabled.

2024-09-16 15:17 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/556 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_dups_logicalsc_generated [setup failure]<br>verify_error [setup failure]<br>sc_transactional_rowlocks_generated<br>timepart_trunc_serialsc_generated<br>timepart_trunc<br>tunables<br>truncatesc_offline_generated</p>

2024-09-18 18:57 UTC, mponomar approved these changes

2024-09-18 20:14 UTC, dorinhogea commented
@mponomar thank you

2024-09-18 20:15 UTC, merged

2024-09-18 20:53 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>5/556 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>writes_remsql_names_negativerowid_generated [setup failure]<br>sc_swapfields<br>sc_transactional_rowlocks_generated<br>lostwrite<br>truncatesc_offline_generated</p>