block creating a partition with shards matching existing shards
bloomberg/comdb2 pull request #4701
Opened 2024-09-17 15:22 UTC by dorinhogea

It only happens if we drop a legacy type time partition (which preserves its shards), then recreate the original table with the same name, and then finally altering that to match the configuration of the initial partition.   It is a fast fail, breaking sql.

2024-09-17 15:25 UTC, mponomar approved these changes

2024-09-18 00:49 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>7/556 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>simple_timepart_reptimeout_generated<br>simple_timepart<br>timepart_retention1<br>lostwrite<br>online_compaction<br>truncatesc_ufid_on_generated<br>truncatesc_offline_generated</p>

2024-09-19 15:53 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/556 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>timepart_changeretention [setup core dumped]<br>analyze_recover_deadlock [setup failure]<br>sc_truncate_lockorder_generated<br>sc_transactional_rowlocks_generated<br>truncatesc_offline_generated<br>ssl_remsql</p>

2024-09-19 18:01 UTC, mponomar approved these changes

2024-09-19 18:21 UTC, mponomar approved these changes

2024-09-19 19:08 UTC, dorinhogea commented
@mponomar thank you

2024-09-19 19:08 UTC, merged