Add set stmt for typessql 8.0
bloomberg/comdb2 pull request #4702
Opened 2024-09-17 17:51 UTC by chands10

8.0 version of https://github.com/bloomberg/comdb2/pull/4671

2024-09-17 18:24 UTC, mponomar approved these changes

2024-09-17 18:29 UTC, chands10 commented
Thanks Mike!

2024-09-18 01:43 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/556 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>autoanalyze [setup failure]<br>fdb_push_rte_connect_generated [setup failure]<br>mismatch_class_remsql_fdbpush_generated [setup failure]<br>lostwrite<br>union_parallel<br>truncatesc<br>truncatesc_offline_generated<br>dbcreate</p>

2024-09-23 15:04 UTC, chands10 commented
cdb2test   Sep 17 21:30:18 2024  in-comdb2db set_typessql_8.0.R20240917.7

2024-09-23 15:04 UTC, merged