Address commit LSN map recovery bug
bloomberg/comdb2 pull request #4711
Opened 2024-09-20 19:16 UTC by morgando

The database recovers to a point prior to the end of the log in the case of log truncation and in the case of point-in-time recovery. Therefore, it may unroll transactions that were formerly committed if they committed after that recovery point. These transactions are not currently removed from the commit LSN map: This is a bug. The changes in this PR fix this bug.

2024-09-20 19:22 UTC, morgando commented on berkdb/txn/txn_rec.c
> -					info, argp->txnid->txnid, argp->opcode, lsnp);
This seems extraneous

2024-09-20 23:33 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/578 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>autoanalyze [setup failure]<br>rowlock_update [setup failure]<br>sc_resume_logicalsc_generated<br>analyze_exit_immediately<br>commit_lsn_map_delete_generated<br>snap_ha_retry_newsi_generated<br>sc_resume<br>truncatesc_ufid_on_generated</p>

2024-09-24 18:14 UTC, markhannum approved these changes

2024-09-25 01:09 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>10/579 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_tableversion [setup failure]<br>sc_dups_logicalsc_generated [setup failure]<br>siasofupdate [setup failure]<br>sc_resume_logicalsc_generated<br>sc_transactional_rowlocks_generated<br>online_compaction<br>commit_lsn_map_delete_generated<br>snap_ha_retry_newsi_generated<br>truncatesc<br>truncatesc_ufid_on_generated</p>

2024-09-25 19:00 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/579 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate [setup failure]<br>copyschema_timepart [setup failure]<br>union_parallel [setup failure]<br>sc_truncate_lockorder_generated<br>sc_transactional_rowlocks_generated<br>truncatesc_ufid_on_generated<br>snap_ha_retry_newsi_generated<br>truncatesc<br>dbcreate</p>

2024-09-25 19:34 UTC, markhannum approved these changes

2024-09-25 20:09 UTC, morgando commented
`cdb2test   Sep 25 11:37:47 2024  in-comdb2db modsnap_recovery_undo_2.R20240925.3`

2024-09-25 20:09 UTC, merged