{176603116}: Improvements to the scope of valueFromFunction()
bloomberg/comdb2 pull request #4714
Opened 2024-09-23 18:21 UTC by riverszhang89

This patch ports https://sqlite.org/src/info/a0f39419cb5bdfa4, and adds tests for it.

2024-09-23 19:22 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-09-24 16:43 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/578 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>writes_remsql_fdbpushredirect_generated [setup failure]<br>verify_error [setup failure]<br>ssl_remsql [setup failure]<br>sc_resume_logicalsc_generated<br>sc_transactional_rowlocks_generated<br>snap_ha_retry_newsi_generated<br>truncatesc_ufid_on_generated</p>

2024-09-24 18:00 UTC, chands10 approved these changes

2024-09-25 12:19 UTC, riverszhang89 commented
@chands10 Thanks for the review!

2024-09-25 12:19 UTC, merged