{176689231}: Porting SQLite fix for LEFT-JOIN using OR that matches no rows
bloomberg/comdb2 pull request #4728
Opened 2024-09-26 12:43 UTC by riverszhang89

This patch backports https://www.sqlite.org/src/info/f02030b3403d6773

2024-09-26 18:03 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>12/579 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>blkseq_race [setup failure]<br>writes_remsql_names_fdbpushredirect_generated [setup failure]<br>writes_remsql_names_fdbpush_generated [setup failure]<br>verify_error [setup failure]<br>sc_remsql [setup failure]<br>misstable_remsql_rte_connect_generated [setup failure]<br>phys_rep_tiered<br>commit_lsn_map_delete_generated<br>snap_ha_retry_newsi_generated<br>truncatesc_ufid_on_generated</p>

2024-09-26 18:37 UTC, riverszhang89 commented
```
cdb2test   Sep 26 10:45:53 2024  in-comdb2db sqlite_left_join_or_null.R20240926.2
```

2024-09-26 19:28 UTC, morgando approved these changes

2024-09-27 11:28 UTC, riverszhang89 commented
@morgando Thank you for the code review!

2024-09-27 11:28 UTC, merged