Implement comdb2_filenames
bloomberg/comdb2 pull request #4730
Opened 2024-09-26 18:48 UTC by morgando

If we're just interested in knowing the filenames in the database's directory, then selecting them from `comdb2_files` is inefficient because `comdb2_files` will scan the contents of every file (creating a distinct record for every chunk in a file).

The changes in this PR provide a system table called `comdb2_filenames` which provides a method for accessing a database's file names that doesn't involve scanning the contents of files.

Alternatively `comdb2_files` could be optimized to handle selects of non-contents more efficiently.

2024-09-26 23:03 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>225/579 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_inserts_deletes_logicalsc_generated [setup failure]<br>ssl_remsql_fdbpushredirect_generated [setup failure]<br>comdb2sys_queueodh_generated<br>comdb2sys_pagesize_generated<br>comdb2sys<br>auth_twofiles_generated<br>auth_queueodh_generated<br>auth<br>userschema_queueodh_generated<br>userschema</p>

2024-09-27 18:53 UTC, mponomar approved these changes

2024-09-27 20:44 UTC, morgando commented
`cdb2test   Sep 26 15:56:05 2024  in-comdb2db comdb2_filenames.R20240926.5`

2024-09-27 20:44 UTC, morgando commented
Thanks Mike!

2024-09-27 20:45 UTC, merged