Enable IAM user metrics with low verbosity
bloomberg/comdb2 pull request #4743
Opened 2024-09-30 15:52 UTC by mohitkhullar

changes already pushed to  bbplugins

2024-09-30 20:10 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>11/580 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>simple_timepart [setup failure]<br>updcolsbug [setup failure]<br>basic_sslnoproto_generated [setup failure]<br>sc_resume<br>truncatesc_ufid_on_generated<br>analyze_exit_immediately<br>snap_ha_retry_newsi_generated<br>diskspace_nollmeta_nostripe_generated<br>tunables</p>

2024-10-01 19:23 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/580 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>online_compaction<br>commit_lsn_map_delete_generated<br>snap_ha_retry_newsi_generated<br>truncatesc<br>dbcreate</p>

2024-10-30 15:50 UTC, mponomar approved these changes

2024-10-30 17:51 UTC, mohitkhullar commented
Thanks

2024-10-30 17:51 UTC, merged