Fix mac build
bloomberg/comdb2 pull request #4753
Opened 2024-10-07 19:26 UTC by mohitkhullar

https://github.com/bloomberg/comdb2/pull/4672

.../comdb2/bdb/bdb_api.h:2349:26: error: redefinition of typedef 'bias_info' is a C11 feature [-Werror,-Wtypedef-redefinition]
typedef struct bias_info bias_info;
                         ^
.../comdb2/db/sqlglue.h:17:26: note: previous definition is here
typedef struct bias_info bias_info;

.../comdb2/bbinc/blob_buffer.h:54:3: error: redefinition of typedef 'blob_buffer_t' is a C11 feature [-Werror,-Wtypedef-redefinition]
} blob_buffer_t;
  ^
.../comdb2/comdb2/db/sqlglue.h:17:28: note: previous definition is here
typedef struct blob_buffer blob_buffer_t;

2024-10-07 20:04 UTC, morgando approved these changes

2024-10-08 08:18 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/584 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_inserts [setup failure]<br>sc_newuniq_logicalsc_generated [setup failure]<br>snap_ha_retry_newsi_generated</p>

2024-10-08 17:24 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-10-08 22:03 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/584 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>fdb_push_redirect_generated [setup failure]<br>fdb_push [setup failure]<br>snap_ha_retry_newsi_generated<br>auth</p>

2024-10-11 14:43 UTC, merged

2024-10-11 14:43 UTC, mohitkhullar commented
Thanks