Fail modsnap if gen changes
bloomberg/comdb2 pull request #4755
Opened 2024-10-08 14:56 UTC by morgando

The changes in this PR fix the following bug:

1) a modsnap transaction latches its start LSN
2) truncate runs
3) the modsnap transaction sees new updates in its selects since these updates have commit LSNs lower than the latched snapshot start LSN

The fix in this PR fail a modsnap transaction when it tries to open a cursor if the db's generation has changed.

2024-10-08 14:58 UTC, morgando commented
/nobuild

2024-10-08 14:59 UTC, morgando commented
/skipbuild

2024-10-08 16:05 UTC, morgando commented
/runtests

2024-10-09 01:25 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/585 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>fdb_push_rte_connect_generated [setup failure]<br>logfill_logput_window_generated<br>analyze_exit_immediately<br>commit_lsn_map_delete_generated<br>snap_ha_retry_newsi_generated</p>

2024-10-10 23:15 UTC, markhannum approved these changes

2024-10-16 04:28 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>6/585 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_partial_datacopy_logicalsc_generated [setup failure]<br>sc_newuniq [setup failure]<br>sc_transactional_rowlocks_generated<br>analyze_exit_immediately<br>commit_lsn_map_delete_generated<br>snap_ha_retry_newsi_generated</p>

2024-10-17 18:18 UTC, morgando commented
`mdouglas47 Oct 16 12:47:17 2024  in-comdb2db trunc_snap.R20241016.3`

2024-10-18 21:19 UTC, merged