ignore utxnid 0 during recovery
bloomberg/comdb2 pull request #4760
Opened 2024-10-10 19:19 UTC by aakash10292

https://github.com/bloomberg/comdb2/pull/4613 explicitly avoids adding utxnid 0 to the commit_lsn_map. This patch Ignores the same during recovery . 

This patch is an attempt to fix rm test failures : 

NEW MASTER NODE pno-comdb2sun2
trying writelock (bdb_rep_verify 12), last writelock is bdb_rep_verify 0
__rep_process_message line 2159: got rep_verify_match count=2 for lsn [1][708252]
skip-recovery cannot skip, prev-commit=[1:713308] trunc-lsn=[1:708252]
__rep_dorecovery calling truncate with lsn [1:708252]
__db_find_recovery_start rc -30990
running forward pass from 1:705814 -> 1:718184
__env_openfiles: open files from lsn 1:705814
running backward pass from 1:705814 <- 1:718184
**__txn_commit_map_remove_nolock: Could not find transaction 0 in the map
__txn_regop_recover: Failed to remove 0 from the commit map**
Recovery function for LSN 1 713308 failed on backward pass
comdb2_recovery_cleanup starting for [1:708252] as REPLICANT

2024-10-10 19:33 UTC, markhannum approved these changes

2024-10-10 23:18 UTC, markhannum approved these changes

2024-10-10 23:33 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/584 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>copyschema_timepart [setup failure]<br>writes_remsql_fdbpushredirect_generated [setup failure]<br>osql_cleanup<br>online_compaction<br>commit_lsn_map_delete_generated<br>snap_ha_retry_newsi_generated</p>

2024-10-11 00:18 UTC, aakash10292 commented
cdb2test   Oct 10 16:12:39 2024  in-comdb2db aar_utxnid_recover.R20241010.1

2024-10-11 00:19 UTC, merged