Fix IAM for time partitioned tables 8
bloomberg/comdb2 pull request #4762
Opened 2024-10-11 14:49 UTC by mohitkhullar

2024-10-11 23:23 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/558 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>blkseq_race [setup failure]<br>cdb2_close<br>lostwrite<br>incoh_remsql_rte_connect_generated<br>truncatesc_offline_generated</p>

2024-10-14 18:10 UTC, markhannum approved these changes

2024-10-15 05:03 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/558 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_tableversion_logicalsc_generated [setup failure]<br>truncatesc_offline_generated</p>

2024-10-15 12:37 UTC, mohitkhullar commented
Thanks

2024-10-15 12:37 UTC, merged