{176908531} UPSERT again
bloomberg/comdb2 pull request #4763
Opened 2024-10-11 18:10 UTC by akshatsikarwar

/silent

2024-10-11 18:13 UTC, mponomar approved these changes

2024-10-11 18:13 UTC, morgando approved these changes

2024-10-12 03:28 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/584 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>writes_remsql_names_negativerowid_generated [setup failure]<br>sc_transactional_rowlocks_generated<br>commit_lsn_map_delete_generated<br>snap_ha_retry_newsi_generated<br>union_parallel<br>auth<br>dbcreate</p>

2024-10-14 13:33 UTC, akshatsikarwar commented
`cdb2test   Oct 11 20:17:36 2024  in-comdb2db upsert.R20241011.5`

2024-10-14 13:33 UTC, merged