fix read_committed test
bloomberg/comdb2 pull request #4773
Opened 2024-10-16 16:34 UTC by aakash10292

This patch fixes a few things in read_committed test: 
1.) We weren't redirecting stderr to stdout
2.) Print diff incase of failure to make it easier to inspect the failures
3.) Fix q22 test

2024-10-16 20:47 UTC, morgando approved these changes

2024-10-17 07:08 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/585 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_inserts_deletes_logicalsc_generated [setup failure]<br>timepart_frgncnst [setup failure]<br>sc_tableversion_logicalsc_generated [setup failure]<br>writes_remsql_fdbpushredirect_generated [setup failure]<br>fdb_push_rte_connect_generated [setup failure]<br>analyze<br>snap_ha_retry_newsi_generated<br>auth</p>

2024-10-17 11:38 UTC, aakash10292 commented
cdb2test   Oct 16 23:35:33 2024  in-comdb2db aar_fix_recom_test.R20241016.11

2024-10-17 11:38 UTC, aakash10292 commented
@morgando thanks for the review!

2024-10-17 11:39 UTC, merged