Fix recom test (8.0)
bloomberg/comdb2 pull request #4774
Opened 2024-10-16 18:35 UTC by aakash10292

Porting https://github.com/bloomberg/comdb2/pull/4773

2024-10-16 20:48 UTC, morgando approved these changes

2024-10-17 08:02 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/558 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lock_views [setup failure]<br>sc_transactional_rowlocks_generated<br>truncatesc_offline_generated</p>

2024-10-17 11:39 UTC, aakash10292 commented
cdb2test   Oct 17 03:55:09 2024  in-comdb2db aar_fix_recom_test_8.R20241017.0

2024-10-17 11:39 UTC, aakash10292 commented
@morgando thanks again!

2024-10-17 11:40 UTC, merged