Put min() in utils
bloomberg/comdb2 pull request #4778
Opened 2024-10-18 17:57 UTC by morgando

Put a min function in utils that doesn't double-evaluate the inputs.

2024-10-18 18:01 UTC, LiSodium approved these changes

2024-10-18 18:01 UTC, LiSodium commented
lgtm

2024-10-18 22:13 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/585 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_multiddl_generated [setup failure]<br>scupdates_logicalsc_generated [setup failure]<br>sc_transactional_rowlocks_generated<br>snap_ha_retry_newsi_generated<br>dbcreate</p>

2024-10-21 14:40 UTC, morgando commented
`cdb2test   Oct 18 14:48:43 2024  in-comdb2db min.R20241018.2`

2024-10-21 14:40 UTC, merged