Cleanup modsnap code
bloomberg/comdb2 pull request #4785
Opened 2024-10-24 19:47 UTC by morgando

The changes in this PR

1. Remove redundant code
2. Refactor `bdb_get_modsnap_start_state`
3. Update out of date comments / variable names
4. Fix bug in `__txn_commit_map_delete_logfile_list`

2024-10-24 19:49 UTC, morgando commented on berkdb/txn/txn_util.c
> +			successor = hash_find(txmap->logfile_lists, &txmap->highest_logfile);
This should not have been `smallest_logfile`

2024-10-24 20:55 UTC, morgando commented on berkdb/rep/rep_record.c
Removed duplication here (the if and else block were basically the same)

2024-10-24 20:56 UTC, morgando commented on bdb/tran.c
> -        if ((rc = __txn_commit_map_get_highest_checkpoint_lsn(dbenv, &last_checkpoint_lsn, 0)) != 0) {
Removed `__txn_commit_map_get_highest_checkpoint_lsn` because we can just use `bdb_checkpoint_list_get_ckplsn_before_lsn`

2024-10-24 20:56 UTC, morgando commented on bdb/tran.c
> -        if ((rc = __txn_commit_map_get_modsnap_start_lsn(dbenv, &modsnap_start_lsn, 0)) != 0) {
Removed `__txn_commit_map_get_modsnap_start_lsn` because we can just use `bdb_get_current_lsn`

2024-10-25 01:28 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/586 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>snap_ha_retry_newsi_generated</p>

2024-11-01 18:27 UTC, markhannum approved these changes

2024-11-04 16:19 UTC, markhannum approved these changes

2024-11-04 20:48 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/586 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated [setup failure]<br>sc_lock_inversion [setup failure]<br>writes_remsql [setup failure]<br>phys_rep_tiered<br>analyze_exit_immediately<br>mem_protobuf<br>snap_ha_retry_newsi_generated</p>

2024-11-07 15:57 UTC, merged