Update appsock exhausted error code
bloomberg/comdb2 pull request #4786
Opened 2024-10-25 15:25 UTC by chands10

Problem: return code -110 is already taken by CDB2ERR_SCHEMA
Replace CDB2__ERROR_CODE__APPSOCK_LIMIT (-110) with CDB2ERR_APPSOCK_LIMIT (-23) so it is distinct from CDB2ERR_SCHEMA

This will be used by cdb2api in the future to fix exhausted appsock bug (currently doesn't retry on other nodes when reaches limit)

Don't think code -110 is parsed anywhere currently

2024-10-25 15:26 UTC, chands10 commented
Probably can't remove `    APPSOCK_LIMIT           = -110;` from sqlresponse.proto?

2024-10-25 19:53 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/586 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_multiddl_generated [setup failure]<br>oflowaddrem [setup failure]<br>basic_rowset_generated [setup failure]<br>cldeadlock<br>logfill_logput_window_generated<br>snap_ha_retry_newsi_generated</p>

2024-10-28 23:12 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/586 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated [setup failure]<br>scupdates_logicalsc_generated [setup failure]<br>writes_remsql_rte_connect_generated [setup failure]<br>snapshot_during_truncate<br>commit_lsn_map_delete_generated<br>snap_ha_retry_newsi_generated<br>auth</p>

2024-10-30 20:04 UTC, morgando approved these changes

2024-10-31 04:37 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/586 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>unionpar_maxqueue [setup failure]<br>replay_history [setup failure]<br>siasofupdate [setup failure]<br>blob_sanity [setup failure]<br>snap_ha_retry_newsi_generated<br>ssl_remsql_fdbpushredirect_generated</p>

2024-10-31 14:28 UTC, merged