Increase precision of modsnap truncate failure
bloomberg/comdb2 pull request #4790
Opened 2024-10-28 19:26 UTC by morgando

The changes in this PR improve upon the failure implemented in #4755: 

The changes in #4755 disallow a  modsnap transaction from opening a cursor whenever there's a gen change. This is a catch-all method that can unnecessarily fail transactions.

The changes in this PR remove these unnecessary failures by only disallowing a modsnap transaction from opening a cursor if we truncate to an lsn below its start lsn.

2024-10-29 00:08 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/586 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>simple_timepart_reptimeout_generated [setup failure]<br>sc_truncate_multiddl_generated [setup failure]<br>fdb_push_redirect_generated [setup failure]<br>mismatch_class_remsql [setup failure]<br>verify_db_parallel_generated [setup failure]<br>sc_transactional_rowlocks_generated<br>snap_ha_retry_newsi_generated<br>ssl_remsql_fdbpushredirect_generated</p>

2024-11-04 19:21 UTC, markhannum approved these changes

2024-11-08 21:19 UTC, morgando commented
`mdouglas47 Nov  7 17:59:00 2024  in-comdb2db better_trunc_failure.R20241107.7`

2024-11-08 22:20 UTC, markhannum approved these changes

2024-11-08 22:24 UTC, merged