Nb getnameinfo
bloomberg/comdb2 pull request #4792
Opened 2024-10-28 22:18 UTC by akshatsikarwar

/silent

2024-10-28 22:18 UTC, akshatsikarwar commented
/silent

2024-10-29 08:35 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>10/586 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>comdb2sys [setup failure]<br>sc_dups [setup failure]<br>load_cache_autocache_generated [setup failure]<br>writes_remsql_names_fdbpushredirect_generated [setup failure]<br>basic_rowset_generated [setup failure]<br>sc_truncate_multiddl_generated<br>online_compaction<br>comdb2sys_queueodh_generated<br>snapshot_during_truncate<br>snap_ha_retry_newsi_generated</p>

2024-10-29 13:15 UTC, markhannum approved these changes

2024-10-29 13:44 UTC, merged

2024-10-29 15:43 UTC, akshatsikarwar commented
`cdb2test   Oct 29 01:00:23 2024  in-comdb2db nb-getnameinfo.R20241029.0`