query blocking replication
bloomberg/comdb2 pull request #4817
Opened 2024-11-04 20:10 UTC by akshatsikarwar

/silent

2024-11-05 17:16 UTC, roborivers requested changes
.

2024-11-07 00:40 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>545/586 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>dohsql_leaks<br>simple_timepart_reptimeout_generated<br>sc_timepart_multiddl_generated<br>sc_timepart_logicalsc_generated<br>sc_timepart<br>systable_locking<br>truncatesc<br>sicountbug<br>disttxn<br>sidupidx3</p>

2024-11-14 21:19 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>495/586 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>dohsql_leaks<br>simple_timepart_reptimeout_generated<br>simple_timepart<br>sc_timepart_logicalsc_generated<br>sc_timepart<br>yast_stat4scan_generated<br>yast<br>timepart_auth<br>systable_locking<br>truncatesc</p>

2024-11-15 16:16 UTC, roborivers requested changes
.

2024-11-18 11:53 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>228/586 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_inserts_deletes_logicalsc_generated [setup failure]<br>writes_remsql_names_negativerowid_generated [setup failure]<br>ssl_remsql_fdbpushredirect_generated [setup failure]<br>truncatesc<br>online_compaction<br>tablelocks<br>newsi_on_master<br>snapisol_partial_index_off_generated<br>snapisol_noearly_generated<br>snapisol</p>

2024-11-21 19:34 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>81/588 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>autoanalyze [setup failure]<br>misstable_remsql [setup failure]<br>truncatesc<br>newsi_on_master<br>snapisol_partial_index_off_generated<br>snapisol_noearly_generated<br>snapisol<br>snap_ha_retry_newsi_generated<br>snap_ha_retry<br>tunables</p>

2024-11-23 01:01 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-11-26 19:21 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>12/588 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>comdb2sys [setup failure]<br>serialstep [setup failure]<br>truncatesc<br>analyze_exit_immediately<br>snap_ha_retry_newsi_generated<br>union_parallel<br>sirandtest<br>sicountbug2<br>sirandtest2<br>sc_partial_datacopy_logicalsc_generated</p>

2024-11-26 20:23 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/588 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>misstable_remsql_rte_connect_generated [setup failure]<br>fdb_push_redirect_generated [setup failure]<br>truncatesc<br>snap_ha_retry_newsi_generated<br>cldeadlock</p>

2024-12-02 19:53 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>138/589 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>leakcheck [setup failure]<br>blkseq_race [setup failure]<br>comdb2sys [setup failure]<br>clientstats_leaks [setup failure]<br>writes_remsql_names_fdbpushredirect_generated [setup failure]<br>truncatesc<br>online_compaction<br>comdb2sys_pagesize_generated<br>snap_ha_retry_newsi_generated<br>union_parallel</p>

2024-12-03 13:56 UTC, akshatsikarwar commented
/plugin-branch long-join

2024-12-13 00:10 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>349/592 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>simple_timepart [setup failure]<br>sc_truncate_lockorder_generated [setup failure]<br>replay_history [setup failure]<br>sc_lock_inversion [setup failure]<br>timepart_constraints [setup failure]<br>selectv_recom_range [setup failure]<br>selectv_rcode_serialize_reads_like_writes_generated [setup failure]<br>truncatesc<br>phys_rep_perf<br>online_compaction</p>

2024-12-13 21:58 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/589 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_constraints_logicalsc_generated<br>phys_rep_perf<br>snap_ha_retry_newsi_generated<br>tunables<br>truncatesc</p>

2024-12-16 22:44 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>8/594 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>osql_cleanup<br>truncatesc<br>phys_rep_perf<br>logarchive<br>snapisol_noearly_generated<br>snap_ha_retry_newsi_generated<br>fdb_compat_rte_connect_generated<br>simple_remsql_whitelist_generated</p>

2024-12-17 01:47 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/594 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>truncatesc<br>phys_rep_perf<br>online_compaction<br>logarchive<br>snapisol_partial_index_off_generated<br>snapisol_noearly_generated<br>snap_ha_retry_newsi_generated<br>simple_remsql_whitelist_generated<br>cldeadlock</p>

2025-01-06 17:23 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>577/598 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sicountbug<br>serial_randtest2<br>verify_writes<br>updater_latency<br>ixentry_order<br>socksql_master_swings<br>odh_blobs<br>scindex<br>scindex_logicalsc_generated<br>phys_rep_perf</p>

2025-01-07 16:38 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>514/598 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sicountbug2 [setup failure]<br>truncatesc<br>odh_blobs<br>scindex<br>scindex_logicalsc_generated<br>phys_rep_perf<br>phys_rep_tiered_nosource_generated<br>phys_rep_tiered<br>phys_rep_tiered_firstfile_generated<br>sc_constraints</p>

2025-01-08 19:57 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>409/598 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>sc_truncate [setup failure]<br>sc_lotsoftables_logicalsc_generated [setup failure]<br>sc_inserts [setup failure]<br>comdb2sys_pagesize_generated [setup failure]<br>lock_views<br>truncatesc<br>phys_rep_perf<br>sc_versmismatch<br>recom_replay</p>

2025-01-09 17:40 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>337/598 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_lotsoftables_logicalsc_generated [setup failure]<br>sc_lotsoftables [setup failure]<br>leakcheck [setup failure]<br>selectv_recom_range [setup failure]<br>sc_truncate<br>phys_rep_perf<br>printlog<br>comdb2sys_queueodh_generated<br>comdb2sys<br>comdb2sys_pagesize_generated</p>

2025-01-10 20:31 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>233/598 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_perf<br>printlog<br>comdb2sys_queueodh_generated<br>comdb2sys<br>comdb2sys_pagesize_generated<br>autoanalyze<br>diskspace_nollmeta<br>diskspace_nollmeta_nostripe_generated<br>snapisol_partial_index_off_generated<br>snap_ha_retry_newsi_generated</p>

2025-01-13 22:20 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>101/598 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_remsql_fdbpush_generated [setup failure]<br>fdb_compat<br>phys_rep_perf<br>sc_repeated_updates_logicalsc_generated<br>reco-ddlk-sql<br>diskspace_nollmeta_nostripe_generated<br>diskspace_nollmeta<br>snapisol_partial_index_off_generated<br>snap_ha_retry_newsi_generated<br>ddl_csc2</p>

2025-01-14 19:20 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>10/596 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>reco-ddlk-sql<br>diskspace_nollmeta_nostripe_generated<br>diskspace_nollmeta<br>snapisol_noearly_generated<br>snap_ha_retry_newsi_generated<br>simple_remsql_whitelist_generated<br>tunables<br>cldeadlock<br>dbcreate<br>disttxn</p>

2025-01-15 20:04 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/596 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>simple_remsql_whitelist_generated<br>reco-ddlk-sql</p>

2025-01-15 20:34 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/596 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>simple_remsql_whitelist_generated<br>tunables<br>sc_downgrade<br>reco-ddlk-sql<br>dbcreate<br>disttxn</p>

2025-01-16 18:21 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/596 tests failed</b> &#x26A0;.</p>

2025-01-21 20:16 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2025-01-21 22:11 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/596 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>reco-ddlk-sql<br>nogen_full_recovery_disable_generated</p>

2025-01-22 20:06 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/596 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>analyze_exit_immediately</p>

2025-01-23 15:46 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/596 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>osql_cleanup<br>incremental_backup_usenames<br>incoherent_slow<br>pmux_sqlite_file_generated</p>

2025-01-23 18:09 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/596 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>osql_cleanup<br>analyze_exit_immediately<br>fdb_compat_rte_connect_generated</p>

2025-01-24 16:03 UTC, akshatsikarwar commented
/silent

2025-01-24 16:49 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/596 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>pmux_sqlite_file_generated<br>disttxn</p>

2025-01-27 20:51 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/596 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>fdb_compat</p>

2025-01-29 14:45 UTC, mponomar approved these changes

2025-01-29 14:46 UTC, merged