Update tracking structures during log deletion
bloomberg/comdb2 pull request #4826
Opened 2024-11-06 20:02 UTC by morgando

The changes in this PR delete from the checkpoint list and the timestamp-to-lsn mapping structure when a logfile is deleted if modsnap is enabled.

2024-11-06 20:03 UTC, morgando commented on bdb/file.c
> -                }
The above block was duplicated. Consolidated to block following line 3900

2024-11-07 07:08 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/586 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>unionpar_maxqueue [setup failure]<br>leakcheck [setup failure]<br>basic_ssl_generated [setup failure]<br>basic_nogenid48_generated [setup failure]<br>snapshot_during_truncate<br>timepart_trunc<br>snap_ha_retry_newsi_generated<br>dbcreate</p>

2024-11-07 22:00 UTC, riverszhang89 approved these changes

2024-11-11 16:11 UTC, morgando commented
`cdb2test   Nov  6 22:48:53 2024  in-comdb2db modsnap_logdel.R20241106.12`

2024-11-11 16:11 UTC, morgando commented
Thanks Rivers!

2024-11-11 16:11 UTC, merged