[8.0] Keeping track of network wait time to client
bloomberg/comdb2 pull request #4829
Opened 2024-11-08 13:58 UTC by riverszhang89

This patch keeps track of how much time we are blocked on network IO to client, for instance:

```
11/06 18:57:56: LONG REQUEST 9562 msec ...
11/06 18:57:56:   sql=select * from jobs, sql=select * from jobs, ncols=10
11/06 18:57:56:   netwaitms=9148, rowcount=48445, cost=48454.000000
```

2024-11-08 14:17 UTC, mponomar reviewed
This is great, thank you.  Maybe add to eventlog so we have this data per query?

2024-11-08 15:04 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/559 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>truncatesc_offline_generated<br>dbcreate</p>

2024-11-29 10:14 UTC, morgando approved these changes
LGTM!

2024-11-29 10:14 UTC, morgando commented on net/sqlwriter.c
> +        }
Nitpick: Maybe the other state changes to `writer` that happen here could also go into `update_writer_state`? (like setting `writer->bad` and `writer->sent_at`)

2024-11-29 10:14 UTC, morgando commented on tests/reqlog_netwait.test/runit
> +cdb2sql ${CDB2_OPTIONS} --host $mach $dbnm "EXEC PROCEDURE sys.cmd.send('reql longreqfile <stdout>')" >/dev/null
TIL!

2024-12-02 14:18 UTC, merged