dist_txnid is already cleared when osql_sock_commit is called
bloomberg/comdb2 pull request #4844
Opened 2024-11-19 14:14 UTC by dorinhogea

Right now we are sending an rc over the remtran socket that is not being read by the current txn.

2024-11-19 14:26 UTC, markhannum submitted a review, later dismissed
tx Dorin!

2024-11-19 18:28 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/586 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>disttxn<br>phys_rep_tiered_nosource_generated<br>queuedb_rollover_noroll1_generated<br>snap_ha_retry_newsi_generated<br>dbcreate</p>

2024-11-20 02:38 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/586 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_lotsoftables_logicalsc_generated [setup failure]<br>autoanalyze [setup failure]<br>fdb_push_rte_connect_generated [setup failure]<br>disttxn<br>phys_rep_tiered<br>snap_ha_retry_newsi_generated</p>

2024-11-21 04:25 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/586 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>disttxn<br>snap_ha_retry_newsi_generated<br>dbcreate</p>

2024-11-21 19:48 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/588 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_lotsoftables_logicalsc_generated [setup failure]<br>sc_remsql_fdbpush_generated [setup failure]<br>snap_ha_retry_newsi_generated</p>

2024-11-22 15:39 UTC, markhannum approved these changes

2024-11-22 15:45 UTC, dorinhogea commented
@markhannum thank you

2024-11-22 15:45 UTC, merged