[WIP] Legacy queue migration
bloomberg/comdb2 pull request #4864
Opened 2024-11-27 14:32 UTC by LiSodium

To help us review your pull request, please consider providing an overview of the following:
* What is the type of the change (bug fix, feature, documentation and etc.) ?
* What are the current behavior and expected behavior, if this is a bugfix ?
* What are the steps required to reproduce the bug, if this is a bugfix ?
* What is the current behavior and new behavior, if this is a feature change or enhancement ?
* [Optional] Why is the new behavior better than the current behavior, if this is a feature change ?

2024-11-27 15:38 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-12-04 19:58 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/589 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_tableversion_logicalsc_generated [setup failure]<br>writes_remsql_names_fdbpush_generated [setup failure]<br>snap_ha_retry_newsi_generated<br>tunables</p>

2024-12-05 17:35 UTC, mponomar approved these changes

2024-12-05 22:17 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>286/591 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sirace [setup failure]<br>maxtable [setup failure]<br>sidupidx3 [setup failure]<br>sc_truncate_multiddl_generated [setup failure]<br>sc_redo_logicalsc_generated [setup failure]<br>scindex_deadlock_logicalsc_generated [setup failure]<br>rowlock_update [setup failure]<br>rawindex [setup failure]<br>phys_rep_perf<br>timepart_trunc_serialsc_generated</p>

2024-12-11 18:01 UTC, merged