Avoid reading llmeta disableskipscan tunable for all tables during analyze stat load.
bloomberg/comdb2 pull request #4886
Opened 2024-12-05 20:05 UTC by dorinhogea

Instead, read at the server start and when that tunable changes for any table (which is signaled by a scdone sc_analyze message).
This will eliminate redundant llmeta reads during a sqlite engine creation.

2024-12-05 21:49 UTC, aakash10292 approved these changes

2024-12-06 17:56 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>444/591 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_force [setup failure]<br>phys_rep_tiered [setup failure]<br>incrementalcopy [setup failure]<br>sc_truncate_multiddl_generated [setup failure]<br>incoh_remsql_rte_connect_generated [setup failure]<br>analyze_partial_index_off_generated [setup failure]<br>sc_lock_inversion [setup failure]<br>comdb2sys_queueodh_generated [setup failure]<br>systable_locking<br>phys_rep_perf</p>

2024-12-07 03:24 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>11/591 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>selectv_range [setup failure]<br>load_cache [setup failure]<br>blob2 [setup failure]<br>temp_table_cursor_leak<br>phys_rep_perf<br>online_compaction<br>comdb2sys_queueodh_generated<br>comdb2sys<br>comdb2sys_pagesize_generated<br>snap_ha_retry_newsi_generated</p>

2024-12-09 15:49 UTC, dorinhogea commented
@aakash10292 thank you

2024-12-09 15:49 UTC, merged