Logdel headroom bug
bloomberg/comdb2 pull request #4891
Opened 2024-12-10 14:22 UTC by morgando

2024-12-10 14:51 UTC, mponomar approved these changes

2024-12-10 15:42 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>21/564 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_upsert [setup failure]<br>sc_tableversion_logicalsc_generated [setup failure]<br>writes_remsql_names [setup failure]<br>phys_rep_perf<br>simple_timepart_reptimeout_generated<br>simple_timepart<br>commit_delay_on_copy<br>simple_ssl<br>random_osql_replay<br>yast_stat4scan_generated</p>

2024-12-11 15:16 UTC, akshatsikarwar commented
I would also love to see the actual log file names in all the trace that this function prints. For e.g.:
Instead of : `Can't delete log, age %ld not older than log delete age %`
Would like: `Can't delete log.0000000592 , age %ld not older than log delete age`

2024-12-19 16:11 UTC, akshatsikarwar approved these changes

2024-12-19 19:18 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/563 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>oflowaddrem [setup failure]<br>phys_rep_perf<br>rem<br>lostwrite<br>truncatesc_offline_generated</p>

2024-12-20 14:15 UTC, mponomar approved these changes

2024-12-23 20:08 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>4/564 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_inserts_logicalsc_generated [setup failure]<br>basic_snapshot_generated [setup failure]<br>phys_rep_perf<br>truncatesc_offline_generated</p>

2024-12-24 18:37 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/564 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_inserts [setup failure]<br>sc_remsql_fdbpush_generated [setup failure]<br>fdb_push_rte_connect_generated [setup failure]<br>logfill_logput_window_generated<br>phys_rep_perf<br>lostwrite<br>online_compaction<br>sc_resume2<br>truncatesc_offline_generated</p>

2024-12-31 19:55 UTC, merged