Fix bugs in analyze_empty_tables behavior
bloomberg/comdb2 pull request #4892
Opened 2024-12-11 15:19 UTC by aakash10292

Porting https://github.com/bloomberg/comdb2/pull/4883

2024-12-11 16:23 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>33/563 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings [setup failure]<br>sc_dups_logicalsc_generated [setup failure]<br>writes_remsql_names_negativerowid_generated [setup failure]<br>writes_remsql [setup failure]<br>sc_remsql_fdbpush_generated [setup failure]<br>mismatch_class_remsql_rte_connect_generated [setup failure]<br>phys_rep_perf<br>comdb2sys_queueodh_generated<br>comdb2sys_pagesize_generated<br>comdb2sys</p>

2024-12-12 17:58 UTC, aakash10292 commented
aarayambeth Dec 12 10:50:54 2024      success aar_analyze_empty_tables_8.R20241212.3

2024-12-12 23:42 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/563 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>unionpar_maxqueue [setup failure]<br>sc_remsql_fdbpushredirect_generated [setup failure]<br>phys_rep_perf<br>lostwrite<br>truncatesc_offline_generated<br>comdb2sys_queueodh_generated<br>comdb2sys<br>comdb2sys_pagesize_generated</p>

2024-12-13 15:04 UTC, mponomar approved these changes

2024-12-13 15:06 UTC, merged