Fix log delete bug that occurs when there's low disk space
bloomberg/comdb2 pull request #4894
Opened 2024-12-11 15:31 UTC by morgando

2024-12-11 19:58 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>10/592 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_newuniq [setup failure]<br>basic_rowlocks_generated [setup failure]<br>sc_transactional_rowlocks_generated<br>phys_rep_perf<br>analyze_exit_immediately<br>comdb2sys_queueodh_generated<br>comdb2sys_pagesize_generated<br>comdb2sys<br>snap_ha_retry_newsi_generated<br>dbcreate</p>

2024-12-13 20:37 UTC, morgando commented on bdb/file.c
> +         (bdb_state->attr->logdeleteage > now)))
Fix this

2024-12-19 15:55 UTC, akshatsikarwar approved these changes

2024-12-19 20:44 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>134/594 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>writes_remsql_names_negativerowid_generated [setup failure]<br>fdb_compat<br>phys_rep_perf<br>analyze_exit_immediately<br>snapisol_partial_index_off_generated<br>snapisol_noearly_generated<br>snapisol<br>snap_ha_retry_newsi_generated<br>fdb_compat_rte_connect_generated<br>ddl_csc2</p>

2024-12-23 15:56 UTC, merged