Set generation from ckp-logs
bloomberg/comdb2 pull request #4908
Opened 2024-12-14 12:39 UTC by markhannum

Not writing transaction records from full-recovery opened up situations where a node coming up would be able to see the most recently written generation only from checkpoint records.  Because of this bug, it would then start to emit records at a lower generation than had been previously seen.

2024-12-14 17:02 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-12-14 19:37 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/563 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_perf<br>logarchive<br>comdb2sys_queueodh_generated<br>comdb2sys_pagesize_generated<br>comdb2sys<br>sc_downgrade<br>truncatesc_offline_generated</p>

2024-12-14 20:55 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/563 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>analyze_fastinit_race<br>phys_rep_perf<br>logarchive<br>comdb2sys_queueodh_generated<br>comdb2sys_pagesize_generated<br>comdb2sys<br>truncatesc_offline_generated</p>

2024-12-14 23:26 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/563 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>analyze_fastinit_race<br>phys_rep_perf<br>sc_resume2<br>logarchive<br>comdb2sys_queueodh_generated<br>comdb2sys_pagesize_generated<br>comdb2sys<br>truncatesc_offline_generated</p>

2024-12-15 05:27 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-12-16 03:17 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-12-26 17:23 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/567 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_perf<br>logarchive<br>tunables<br>truncatesc_offline_generated</p>

2024-12-26 20:23 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/567 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill_logput_window_generated<br>phys_rep_perf<br>sc_parallel_logicalsc_generated<br>logarchive<br>truncatesc_offline_generated</p>

2024-12-26 21:53 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/567 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>analyze_fastinit_race<br>phys_rep_perf<br>queuedb_rollover<br>nogen_full_recovery_disable_generated<br>nogen_full_recovery_ckpbug_generated<br>truncatesc_offline_generated</p>

2024-12-27 23:14 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/567 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>phys_rep_perf<br>truncatesc_offline_generated</p>

2025-01-02 15:46 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/568 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_perf<br>phys_rep_tiered_firstfile_generated<br>truncatesc_offline_generated</p>

2025-01-04 21:23 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/566 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_perf<br>queuedb_rollover_noroll1_generated<br>analyze<br>sc_datacopy_logicalsc_generated<br>truncatesc_offline_generated</p>

2025-01-05 06:49 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/566 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_perf<br>truncatesc_offline_generated</p>

2025-01-05 18:33 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/566 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>phys_rep_perf<br>truncatesc_offline_generated</p>

2025-01-08 23:09 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/566 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_perf<br>lostwrite<br>truncatesc_offline_generated</p>

2025-01-09 13:33 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/566 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_perf<br>lostwrite<br>truncatesc_offline_generated</p>

2025-01-18 02:26 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/567 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated<br>sc_transactional_rowlocks_generated<br>phys_rep_perf<br>nogen_full_recovery<br>truncatesc_offline_generated</p>

2025-01-21 16:13 UTC, aakash10292 approved these changes
Walked through changes with Mark. LGTM

2025-01-22 13:32 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/567 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>osql_cleanup<br>phys_rep_perf<br>sc_downgrade<br>truncatesc_offline_generated</p>

2025-01-22 14:47 UTC, aakash10292 approved these changes

2025-01-22 14:48 UTC, merged