Fix bugs with phys_rep_perf testcase
bloomberg/comdb2 pull request #4909
Opened 2024-12-14 21:11 UTC by markhannum

This PR addresses copycomdb2 / ssh issues with the phy_rep_perf test case.

2024-12-15 01:32 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>10/591 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>writes_remsql_names_rte_connect_generated [setup failure]<br>ssl_remsql_rte_connect_generated [setup failure]<br>phys_rep_perf<br>analyze_partial_index_off_generated<br>snap_ha_retry_newsi_generated<br>tunables<br>sc_downgrade<br>ssl_remsql_fdbpush_generated<br>dbcreate</p>

2024-12-16 03:28 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>11/591 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>largecsc2 [setup failure]<br>writes_remsql_names_fdbpush_generated [setup failure]<br>writes_remsql [setup failure]<br>long_db_name [setup failure]<br>schemalk<br>phys_rep_perf<br>queuedb_rollover<br>snap_ha_retry_newsi_generated<br>tunables</p>

2024-12-16 18:09 UTC, akshatsikarwar approved these changes

2024-12-16 18:09 UTC, merged

2024-12-16 21:18 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/591 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_tableversion_logicalsc_generated [setup failure]<br>sc_tableversion [setup failure]<br>writes_remsql_names_fdbpush_generated [setup failure]<br>writes_remsql_names [setup failure]<br>phys_rep_perf<br>snap_ha_retry_newsi_generated<br>tunables</p>