Set generation from ckp-logs
bloomberg/comdb2 pull request #4919
Opened 2024-12-17 23:19 UTC by markhannum

Not writing rep-gen transaction records from full-recovery opened up situations where a node coming up would be able to see the most recently written generation only from checkpoint records. Because of this bug, it would then start to emit records at a lower generation than had been previously seen.

Additionally, Emit 'recovery-checkpoints' from recovery, which won't ever be used for matching.  This is necessary because full-recovery needs to write a checkpoint using the most recent generation available in the transaction log.  Because this record isn't emitted from the cluster-master, writing a normal checkpoint on the same generation re-opens the possibility that a replicant will incorrectly match.  Solution is to only emit a 'recovery-checkpoint' from full-recovery.

2024-12-18 03:32 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-12-18 17:37 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-12-18 22:08 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/594 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_perf<br>triggersc_latency<br>logarchive<br>snapisol_partial_index_off_generated<br>snapisol_noearly_generated<br>snap_ha_retry_newsi_generated<br>ddl_csc2<br>simple_remsql_whitelist_generated</p>

2024-12-20 23:31 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>142/595 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_perf<br>nogen_full_recovery_disable_generated<br>commit_delay_on_copy<br>simple_ssl<br>logarchive<br>snapisol_partial_index_off_generated<br>snapisol_noearly_generated<br>snap_ha_retry_newsi_generated<br>ddl_csc2<br>simple_remsql_whitelist_generated</p>

2024-12-21 01:58 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-12-23 05:27 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-12-23 17:12 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>132/596 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill<br>phys_rep_perf<br>nogen_full_recovery_disable_generated<br>analyze_partial_index_off_generated<br>analyze<br>logarchive<br>snapisol_partial_index_off_generated<br>snap_ha_retry_newsi_generated<br>ddl_csc2<br>simple_remsql_whitelist_generated</p>

2024-12-26 18:05 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>8/598 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_perf<br>analyze_partial_index_off_generated<br>logarchive<br>snapisol_noearly_generated<br>snap_ha_retry_newsi_generated<br>ddl_csc2<br>simple_remsql_whitelist_generated<br>sc_lotsoftables_logicalsc_generated</p>

2024-12-27 00:07 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/598 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_perf<br>snapisol_noearly_generated<br>snap_ha_retry_newsi_generated<br>ddl_csc2<br>simple_remsql_whitelist_generated<br>disttxn</p>

2024-12-28 00:40 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/598 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_perf<br>snapisol<br>snap_ha_retry_newsi_generated<br>ddl_csc2<br>simple_remsql_whitelist_generated</p>

2025-01-02 17:15 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/597 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_perf<br>analyze_exit_immediately<br>timepart_trunc_serialsc_generated<br>snapisol<br>snap_ha_retry_newsi_generated<br>ddl_csc2<br>simple_remsql_whitelist_generated</p>

2025-01-04 22:49 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>7/597 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_perf<br>online_compaction<br>snapisol_partial_index_off_generated<br>snapisol<br>snap_ha_retry_newsi_generated<br>ddl_csc2<br>simple_remsql_whitelist_generated</p>

2025-01-05 08:16 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/597 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_perf<br>phys_rep_tiered_nosource_generated<br>snapisol_partial_index_off_generated<br>snap_ha_retry_newsi_generated<br>ddl_csc2<br>simple_remsql_whitelist_generated</p>

2025-01-05 20:13 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/597 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>sc_transactional_rowlocks_generated<br>phys_rep_perf<br>snapisol_partial_index_off_generated<br>snap_ha_retry_newsi_generated<br>ddl_csc2<br>simple_remsql_whitelist_generated<br>phys_rep_tiered_firstfile_generated<br>sc_downgrade</p>

2025-01-09 00:36 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>5/597 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_perf<br>op_makerecord<br>snap_ha_retry_newsi_generated<br>ddl_csc2<br>simple_remsql_whitelist_generated</p>

2025-01-09 14:58 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/597 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_perf<br>snapisol_partial_index_off_generated<br>snapisol_noearly_generated<br>snap_ha_retry_newsi_generated<br>ddl_csc2<br>simple_remsql_whitelist_generated</p>

2025-01-17 02:31 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2025-01-17 20:46 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/595 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>nightmare_recovery</p>

2025-01-18 00:08 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/595 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>nogen_full_recovery_rollout_generated<br>fdb_compat</p>

2025-01-18 03:57 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/595 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated</p>

2025-01-21 23:59 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/595 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>sc_parallel_logicalsc_generated<br>pmux_sqlite_memory_generated<br>pmux_sqlite_file_generated</p>

2025-01-22 14:47 UTC, aakash10292 approved these changes

2025-01-22 14:47 UTC, merged