{176747440}: correctly handling dbinfo under single-port
bloomberg/comdb2 pull request #4921
Opened 2024-12-18 17:23 UTC by riverszhang89

Even when configured single-port, the jdbc driver would start using database ports after receiving a dbinfo response which contains those port numbers. This patch fixes it.

2024-12-18 17:24 UTC, riverszhang89 commented
/cbuild-compile-only

2024-12-18 20:44 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>160/594 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>sc_inserts_logicalsc_generated [setup failure]<br>selectv_range [setup failure]<br>selectv_partial_index_off_generated [setup failure]<br>load_cache [setup failure]<br>writes_remsql_names_negativerowid_generated [setup failure]<br>phys_rep_perf<br>snapisol_partial_index_off_generated<br>snap_ha_retry_newsi_generated<br>ddl_csc2</p>

2024-12-19 21:22 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-12-20 21:04 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>10/595 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>writes_remsql_names_fdbpushredirect_generated [setup failure]<br>ssl_remsql_fdbpush_generated [setup failure]<br>verify_db_parallel_generated [setup failure]<br>phys_rep_perf<br>snapisol_partial_index_off_generated<br>snap_ha_retry_newsi_generated<br>ddl_csc2<br>simple_remsql_whitelist_generated<br>tunables<br>ssl_remsql_rte_connect_generated</p>

2024-12-21 03:37 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-12-23 14:46 UTC, mohitkhullar approved these changes
lgtm

2024-12-23 14:47 UTC, mponomar approved these changes

2024-12-23 14:50 UTC, riverszhang89 commented
@mohitkhullar @mponomar Thank you both for the review!

2024-12-23 14:50 UTC, merged