Block resuming a partition merge schema change
bloomberg/comdb2 pull request #4936
Opened 2024-12-24 18:58 UTC by dorinhogea

Resuming would require sharing the destination newdb,  which involves more complicated code changes and will be adressed in 8.1.

2024-12-24 20:03 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/564 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>fdb_push [setup failure]<br>mismatch_class_remsql_fdbpushredirect_generated [setup failure]<br>phys_rep_perf<br>sc_timepart<br>lostwrite<br>truncatesc_offline_generated</p>

2025-02-05 20:22 UTC, morgando reviewed
Are there any existing tests for resuming partitioned schema changes?

2025-02-05 20:22 UTC, morgando commented on schemachange/sc_logic.c
>      }
Are there any existing tests for resuming partitioned schema changes?

2025-02-05 20:31 UTC, dorinhogea commented on db/osqlcomm.c
> -        sc->partition.type = tt;
we need to communicate to resuming master that this is a partition merge, which info is stored in sc->partition,.type.  The initial code was setting this to PARTITION_NONE to avoid triggering a do_merge inside do_alter_table.

2025-02-05 20:34 UTC, dorinhogea commented on schemachange/sc_alter_table.c
> +    if (s->partition.type == PARTITION_MERGE && !db->sqlaliasname)
Since now we are preserving PARTITION_MERGE (see comment for osqlcomm.c change), we need to avoid calling do_merge instead of do_alter (a do_merge moves data between tables, an alter keeps data in same table).

2025-02-05 20:35 UTC, dorinhogea commented on schemachange/sc_logic.c
> +                sc_del_unused_files(tbl);
strong assumption that sc->db is set at this point.  safer to retrieve from hash.

2025-02-05 20:37 UTC, dorinhogea commented on schemachange/sc_logic.c
> +                }
Correct, otherwise I would start a schema change for a shard ((because it was already in progress on the previous master), before we check that this is a merge that needs to be blocked.

2025-02-05 20:38 UTC, dorinhogea commented on schemachange/sc_logic.c
>      }
A few tests swing the master during schema changes, sc_resume is dedicated for that

2025-02-06 18:52 UTC, morgando commented
`cdb2test   Feb  5 14:38:08 2025      success modsnap_reader_optimization.R20250205.8`

2025-02-19 16:48 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/568 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_perf<br>incremental_backup_load<br>truncatesc_offline_generated</p>

2025-02-20 16:56 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/568 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>analyze_fastinit_race<br>incoherent_slow<br>phys_rep_perf<br>incremental_backup_load<br>truncatesc_offline_generated</p>

2025-02-21 15:49 UTC, morgando approved these changes

2025-02-21 15:51 UTC, dorinhogea commented
@morgando thank you

2025-02-21 15:51 UTC, merged