Allow multi-line ';'-delimited cdb2sql statements
bloomberg/comdb2 pull request #4938
Opened 2024-12-27 18:50 UTC by morgando

See tests for example use

2024-12-27 19:43 UTC, morgando commented on cdb2api/cdb2api.h
> +    CDB2ERR_UNKNOWN_PROPERTY = -112,
TODO: move these

2024-12-27 19:50 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

2024-12-27 19:57 UTC, morgando commented on tools/cdb2sql/cdb2sql.cpp
> +class DdlBlockInputProcessor : public InputProcessor {
I don't like this name

2024-12-27 20:01 UTC, morgando commented on tools/cdb2sql/cdb2sql.cpp
> +            return;
The input line is useless if it is a comment or an empty line and the preceding sql is a comment or an empty line

2024-12-27 22:32 UTC, morgando commented on tools/cdb2sql/cdb2sql.cpp
> +        if (!is_comment_or_empty_line(_sql.c_str())) {
replace with `!_sql.empty()`

2024-12-30 13:22 UTC, mponomar commented
Looks good.  Maybe a different prompt if the last statement was incomplete?
eg:
```
cdb2sql> select
...> 1 as a;
(a=1)
cdb2sql>
```
Just a suggestion, works great without it.

2024-12-30 13:22 UTC, mponomar approved these changes

2025-01-02 22:23 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>131/597 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>autoanalyze [setup failure]<br>logfill_logput_window_generated<br>phys_rep_perf<br>analyze_exit_immediately<br>snapisol_partial_index_off_generated<br>snapisol_noearly_generated<br>snap_ha_retry_newsi_generated<br>fdb_compat<br>ddl_csc2<br>simple_remsql_whitelist_generated</p>

2025-03-07 15:18 UTC, morgando commented
> Looks good. Maybe a different prompt if the last statement was incomplete? eg:
> 
> ```
> cdb2sql> select
> ...> 1 as a;
> (a=1)
> cdb2sql>
> ```
> 
> Just a suggestion, works great without it.

Made this change!

2025-03-12 00:59 UTC, mponomar approved these changes

2025-03-12 16:08 UTC, roborivers requested changes
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/603 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>incremental_backup_load<br>cldeadlock</p>

2025-03-12 19:17 UTC, merged